### ISSUE TITLE
CSV export header names

### ISSUE THREAD

**Issue by ckieler86** [apexcharts/Blazor-ApexCharts#102]
In the generated CSV file you will find 'category' as the first entry.
Is it possible to change this entry in the title of the xaxis, e.g. in 'period' or take a new field?

This is already a feature in the apex library under chart toolbar options : https://apexcharts.com/docs/options/chart/toolbar/#headerCategory

also see 
https://github.com/apexcharts/apexcharts.js/issues/1514#issuecomment-671256319
for use - it appears the export class has not been added yet. 

I have also noticed that the exports are a random string of characters, this appears to also be an option at the toolbar level 

![image](https://user-images.githubusercontent.com/62707326/171720749-c5c3b4e1-5c5a-4bfa-80e4-cbaf647af163.png)

Thanks

**Comment by joadan** [comment]
Hi,

Thank you for reporting, I'll look into this.

**Comment by ckieler86** [comment]
Looks and works great!!! Thanks!

**Comment by joadan** [comment]
Thank you
