### ISSUE TITLE
Download as CSV is not working correctly.

### ISSUE THREAD

**Issue by Zapnologica** [apexcharts/Blazor-ApexCharts#106]
We are using the apex blazor wrapper in our website.

One of the clients just notified us that the download as CSV option is not working correctly.|

![image](https://user-images.githubusercontent.com/3656913/172391838-1e8ad255-7998-4be5-8c81-a34dd4cf8d67.png)

You will see the issue is:

First of all the CSV is not properly breaking up the columns by the comma "," .  In our previous systems, we used to put sep=,   on the first line of the CSV and this fixed the issue.

Secondly the date is only showing the date, not the time.

**Comment by joadan** [comment]
Hi,

Please take a look at https://apexcharts.github.io/Blazor-ApexCharts/features/export#csv%20formatter

Fixed in v0.9.12-beta

**Comment by Zapnologica** [comment]
> Hi,
> 
> Please take a look at https://apexcharts.github.io/Blazor-ApexCharts/features/export#csv%20formatter
> 
> Fixed in v0.9.12-beta

Thank you very much.  This is EXACTLY what we needed.  I have literally had so many phone calls this week moaning about the csv,  this fix worked perfectly and your documentation was perfect.

**Comment by joadan** [comment]
Great that the issue was resolved. 
Please do not forget to star the repo if you like it..
