### ISSUE TITLE
Heatmap colors

### ISSUE THREAD

**Issue by WukovatzD** [apexcharts/Blazor-ApexCharts#109]
Would an extension of the additional color representations be feasible for the heatmap like in [here](https://apexcharts.com/javascript-chart-demos/heatmap-charts/)?

**Comment by joadan** [comment]
Hi.

I think this should be possible, but I'll add some samples to confirm.

**Comment by joadan** [comment]
More samples at: https://apexcharts.github.io/Blazor-ApexCharts/heatmap-charts
