### ISSUE TITLE
Is the Selection Event available?

### ISSUE THREAD

**Issue by kawpls** [apexcharts/Blazor-ApexCharts#116]
I was looking at the events and there just seem to be 4 out of like 15+ I was wondering if I could add it myself by using what the other event callbacks are using.

**Comment by joadan** [comment]
Hello,

PR's are more then welcome. 
We try to follow the Apexchart event style/naming as much as possible, but If there are good reasons we can make exceptions.

Please let me know if you plan to start.. if not I might go for it.

**Comment by kawpls** [comment]
I tried and wasn't able I'm pretty new to js so I'm not sure if I can do it correctly, if you guys could do it it would be awesome I really like the work the team is doing its working pretty flawlessly.

**Comment by joadan** [comment]
I can givi it a try now.. 

Is it just the selection event you are after or are there more events that you need.

**Comment by kawpls** [comment]
only selection

**Comment by kawpls** [comment]
thanks a lot u made my work 100 times easier C:

**Comment by joadan** [comment]
Fixed in v0.9.13-beta

Docs at https://apexcharts.github.io/Blazor-ApexCharts/events/selection

**Comment by kawpls** [comment]
OMG thanks a lot. You are awesome it works perfectly.
