### ISSUE TITLE
ApexSeries Null in certain instances

### ISSUE THREAD

**Issue by constrictor14** [apexcharts/Blazor-ApexCharts#12]
I was encountering a null reference when dynamically adding ApexSeries to an ApexChart in my .razor file in the OnInitialized and Dispose methods of ApexSeries.  It showed up with Chart reporting null and crashing out (highlighted).  I made the following code change to protect against that.  Probably a bit of overkill since I have not seen a Chart.Options be null when the Chart object was initialized. 

Love what you're doing. Thanks so much!

![image](https://user-images.githubusercontent.com/11917484/107997584-15c41a80-6fb1-11eb-9c59-1aac922613cb.png)

**Comment by joadan** [comment]
Hi,

Glad you like the component!

Just to be clear, it works now after the additional null check, or?
From you highlight it looks like the Series was null and not the options, or?

Sorry if I'm missing something obvious here.

**Comment by joadan** [comment]
Clean up
