### ISSUE TITLE
Tooltip at chart with multiple y-axis

### ISSUE THREAD

**Issue by WukovatzD** [apexcharts/Blazor-ApexCharts#130]
Next strange thing upcoming... first of all, i would like to apologise for already bringing work/questions again....

However, using a chart with multiple y-axis (both line-charts) with different value scales are not showing the tooltip combined.
the tooltip is shown for either one value or the other and not both combined as in the documentation.

```csharp
    <ApexChart @ref="_chart" Options="_options" XAxisType="XAxisType.Datetime" TItem="Model" Title="@L["xx"]">

        <ApexPointSeries TItem="Model"
                     Items="_values"
                     Name="@L["T"]"
                     SeriesType="SeriesType.Line"
                     XValue="@(e => e.DateTime)"
                     YValue="@(e => Math.Round(e.Sum, 2))"
                     OrderBy="e=>e.X" />

        <ApexPointSeries TItem="Model"
                     Items="_statusTimeLine.Select(x => new Model(x.SourceTime, x.P))"
                     Name="@L["P"]"
                     SeriesType="SeriesType.Line"
                     XValue="@(e => e.DateTime)"
                     YValue="@(e => Math.Round(e.Sum, 0))"
                     OrderBy="e=>e.X" />
    </ApexChart>

@code {
    private void SetChartOptions()
    {
        _options.Yaxis = new List<YAxis>()
        {
            new YAxis
            {
                Title = new AxisTitle { Text = "" },
                DecimalsInFloat = 2,
            },

            new YAxis
            {
                Title = new AxisTitle { Text = "" },
                DecimalsInFloat = 0,
                Opposite = true
            },
        };

        _options.Tooltip = new()
            {
                X = new() { Formatter = @"function (value) { return `${new Date(value).toLocaleDateString()} ${new Date(value).getHours() < 10 ? '0'+new Date(value).getHours() : new Date(value).getHours()}:${new Date(value).getMinutes() < 10 ? '0'+new Date(value).getMinutes() : new Date(value).getMinutes()}`;}" },
                Y = new()
                {
                    Formatter = @"function (value)
                                {
                                    if(value < 80) { return value + ' '}
                                    return value + ' ';
                                }"
                }
            };
    }
}

```

![grafik](https://user-images.githubusercontent.com/57444032/179496929-d6feabef-c76a-4221-884d-0d8a696e8abe.png)

![grafik](https://user-images.githubusercontent.com/57444032/179496995-d7021ad3-b634-4ded-8eab-6322b9217508.png)

The code has been slightly modified as some values contain interene information.
Many thanks in advance!

**Comment by joadan** [comment]
Thanks for reporting

I'll try to troubleshout as soon as I can.

**Comment by joadan** [comment]
I added a simple example https://apexcharts.github.io/Blazor-ApexCharts/features/formatters#multiple%20y%20axis
Looks like this one is working or I'm I missing something?

**Comment by WukovatzD** [comment]
In case of two different values, i.e. number of persons in corelation to total energy consumption (i.e. two different value units, like count and KW).

Furthermore, if I have only 20 measurements of persons but 5000 of energy values, only one value is displayed as tooltip. Example: Hover over chart shows once the number of persons and when I move the mouse only the energy.

My assumption is that at this point no value is entered. Is this due to Apex-charts itself? A workaround would be to increase the person list to the number of enregie values and play the points but I would like to avoid that :(

Translated with www.DeepL.com/Translator (free version)

**Comment by joadan** [comment]
Sorry for the late reply here with X-Values needs to meatch in each series. 
This is a limitiation of apexcharts.
