### ISSUE TITLE
How to make a real time chart

### ISSUE THREAD

**Issue by jpanext** [apexcharts/Blazor-ApexCharts#131]
Hi,
I'd like to create a real time chart and I do not know how to do that. What is the most efficient way? AddSeries, AppendData,..?
Can you give an example please?

**Comment by joadan** [comment]
Hi,
 
Please check docs here, https://apexcharts.github.io/Blazor-ApexCharts/methods/update-series#realtime

**Comment by jpanext** [comment]
Thank you, it helps. Perhaps in your documentation you should split the update menu and make a "Real time" button, because RT is quite hidden at the bottom of the page.

**Comment by sacalata** [comment]
> Thank you, it helps. Perhaps in your documentation you should split the update menu and make a "Real time" button, because RT is quite hidden at the bottom of the page.

Agree, couldn't find it as well
