### ISSUE TITLE
CandleChart Gap

### ISSUE THREAD

**Issue by kiranmaya** [apexcharts/Blazor-ApexCharts#133]
How to avoid this Irregular time interval gap.
![Screenshot_9](https://user-images.githubusercontent.com/3712631/180623450-5843b24c-042a-4b3d-abb8-b34f1d68864a.jpg)

**Comment by joadan** [comment]
Hello,

Please check https://github.com/apexcharts/apexcharts.js/issues/1191

**Comment by kiranmaya** [comment]
fixed candles Gap, how to set the gap between x-axis labels.

**Comment by kiranmaya** [comment]
fixed with ```
  options.Xaxis = new XAxis
            {
                Labels = new XAxisLabels
                {
                    Rotate=0,
                    Formatter = @"function (value) {
                    if (value === undefined) {return '';}
                    return value.slice(-8).slice(0, 5);}"
                },
                TickAmount=8
            };
```
