### ISSUE TITLE
nuget package

### ISSUE THREAD

**Issue by kiranmaya** [apexcharts/Blazor-ApexCharts#134]
![Screenshot_12](https://user-images.githubusercontent.com/3712631/180656655-f58ccdbd-d184-4f88-9f51-b9b046d91e30.jpg)
Unable to install package via nuget or power shell.is there any other way to add GitHub projects in project file ?

**Comment by joadan** [comment]
Hi,

Check the _Include prerelease_ checkbox

**Comment by kiranmaya** [comment]
it's came in results with pre-release checkbox tick.
