### ISSUE TITLE
No Gridlines on DateTime Axis

### ISSUE THREAD

**Issue by Nachtwind85** [apexcharts/Blazor-ApexCharts#136]
Hi, 

After trying to figure out how to do this i am simply out of my wits but cant really believe this is a bug.. but nevertheless if it is i may just report it:

`                    <ApexChart TItem="cLFCount" Title="(CAST01)"
                            XAxisType="XAxisType.Datetime"
                            Options="options"
                            >

                        <ApexPointSeries TItem="cLFCount"
                                        Items=""
                                        Name=""
                                        SeriesType="SeriesType.Line"
                                        XValue="@(e => e.Date)"
                                        YValue="@(e => e.Count)"
                                        OrderBy="e=>e.X" />

                        <ApexPointSeries TItem="cLFCount"
                                        Items=""
                                        Name=""
                                        SeriesType="SeriesType.Line"
                                        XValue="@(e => e.Date)"
                                        YValue="@(e => (decimal?) e.rollingAverage)"
                                        OrderBy="e=>e.X" />
                    </ApexChart>`

![Bild_2022-07-27_084057491](https://user-images.githubusercontent.com/60173070/181178973-e5e0faf1-d714-4d7f-90f9-5f0321888d16.png)

So far the Chart works somewhat as intended but i need to add gridlines for the (Datetime) x axis as well...
Therefore i added the following parts of code in OnInitializedAsync():

`        options.Grid = new Grid
            {
                Show = true,
                Position = GridPosition.Back,
            };
        options.Xaxis = new XAxis
            {
                AxisTicks = new AxisTicks { Show = true },
                AxisBorder = new AxisBorder { Show = true },
                TickAmount = 48,
                Title = new AxisTitle
                {
                    OffsetY = 5,
                    Text = "Uhrzeit",
                    Style = new AxisTitleStyle { FontSize = "14px", Color = "lightgrey" }
                },

            };`

Unfortunately, as seen on the picture, it wont show any vertical gridlines. I am currently out of my wits and think that this may be some sort of bug.. but if that would be the case i had expected someone else to find it earler... 

I use the following:
Net 6
Blazor-Apexcharts - 0.9.13-beta

Thanks in advance

**Comment by kiranmaya** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/3712631/181877327-507826ba-1031-4623-bc36-96691501d766.jpg)
