### ISSUE TITLE
Prevent color override for the selected point

### ISSUE THREAD

**Issue by ewdlop** [apexcharts/Blazor-ApexCharts#137]
Hello, 
I just have a question. I am using the Bar char and I would like to prevent color override for the selected point/bar,
I am wondering how to go about doing this?

**Comment by joadan** [comment]
Hello,

Sorry for my very late reply.

Could you please try the state option.

`        options.States = new States
            {
                Active = new StatesActive
                {
                    Filter = new StatesFilter { Type = "none", Value = 0 }
                }
            };
`

Please not! in a upcoming release the Type will be an enum rather then a string.

**Comment by ewdlop** [comment]
Thanks!
