### ISSUE TITLE
HeatMap problem

### ISSUE THREAD

**Issue by anton-dot** [apexcharts/Blazor-ApexCharts#138]
Hello!
Have problem with heatmap.

When i add several series with different start date, chart ignore that and starts every series with smalest date.
FE one series starts with 2022-07-01 and another with 2022-07-05.

Chart draws with 2022-07-01, it's correct, but second series start with 2022-07-01, thats not correct :(

But if you handle click on point ( 2022-07-01 second series) , then it give correct date in handle method (2022-07-05).

**Comment by joadan** [comment]
Hello,

I'm sorry for my late reply.

I think this is the same as https://github.com/apexcharts/Blazor-ApexCharts/issues/124 

In short you have to make sure all series have the same X-Axis values.

**Comment by joadan** [comment]
#158
