### ISSUE TITLE
DonutLabelValue Formatter?

### ISSUE THREAD

**Issue by klmcmhrcm** [apexcharts/Blazor-ApexCharts#140]
Enhancement? I couldn't find a way to format a DonutLabelValue in the Blazor-ApexCharts wrapper. I saw a formatter in the Js Documentation, but that functionality does not seem to be wrapped in the Blazor Wrapper. I am new to ApexCharts and Blazor; if I have that wrong, please let me know how? Thank you.

**Comment by joadan** [comment]
Hello,
 
Have you looked at the samples at https://apexcharts.github.io/Blazor-ApexCharts/features/formatters
Please let me know if anything is unclear.
Thank you
