### ISSUE TITLE
Weird behaviour with dynamically added chart series

### ISSUE THREAD

**Issue by hofmannmarkus0** [apexcharts/Blazor-ApexCharts#141]
Run into some strange behavior with v0.9.13-beta on dotnet 6.0
I used a completely new project created from the ``Blazor Server App`` Template in Visual Studio 2022 to replicate this.
The project can be found here: https://github.com/hofmannmarkus0/BlazorApexcharts-Issue-Showcase
The links further down in this issue, all just link to separate pages I created in this project.

I am trying to dynamically add new Point Series elements to a chart using an ``@foreach`` loop in my component.
As long as this happens within ``OnInitialized`` everything works as expected and the point series are all rendered properly.

But as soon as I try to add more series later on (e.g. when a button is pressed), rendering of the new series is somewhat "delayed". The first button click has no visual effect and the second button click finally causes the series added by the first click to be rendered (same with consecutive button clicks). This already includes calling ``ApexChart.UpdateSeriesAsync`` on the chart reference
Example: [component](https://github.com/hofmannmarkus0/BlazorApexcharts-Issue-Showcase/blob/master/BlazorApp1/Pages/WorksButDelayed.razor) and [code behind](https://github.com/hofmannmarkus0/BlazorApexcharts-Issue-Showcase/blob/master/BlazorApp1/Pages/WorksButDelayed.razor.cs)

Calling ``ApexChart.UpdateSeriesAsync`` twice in a row somehow seems to fix this issue, calling ``StateHasChanged`` or ``ApexChart.RenderAsync`` did not result in any improvement with this issue.
Example: [component](https://github.com/hofmannmarkus0/BlazorApexcharts-Issue-Showcase/blob/master/BlazorApp1/Pages/Works.razor) and [code behind](https://github.com/hofmannmarkus0/BlazorApexcharts-Issue-Showcase/blob/master/BlazorApp1/Pages/Works.razor.cs)

Another issue I noticed while working with this was that the chart completely fails to render with javascript typeerrors when I have no chart series at all when initiallly rendering the html (in case I might not have the data to display a series immediately after loading the page) which can be replicated in this example: [component](https://github.com/hofmannmarkus0/BlazorApexcharts-Issue-Showcase/blob/master/BlazorApp1/Pages/CompletelyBroken.razor) and [code behind](https://github.com/hofmannmarkus0/BlazorApexcharts-Issue-Showcase/blob/master/BlazorApp1/Pages/CompletelyBroken.razor)
It also cant recover from this broken state after adding entries to the source list used to generate the point series as this just results in more javascript errors.

I am not entirely sure if I am just missing something or not, so any help/advice would be appreciated. 

(For the last issue, I should be able to work around it in some way, but this does not feel like intended/wanted behavior)

**Comment by joadan** [comment]
Hello,

Thnak you for a detailed report and the repo. I will look into this asap.

**Comment by joadan** [comment]
Hi,

I made a PR with some changes.. please have a look and let me know if anything is unclear.
I will have one more look on the second issue, I might be something we can prevent in the integration.
However it is not simple because with no series we are missing some vital information for the chart.

**Comment by hofmannmarkus0** [comment]
Hello,

thank you for the suggestions.
They definitely work for me in the test project and helped me identify some misunderstandings on my end.

I had tried to add a delay earlier, but so far when I had to use delays, it never mattered wether it blocked the thread completely or just delayed execution of the method and therefore I had tried it using ``Task.Delay(10).Wait()`` which obviously also blocks blazor from syncing the changes, and coming from working with wpf and similar desktop ui frameworks, the concept of needing to wait for the changes to be synced with the components was new to me.

Using ``await Task.Delay(10)`` as you suggested worked here.

For the second issue, I just found the ``NoData`` option. Setting that and adding an empty chart series instead of having no series at all, I can render an empty chart with a hint about having no data, which I prefer over hiding the chart completely in my real use-case, though disabling the chart with the ``@if (Series != null && Series.Any()`` also worked to prevent the issue.

Thanks again for the suggestions as they really helped me figuring out what I was doing the wrong way.

**Comment by hofmannmarkus0** [comment]
just as an addition: for the second "issue" it would be nice if this wrapper could show a warning/error message that makes it more obvious whats wrong as the javascript errors where not really helping with finding the cause.
________________________________

**Comment by joadan** [comment]
#158

**Comment by hofmannmarkus0** [comment]
just as an addition: for the second "issue" it would be nice if this wrapper could show a warning/error message that makes it more obvious whats wrong as the javascript errors where not really helping with finding the cause.
