### ISSUE TITLE
Adding PlotOptions for Area Chart

### ISSUE THREAD

**Issue by Aerevia** [apexcharts/Blazor-ApexCharts#146]
Hello,
Thanks for the library ! 
I cannot find the PlotOptions for Area type chart : https://apexcharts.com/docs/options/plotoptions/area/
Can I modify this option somewhere if it's not in the library's options yet ?

**Comment by joadan** [comment]
Hi,

Looking at it now...

**Comment by joadan** [comment]
Hi,

I have fixed it, added sample https://apexcharts.github.io/Blazor-ApexCharts/area-charts#plotoptions 
New release will be deployed later today.

Thank you

**Comment by joadan** [comment]
Fixed in v0.9.14-beta

**Comment by Aerevia** [comment]
Works perfectly, thanks for the fast fix !
