### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'type') for Apex Chart in react js

### ISSUE THREAD

**Issue by MD-Mehedi-Hasan18111** [apexcharts/Blazor-ApexCharts#149]
I get this error when I am using the apex chart. I also pass the props type for chart. after reloading the page I get this error I don't understand why I get this error. Please help!
![image](https://user-images.githubusercontent.com/86622586/191091926-3fe80f57-9b83-4760-b071-2e2ef161f1fa.png)
![image](https://user-images.githubusercontent.com/86622586/191092041-7e9fb8a3-ae7a-4e5e-adf3-79600b550abd.png)

**Comment by joadan** [comment]
Hello,

This repo is the Blazor wrapper for apex charts, looks like you are using react.
https://github.com/apexcharts/react-apexcharts is the react wrapper repo.

Thank you,
