### ISSUE TITLE
Change color based on value and conditions.

### ISSUE THREAD

**Issue by OrionRiftStudios** [apexcharts/Blazor-ApexCharts#150]
thank you for this amazing library.

I would like to know if it is possible to change the color based on the value 
example
value= 100 color should be green
value = -20 color should be red 
I found an example using JS but I would like to know if this library is supporting this scenario
https://stackoverflow.com/questions/64284389/how-to-change-bar-color-at-a-specific-value-with-apex-charts

Thank you

**Comment by joadan** [comment]
Hi,

Have you checked this sample, https://apexcharts.github.io/Blazor-ApexCharts/bar-charts#negative%20values

Thank you
