### ISSUE TITLE
Shadow on Pie's number

### ISSUE THREAD

**Issue by gueganalice** [apexcharts/Blazor-ApexCharts#151]
Hi,

There is a shadow on the Pie's number.

Is it possible to remove it ?
![Shadow pie](https://user-images.githubusercontent.com/91895630/191530379-01e65d9a-6ef2-4327-89d7-138279869b10.png)

**Comment by joadan** [comment]
Hi, 

You can turn it off like this:
 options.DataLabels = new DataLabels { DropShadow = new DropShadow { Enabled = false } };

In Apexchart.js the default is that drop shadow is turned off, I'll investigate if we should do a breaking change and have the same behavior.

**Comment by gueganalice** [comment]
it's working, thank you
