### ISSUE TITLE
Date Range graph : tooltips format time

### ISSUE THREAD

**Issue by MAYSACOLS** [apexcharts/Blazor-ApexCharts#153]
Hello, 

I create a timeline with a Date Range graph. When I pass the mouse on a bar, I just have date information, I'd like to have the date and time information. The YminValue and YMaxValue are at the UnixTimeMilliseconds, but I don't try to get the time with this.

<ApexChart TItem="Event"
                               Title="Projects"
                               Options=optionsTimeline
                               XAxisType="XAxisType.Datetime">

                            <ApexRangeSeries TItem="Event"
                                         PointColor="e=> e.EventType.HexaColor"
                                         Items=GetTimeLine()
                                         XValue="@(e => e.EventType.Name)"
                                         YMinValue="@(e =>e.Start.ToUnixTimeMilliseconds())"
                                         YMaxValue="@(e =>e.End.ToUnixTimeMilliseconds())" />
                        </ApexChart>
Could you help me ?

Thanks a lot

![2022-09-27_15h23_19](https://user-images.githubusercontent.com/114493877/192538896-a03a511f-ce48-4f29-8218-93f482a92216.png)

**Comment by joadan** [comment]
Hello,

Please try the TooltipX option, something like this:

`     options.Tooltip = new ApexCharts.Tooltip
            {
                X = new TooltipX
                {
                    Format = "dd MMM yyyy HH:mm"
                }
            };`

more info here https://apexcharts.com/docs/datetime/

**Comment by joadan** [comment]
I updated the sample: https://apexcharts.github.io/Blazor-ApexCharts/rangebar-charts#date%20range

**Comment by MAYSACOLS** [comment]
Thanks a lot Joadan, that's what I done.
Just one any question. whould you know how to change the width and height of the tooltip ? I don't found anything here 
https://apexcharts.com/docs/options/tooltip/
thank you for your help

**Comment by joadan** [comment]
Not sure how to do that, but If you want full control over the tooltip you can use the Custom tooltip function.
Please check here https://apexcharts.github.io/Blazor-ApexCharts/features/tooltip

**Comment by joadan** [comment]
I you use a custom tooltip you have full control over the formating.
Just format the data in the template, the Tooltip.Format ha no effect when using a custom tooltip

**Comment by MAYSACOLS** [comment]
Hi,

if it can help anyone.

` <ApexChart TItem="Event"
                               Title="my title"
                               Options=optionsTimeline
                               XAxisType="XAxisType.Datetime">
                                    <ApexPointTooltip>
                                         <div class="p-1">
               
                  
                                                        <Row class="mb-2">
                        
                                                            <RowCol Auto>
                                                                    @context.DataPoint.Items.Min(e=>e.Start).ToLongTimeString() -
                                                            </RowCol>
                                                            <RowCol Auto>
                                                                    @context.DataPoint.Items.Min(e=>e.End).ToLongTimeString()
                           
                                                            </RowCol>
                                                        </Row>

                                                        <Row>
                      
                                                            <RowCol Auto>                    
                                                                                  (@context.DataPoint.Items.Min(e=>e.Duration)
                                                            </RowCol>
                                                        </Row>
             
                                                </div>
                                            </ApexPointTooltip>
                                 <ChildContent>
                                    <ApexRangeSeries TItem="Event"
                                        PointColor="e=> e.EventType.HexaColor"
                                        Items=GetTimeLine()
                                        XValue="@(e => e.EventType.Name)"
                                        YMinValue="@(e =>e.Start.ToUnixTimeMilliseconds())"
                                        YMaxValue="@(e =>e.End.ToUnixTimeMilliseconds())" />
                                 </ChildContent>  
                        </ApexChart>

thank you Joadan.`
