### ISSUE TITLE
MudBlazor Error - Script Reference Order

### ISSUE THREAD

**Issue by krugertech** [apexcharts/Blazor-ApexCharts#156]
I am getting random ApexChart reference errors when working with MudBlazor v6.015.
 
**Error:**
![image](https://user-images.githubusercontent.com/28920021/193585375-d87e1c38-0962-4e36-877d-c074ea7c8f8f.png)

I found that by re-prioritising index.html ApexChart &  MudBlazor references resolves the problem (at least for a while). 

MudBlazor after WebAssembly, ApexCharts after MudBlazor. Works until it fails.
```
    <script src="_framework/blazor.webassembly.js"></script>
    <script src="_content/MudBlazor/MudBlazor.min.js"></script>
    <script src="_content/Blazor-ApexCharts/js/apex-charts.min.js"></script>
    <script src="_content/Blazor-ApexCharts/js/blazor-apex-charts.js"></script>
```

Alternatively if the above configuration fails, swapping the order by having ApexCharts first and then MudBlazor works again. 
   ```
    <script src="_framework/blazor.webassembly.js"></script>
    <script src="_content/Blazor-ApexCharts/js/apex-charts.min.js"></script>
    <script src="_content/Blazor-ApexCharts/js/blazor-apex-charts.js"></script>
    <script src="_content/MudBlazor/MudBlazor.min.js"></script>
```

**Update 2**
It appears that only Chrome browser is affected. I've updated to the latest Chrome browser with no difference.
NOTE: FireFox & Brave consistently work.

**Comment by joadan** [comment]
Hello,

I was unable to reproduce, could you check this repo https://github.com/joadan/MudAndApex if you have the same issue.
Works for me with chrome 105.0.5195.127 
Thank you 

Regards Joakim

**Comment by krugertech** [comment]
Hi Joakim,

Thanks. 

I don't appear to have issues with the linked repo. 
I am going to close this issue as the problem cannot be reproduced at the moment.
