### ISSUE TITLE
Delayed title and series name update

### ISSUE THREAD

**Issue by montekarlos** [apexcharts/Blazor-ApexCharts#165]
See PR: https://github.com/apexcharts/Blazor-ApexCharts/pull/164 for a demonstration and further explanation

**Comment by joadan** [comment]
Hello,

Please try to add 
` await Task.Delay(1);`
before the UpdateOptionsAsync

check sample at https://apexcharts.github.io/Blazor-ApexCharts/methods/update-options#maintain%20zoom

**Comment by montekarlos** [comment]
Could you explain why this works? In my usage I found I had to add a delay AFTER the UpdateOptionsAsync. Adding a delay before didn't seem to help at all - including add a much larger delay.

Furthermore this only helped to update the title name. The series name didn't update for me unless I did a double update.

**Comment by joadan** [comment]
I have updated the sample to also update series name.
It looks like it is working.
We need to add the await Task.Delay so blazor can update the component parameters.

**Comment by montekarlos** [comment]
Thanks for that - it pointed me in the right direction.

What I *think* the root cause of the issue is this: https://github.com/dotnet/aspnetcore/issues/22159

Unless we give blazor the chance (`await Task.Delay(1)`) to refresh it's view of the component via the renderer then calling into the javascript causes a sychronous render that uses the old state

The suggested solution there 
`await Task.Yield()` 
also works for me and I think that's slightly cleaner.

**Comment by joadan** [comment]
Thanks for the update.

I agree the await Task.Yield() is much cleaner. 
Maybe this should be in the component call so we don't have to call it from the outside..
