### ISSUE TITLE
Setting Chart Size

### ISSUE THREAD

**Issue by vsia7** [apexcharts/Blazor-ApexCharts#169]
How can I set the chart height? I can see that there is a Height property in options.Chart, but setting this to an integer or string - like 300px - does not change the height.

thanks

**Comment by joadan** [comment]
Hello,

This should work, please see sample at https://apexcharts.github.io/Blazor-ApexCharts/features/chart-size

**Comment by vsia7** [comment]
this works, thank you very much for your help!
