### ISSUE TITLE
Shape property for discrete points

### ISSUE THREAD

**Issue by bdcodestuff** [apexcharts/Blazor-ApexCharts#171]
Hi -- thanks for the excellent library.

I noticed that the discrete marker implementation in Blazor-ApexCharts doesn't have a shape property like apexcharts.js does (see: https://apexcharts.com/docs/options/markers/ ).

Any chance that could be added?

**Comment by joadan** [comment]
Hello,

I'm on it!

**Comment by bdcodestuff** [comment]
Thanks, that looks perfect!

**Comment by joadan** [comment]
Fixed in [v0.9.16-beta](https://github.com/apexcharts/Blazor-ApexCharts/releases/tag/v0.9.16-beta)
