### ISSUE TITLE
Customize `fontfamily` and `fontsize` globally

### ISSUE THREAD

**Issue by Gopichandar** [apexcharts/Blazor-ApexCharts#179]
Is there a way to set `fontfamily` and `fontsize` globally across the charts? I couldn't able to see any docs for the same.

I'm using [Mudblazor](https://mudblazor.com/) and have to set the font from the theme.

**Comment by joadan** [comment]
Hello,

There is no build it feature for this. 

You could have service that would generate a default ChartOptions object with the font settings.
Each chart could then get a default a default object from the service.

**Comment by Gopichandar** [comment]
Thanks for the info @joadan
