### ISSUE TITLE
Persistent CSV Download

### ISSUE THREAD

**Issue by Covenant-Nethengwe** [apexcharts/Blazor-ApexCharts#180]
Good day,

When I download the csv, it sometimes gives the correct values and other times the values are wrong.

**Comment by Covenant-Nethengwe** [comment]
![Screenshot 2022-12-05 121028](https://user-images.githubusercontent.com/53678020/205610983-0dfe3a1e-deb7-4767-8443-7c811e61bc58.png)

**Comment by joadan** [comment]
Hello,

Not sure what could be the issue here. 
Is it possible for you to create a minimal repo reproducing the error?

**Comment by Covenant-Nethengwe** [comment]
Yeah sure, here is the link to the repo

https://github.com/Covenant-Nethengwe/apexchart-bug

**Comment by joadan** [comment]
Hi,

I'm sorry but I really need someting that I can run to duplicate the error.
Thank you
