### ISSUE TITLE
Missing properties

### ISSUE THREAD

**Issue by proteauj** [apexcharts/Blazor-ApexCharts#181]
Hi,

I need to know how to set these properties in plotOptionsBar since they are not available in the wrapper
- BorderRadiusApplication
- BorderRadiusWhenStacked

![DAB7B318-B595-439C-A0AB-949B6D468F94](https://user-images.githubusercontent.com/15527621/206606920-af703101-ae02-47d0-aca1-11aff1af9bdc.png)
![E66A83AA-485C-4F1F-9C4E-4F02AC0F25D3](https://user-images.githubusercontent.com/15527621/206606921-b30844de-f292-48ff-a98f-85f5f1654ec5.png)

**Comment by joadan** [comment]
Hi

Looks like I missed this, I'll add it asap.

**Comment by joadan** [comment]
#182

**Comment by joadan** [comment]
Updated sample: https://apexcharts.github.io/Blazor-ApexCharts/bar-charts#stacked

Please note, not yet released.

**Comment by joadan** [comment]
Fixed in  v0.9.17-beta

**Comment by proteauj** [comment]
Thank you,

I will add this in our mobile app graphs on monday.

Julie Proteau
Cellulaire (438) 728-2728

Le 7 janv. 2023 à 10:46 AM, Joakim Dangården ***@***.***> a écrit :

﻿

Fixed in v0.9.17-beta
