### ISSUE TITLE
Got a JS exception when using ApexChart.FormatYAxisLabel since 0.9.16-beta

### ISSUE THREAD

**Issue by nicolasjolet** [apexcharts/Blazor-ApexCharts#183]
Hello,

Since I've upgraded from 0.9.15-beta to 0.9.16-beta some charts are empty and I got the following error in the browser console :
![image](https://user-images.githubusercontent.com/23367258/206925142-907a0e24-e702-41ba-9279-dc9da920ecfe.png)

If I do not use the ApexChart.FormatYAxisLabel property, it runs fine.
If I downgrade the nuget package to 0.9.15-beta, it runs fine too.

Thank you by advance :)

**Comment by joadan** [comment]
Hi,

Are you running .net 7?
I suspect this is related to https://github.com/apexcharts/Blazor-ApexCharts/pull/176.

**Comment by joadan** [comment]
I was able to reproduce, fix will be released asap.

However please note that ApexChart.FormatYAxisLabel is not supported in blazor server.
https://apexcharts.github.io/Blazor-ApexCharts/features/formatters#use%20dotnet

This fix is to handle the error more gracefully.

**Comment by nicolasjolet** [comment]
I'm running .net 6, but indeed I'm on blazor server.
Thank you for the quick response :)
