### ISSUE TITLE
Error on ApexChart.OnDataPointSelection when used along with ApexChart.Option

### ISSUE THREAD

**Issue by nicolasjolet** [apexcharts/Blazor-ApexCharts#184]
Hi again :)

I'm using the `ApexChart.Option` property in order to remove the toolbar and the `ApexChart.OnDataPointSelection` to show some statistics depending on the selected month in my chart.

Using both properties results in an exception at the second (and subsequent) time I select a column in the chart (no matter if I select the same column twice, or another column)
![image](https://user-images.githubusercontent.com/23367258/207165567-8cbf756c-babe-4909-9141-0050a33044a4.png)

If I don't set the ApexChart.Option on the chart, no issues.

Any clues ? :-)

.net6 + 0.9.16-beta

**Comment by joadan** [comment]
Hello,

Not sure what is going on this should be straight forward. 
Can you share any code so I can reproduce?

Thank you

**Comment by nicolasjolet** [comment]
OK I've found what causes the issue and how to avoid it:

In the following snippet, using the ApexChart.Options from property `WithoutToolbar1` initialized inline causes the issue.
Using `WithoutToolbar2` initialized in the `OnInitializedAsync` method works.

```csharp
<ApexChart TItem="Order" Title="Order Net Value"
           OnDataPointSelection=DataPointsSelected
           Options="WithoutToolbar2">

    <ApexPointSeries TItem="Order" Items="Orders" Name="Gross Value" SeriesType="SeriesType.Bar"
                     XValue="@(e => e.Country)"
                     YValue="@(e => e.Value)"/>
</ApexChart>

@code
{
    class Order
    {
        public string? Country { get; set; }
        public int Value { get; set; }
    }

    List<Order>? Orders => Enumerable.Range(1, 10).Select(i => new Order { Country = "C" + i, Value = i }).ToList();
    ApexChartOptions<Order> WithoutToolbar1 => new () { Chart = new Chart { Toolbar = new Toolbar { Show = false } } };
    ApexChartOptions<Order>? WithoutToolbar2 { get; set; }

    void DataPointsSelected(SelectedData<Order> selectedData) => Console.WriteLine(selectedData.DataPointIndex);

    protected override Task OnInitializedAsync()
    {
        WithoutToolbar2 = new ApexChartOptions<Order> { Chart = new Chart { Toolbar = new Toolbar { Show = false } } };

        return base.OnInitializedAsync();
    }
}
```

Again, the issue stated in the first comment only occurs on the second call of the `OnDataPointSelection` method.
The options apply correctly whatever I use the property `WithoutToolbar1` or `WithoutToolbar2`.

I don't know if this is logical?

**Comment by joadan** [comment]
Hello,

The line 
`ApexChartOptions<Order> WithoutToolbar1 => new () { Chart = new Chart { Toolbar = new Toolbar { Show = false } } };`
will always generate a new options object when requested.
This will remove all other settings written by the the chart.

A better option would be something like: 
`private ApexChartOptions<Order> withoutToolbar1  =  new (){ Chart = new Chart { Toolbar = new Toolbar { Show = false }} };`

Thank you.

**Comment by nicolasjolet** [comment]
Sounds fair, thank you :)
