### ISSUE TITLE
Flexbox charts overflow

### ISSUE THREAD

**Issue by tommmmmm2** [apexcharts/Blazor-ApexCharts#185]
Hi, I've started to use flexbox and after page reload chart has too big width. When page is resized the width is correct. Problem occurs only after fresh reload.  What should I set to fix this? 

Thanks,
T.

**Comment by joadan** [comment]
Hi,

Have you checked this, https://stackoverflow.com/questions/55326858/apex-charts-dont-resize-properly-when-using-flexbox?

I will look into this more as soon as I have some time.
Please update if you manage to resolve it.

**Comment by tommmmmm2** [comment]
Hi, thanks, yes I've seen this, however cannot find any solution. It looks that chart is rendered too fast and from this reason it cannot get correct width. After page resize it is sized correctly. It would be great if you could see into this. 
Thanks!

**Comment by tommmmmm2** [comment]
Hi, any update on this?

**Comment by joadan** [comment]
Hello

Sorry for the delay.
I took a quick look but couldn't reproduce. I don't really know css that well so maybe I'm missing something here.
Would it be possible for you to create a repo that shows the problem?

Regards Joakim

**Comment by joadan** [comment]
Clean up
