### ISSUE TITLE
Event for shared tooltip.

### ISSUE THREAD

**Issue by jneufferrpm** [apexcharts/Blazor-ApexCharts#186]
I am trying to use the OnDataPointEnter and OnDataPointLeave to find the currently hovered tooltip, however this causes shared tooltip to be disabled. Is there any way to use shard tooltip and have an event when it is triggered?

**Comment by joadan** [comment]
Hi,

I belive this is a limitation in Apexcharts.
Check https://apexcharts.com/docs/options/chart/events/ and the dataPointMouseEnter function the documation says:

_Note: When using in line/area charts, this event requires tooltip.intersect: true & tooltip.shared: false along with markers.size has to be greater than 0_
