### ISSUE TITLE
Missing Property for Radial Bar

### ISSUE THREAD

**Issue by ckieler86** [apexcharts/Blazor-ApexCharts#187]
Hello, 

I noticed that the _Formatter_ property is missing from the RadialBarDataLabelsTotal class.

https://github.com/apexcharts/Blazor-ApexCharts/blob/3768630dd4c672cff72e5b07cd0d5218dae6a93b/src/Blazor-ApexCharts/Models/ApexChartOptions.cs#L1114

https://apexcharts.com/docs/options/plotoptions/radialbar/

![image](https://user-images.githubusercontent.com/62707326/209229210-335fa970-d9c3-473f-b174-0136320cddf4.png)

I have also noted that the RadialBarDataLabelsName FontSize is overridden by the RadialBarDataLabelsTotal FontSize 

Thanks!

**Comment by joadan** [comment]
Fixed in  v0.9.17-beta
