### ISSUE TITLE
Selection Event not fully working on timeline/range bar

### ISSUE THREAD

**Issue by kawpls** [apexcharts/Blazor-ApexCharts#188]
The selection events only enters the selection method after the mouse leaves the chart area but not while growing or moving the selection.

**Comment by kawpls** [comment]
![image](https://user-images.githubusercontent.com/58341472/209386383-0cdce97d-0fa8-473d-86a6-0fd5c11e1cab.png)

**Comment by kawpls** [comment]
![image](https://user-images.githubusercontent.com/58341472/209386488-e8ece095-f53b-4695-b41a-4026319c80b1.png)

**Comment by kawpls** [comment]
![image](https://user-images.githubusercontent.com/58341472/209386616-f603f25a-fa3c-4a46-aa3a-7fbebe866b20.png)
If this is removed the selection works but the graph stops working

**Comment by kawpls** [comment]
![image](https://user-images.githubusercontent.com/58341472/209390107-641c1b21-44ad-47d4-9808-1d4d73b0e1b6.png)

**Comment by joadan** [comment]
Hello,

Could you share a minimal repo where this issue can be reproduced?

Thank you,

**Comment by kawpls** [comment]
> Hello,
> 
> Could you share a minimal repo where this issue can be reproduced?
> 
> Thank you,
Yes, Here is the repo anyhelp would be greatly appreciated. 
https://github.com/kawpls/Graphs

**Comment by kawpls** [comment]
https://streamable.com/xqk82x This is a video of the issue

https://tiny-llama-5c1097.netlify.app/ And this is the live site so you can test it out

**Comment by joadan** [comment]
Thank you for the repo, I was able to reproduce.
I belive this is related to https://github.com/apexcharts/apexcharts.js/issues/3533

**Comment by joadan** [comment]
I created a code pen where this can be reproduced in Apexchart https://codepen.io/joadan-the-sasster/pen/PoBpZGO

**Comment by kawpls** [comment]
ohh ok, so this is not a problem withing the blazor wrapper but on the js library? is there a way to "hide" the bug or make a selection on the chart work by myself?

**Comment by joadan** [comment]
This appears to be fixed in apexcharts.js.
Please re-open if the problem still exists.
