### ISSUE TITLE
Fill property not working as expected?

### ISSUE THREAD

**Issue by fresh4** [apexcharts/Blazor-ApexCharts#19]
ApexChartOptions.Fill doesn't seem to be working as expected, or at all, unless I'm missing something. Here is my code:
```C#
options.Fill = new Fill {
            Type = "gradient",
            Gradient = new FillGradient {
                Stops = new List<double> { 0, 50, 100 },
                GradientToColors = new List<string> { "#32F16C", "#F13232" },
                Shade = "dark",
                Type = "vertical",
                OpacityFrom = 0,
                OpacityTo = 1
            }
        };
```
I've tested this with a regular radial chart as well as a series radial chart, and the options filled in seem to do literally nothing to the colors if the code wasn't there no matter how much I change them. The same goes for 'gradient' as 'pattern'. Am I missing something? Or does it just not work? Either way, I think this should be documented or sampled better for reference.

**Comment by joadan** [comment]
I have made improvments related to the fill options. Please check [sample](https://apexcharts.github.io/Blazor-ApexCharts/area-charts) fill

Please re-open if there are still issues.
