### ISSUE TITLE
Blazor component fails to draw in first attempt

### ISSUE THREAD

**Issue by haroon72** [apexcharts/Blazor-ApexCharts#190]
I have simple 5 points to draw the chart and it fails on first attempt and on second refresh it loads chart?

**Comment by sweco-bepema** [comment]
That seems to be a problem with the page loading, not of the component: you are trying to run a function on a component that hasn't been loaded yet on the page.

A better understanding of how the async operation works should help you there. I'm also a beginner, so I'm not the best person to explain it to you, and you didn't share any code, so it's hard to help out.

**Comment by haroon72** [comment]
Fixed the issue. Loading the component in "OnAfterRenderAsync" event in blazor. The component is JS and anything related to JS is run after Component is rendered.

**Comment by sweco-bepema** [comment]
I didn't know that, thanks for sharing the solution

**Comment by joadan** [comment]
Clean up
