### ISSUE TITLE
Failing to plot a simple List<double> with 8760 points as a line chart

### ISSUE THREAD

**Issue by sweco-bepedm** [apexcharts/Blazor-ApexCharts#191]
Hello guys,

I just came across this library, this is fantastic, thanks for the work! I've succeeded in creating really complex graphs with so few lines of code that now I want to convert all my graphs! Here goes some examples:

![image](https://user-images.githubusercontent.com/12100722/210997952-8d3c669c-36b1-4800-a531-d2167ec8ddc8.png)

and this is all the code I wrote:

`<ApexCharts.ApexChart TItem="Zone">
<ApexCharts.ApexPointSeries
                                TItem="Zone"
                                Items="building.Zones.Where(x => x.REVITOccupation > 0)"
                                SeriesType="ApexCharts.SeriesType.Pie"
                                XValue="@(e => e.REVITSpaceKey)"
                                OrderBy="@(e => e.X)"
                                YAggregate="@(e => e.Sum(e => e.REVITOccupation))"
                                />
                        </ApexCharts.ApexChart>`

That's incredible. My previous library would require me to write code in WASM and in C#.... Thanks again for the porting.

But the reason I'm writing is that I can't seem to be able to create the most simple kind of graph, a List of doubles. I am trying to do something like this:
![image](https://user-images.githubusercontent.com/12100722/210998482-5f38989f-b2cc-448c-9e22-2b97fa1d7c66.png)

and i was expecting the code to be as short as the last one, so I wrote the following:
`<ApexCharts.ApexChart TItem="double">
						<ApexCharts.ApexPointSeries TItem="double" 
													Items="@this.BuildingInUse.Heat.Space.Hourly"
													SeriesType="Apex.SeriesType.Line"
													YValue="@(e => e)"
													Name="Space Heating" />
						</ApexCharts.ApexChart>`

where the Item supplied is of type `List<double>`. I can't compile it, says that my YValue needs to be of decimal type.

I've looked in the documentation, but there are no examples of how to deal with a large dataset of 10.000 points, for example. Any help would be appreciated.

**Comment by joadan** [comment]
Hello,

Thank you for the feedback.

For a simple list question, you have to create a class thank you can use to populate the chart.
for example: 
`    private class ValuePoint
    {
        public decimal Value { get; set; }
        public int Position { get; set; }
    }`
Just populate a list of ValuePoint to the chart.
You an easily convert an double to decimal.

For a performance example please check: https://apexcharts.github.io/Blazor-ApexCharts/features/performance
Please note that Apexchart is SVG based so each datapoint will be an SVG dom element. With many datapoints the browser will start to struggle.

**Comment by sweco-bepema** [comment]
Hello again,

There seems that I had a problem with the async part of the code, still trying to figure out how to fix that. 
But for now I did a workaround, and the graph is taking 60 seconds to load with 8760 points. That is VERY different than the very interesting webpage you sent, where 10.000 points were loaded in under 2 seconds. Any idea why that is?

**Comment by joadan** [comment]
Hello,

What is included in the 60 seconds? Is this also taking into account loading the the data from an external source. In my example is when we already have the data in memory.

**Comment by sweco-bepema** [comment]
Hi Joadan,

Still running some tests here. This is what I'm trying to execute in the code:
<img width="200" alt="image" src="https://user-images.githubusercontent.com/12100722/214304159-c7de0995-bb68-42ab-990e-35a82d527903.png">

3 graphs that are updating based on a selection from the table on the left. Each graph 168 points, and currently it's taking me around 5 seconds to refresh the graph. This is how I set up the stopwatch for performance evaluation:

![image](https://user-images.githubusercontent.com/12100722/214304576-c1c67449-7a9c-4e54-a88a-dc7fb245aa54.png)

So I divided the timer into three categories, data fetching, graph data reloading and option reloading. The performance is the following:
* 3 ms data fetching
* 3152 ms series updating
* 948 ms option updating

This is another test than the one I described above (that test does not exist anymore), but the results are very much in line with the performance I reported previously. 3 seconds data loading has quite some impact in the UX, and I see your example loading 20000 points in less time than mine, so I'd like to understand why that is. Any thoughts?

**Comment by joadan** [comment]
Hello, 

In your sample you are measuring the time to update all three charts, so you should divide the number by 3.
It's hard to give any advice with the information you give me, for example what is going on in ConvertToTypicalWeekPoints?
If possible try to create a simple repo that illustrate the problem and I can have a look.

**Comment by sweco-bepema** [comment]
hey joadan,

My example is indeed dividing by 3, but I only had 168 points. If I would have 8760 points, with the same performance, it would be around 9 seconds per graph, which is still way too far than the performance.

I have the feeling that the problem is because I was using a listed numeric entries, with X-values ranging from 1 to 8760. When I passed it as a date, it sped up. I've seen that behavior, but I didn't have the time to run some tests. Will report as soon as I do it. And I will set up an example based on your code, to rule out any problems with the code on my side.

**Comment by sweco-bepema** [comment]
Hey there joadan,

It took me quite some time but, as promised, I got back to you, and this time with all the sauce so you can test it on your side.
I've created a little repo showing a page taking never less than 30 seconds to load a line graph with 8760 points. Here is the repo:

https://github.com/sweco-bepema/ApexChartTest

**Comment by joadan** [comment]
Hello,

Thank you for the repo.

The bulk of the time is for the browser to render the chart. it has nothing to do with the wrapper.
Apexchart is svg based this means that every object is an SVG node and if the number of nodes is high then it takes a long time for the browser to render the chart. I turned of XAxis labels and ticks in your sample and was able to get a much better response.

However I think you should really consider if you have to render so many points at the same time. It 
hard for anyone to make something out of that chart. Would it be an option to group the data?
