### ISSUE TITLE
Support for localization

### ISSUE THREAD

**Issue by MithrilMan** [apexcharts/Blazor-ApexCharts#193]
Hello, thanks for the binding.
Would be nice if you could support localization too, I see apexchart supports localization https://apexcharts.com/docs/localization/
and I see chart options supports the Locale functions but it's a chart instance options

Would be nice to have a better localization support, can it be set once and work everytime without specifying it on every chart instance?
I've never used apexchart JS but looking at the doc I see you can set locale globally

```
Apex.chart = {
  locales: [...localeConfigurationObject],
  defaultLocale: "en"
}
```

In a blazor fascion I could imagine an API like
```
ApexChart.Configure(options => 
   options
      .AddLocale(MyCustomLocaleDefinition)
      .SetDefaultLocale("en")
)
```
to use in Program.cs

**Comment by joadan** [comment]
Hello,

I have looked inot this before, but we felt that it's as easy just to have a singleton service that would generate the a default chart options instance. then you don't have to re-create it each time.
Not sure if this make sense to you. 

 Regards Joakim
