### ISSUE TITLE
Bug when sharing ApexChartOptions between two graphs

### ISSUE THREAD

**Issue by sweco-bepema** [apexcharts/Blazor-ApexCharts#197]
Hi there,

It seems there is a bug when using one options value shared between two graphs. In that case, the graph is completely ignored. Here is an example:

no shared options:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/12100722/214306466-dfc307f8-8268-4527-b9b4-f3e39b7df793.png">

sharing options:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/12100722/214306671-32d36100-ca80-4a4b-8b66-af5dcd5e1ba1.png">

**Comment by joadan** [comment]
Hello,

This is by design, each chart needs it's own chart option object.

**Comment by sweco-bepema** [comment]
oh, alright then. Hope this issue helps someone at least.
