### ISSUE TITLE
Multiple series – Group rows

### ISSUE THREAD

**Issue by vadimffe** [apexcharts/Blazor-ApexCharts#199]
Is there a possibility to build this kind of charts with Blazor ApexCharts? 
https://apexcharts.com/javascript-chart-demos/timeline-charts/multiple-series-group-rows/

Also is there a possibility to show annotations? Like today date? 
https://github.com/apexcharts/apexcharts.js/issues/3511#event-8327696736

**Comment by joadan** [comment]
Hello,

Have you checked samples:

https://apexcharts.github.io/Blazor-ApexCharts/features/axis#xaxis%20groups
https://apexcharts.github.io/Blazor-ApexCharts/features/annotations
