### ISSUE TITLE
[Bug] Stacked Bar Charts - Unable to reduce width of the bars

### ISSUE THREAD

**Issue by Daeymon** [apexcharts/Blazor-ApexCharts#200]
I've got a rather length horizontal stacked bar chart and I would like to reduce the width of the bars by half. But the ColumnWidth property for the PlotOptionsBar does not seem to do anything.

**Comment by joadan** [comment]
Hello,

Not 100% sure what you are trying to accomplish.
But looking at the apexchart docs indicate that BarHeight could be used.

_barHeight: String
In horizontal bar charts, barHeight is the percentage of the available height in the grid-rect.
Accepts ‘0%’ to ‘100%’_
