### ISSUE TITLE
Export option CSV is missing

### ISSUE THREAD

**Issue by hjrb** [apexcharts/Blazor-ApexCharts#201]
Hello,

thank you for this great library, 
I tried to add the Exporter option for CSV using the demo code shown at https://apexcharts.github.io/Blazor-ApexCharts/features/export
But it doesn't appear. The only difference is that i am not using YAggregate but YValue instead.
How can I get the CSV Export work?

**Comment by joadan** [comment]
Hello,

What do you mean by it doesn't appear? Is the toolbar not vivsible or?
Easiest for me to help if you provide a minium repo that shows the problem.
