### ISSUE TITLE
Initialization on OnAfterRenderAsync doesn't work

### ISSUE THREAD

**Issue by eduard-tapkey** [apexcharts/Blazor-ApexCharts#203]
Hi,

I'm trying to initialize the pie chart on the first render of the document. 
The code below will not draw anything. If I remove the "firstRender" check, it will be redrawn over and over again.
I tried to put different if clauses in the method itself, but I believe there must be a simple way how to async load the elements on the first render and keep it that way.
With non-async method this works just fine.
Is this behaviour expected?

```
<ApexChart TItem="ElementModel" @ref="_chart">
    <ApexPointSeries TItem="ElementModel"
         Items="items"
         SeriesType="SeriesType.Pie"
         XValue="@(e => e.Description)"
         YAggregate="@(e => e.Sum(e => e.Amount))"
         OrderByDescending="e=>e.Y" />
</ApexChart>

@code {
 private List<ElementModel> items = new List<ElementModel>();

 protected async override Task OnAfterRenderAsync(bool firstRender)
 {
        if (firstRender)
        {
            await UpdateElements();
        }
 }

 private async Task UpdateElements()
 {
      
       var elements= await Client.GetElements();
       var elements1= new ElementModel() { Description = "Elements1",  Amount = 2 };
       var elements2= new ElementModel() { Description = "Elements2",  Amount = 3 };

        items = new List<ElementModel>() { elements1, elements2};

        //Two UpdateSeries seems to be necessary
        await _chart.UpdateSeriesAsync(true);
        await _chart.UpdateSeriesAsync(true);

        this.StateHasChanged();
    }
}
```

**Comment by joadan** [comment]
Hello,

Is there a special reason why you override the OnAfterRenderAsync?

**Comment by eduard-tapkey** [comment]
Hi @joadan ,
thank you for your answer.
Correct me if I'm wrong, but if I want to load elements on the initialization of the component I need to do it either with overriding OnInitializedAsync or OnAfterRenderAsync .
To have _chart accessible and rendered I do it in OnAfterRenderAsync (and only after first render). 
I will be happy to hear suggestion how to do it better and where to call UpdateElements in this case.
The goals is that whenever this component is used, the elements are loaded from DB and drawn.

**Comment by joadan** [comment]
Have you check the sample, https://apexcharts.github.io/Blazor-ApexCharts/features/chart-data

This gives you two examples of loading data async.

**Comment by eduard-tapkey** [comment]
Oh thank you @joadan 
I had it this way as the first draft, but what I made different now was to set "items" null at the beginning and not an empty list. After this, it started to work.
