### ISSUE TITLE
Missing xAxisLabelClick event

### ISSUE THREAD

**Issue by MarcelStassen** [apexcharts/Blazor-ApexCharts#204]
I'm missing the xAxisLabelClick event 

https://apexcharts.com/docs/options/chart/events/#xAxisLabelClick

**Comment by joadan** [comment]
I'm on it!

**Comment by joadan** [comment]
sample here https://apexcharts.github.io/Blazor-ApexCharts/events/xaxis-label-click

Please note not yet released

**Comment by joadan** [comment]
Fixed in v0.9.18-beta
