### ISSUE TITLE
Legend Formatter?

### ISSUE THREAD

**Issue by mbanks9** [apexcharts/Blazor-ApexCharts#210]
I'm trying to format the legend on my Donut chart to include some extra data. I see that the source apexcharts docs show that there is a formatter for the legend: 
![image](https://user-images.githubusercontent.com/25254388/224113722-d0654126-7804-4412-b1ac-1a5727922d6c.png)

I may have missed it, but don't see an option for this in the wrapper. Any clue on how to do this?

**Comment by joadan** [comment]
Hello,

The formatter is missing, I have added it and it will be available in the next release

**Comment by joadan** [comment]
fivex in [Release v0.9.19-beta](https://github.com/apexcharts/Blazor-ApexCharts/releases/tag/v0.9.19-beta)
