### ISSUE TITLE
Donut : how to count Element in tooltip 

### ISSUE THREAD

**Issue by MAYSACOLS** [apexcharts/Blazor-ApexCharts#211]
Hi everybody.

I have a list of data,  with several line for a same product with a different weight.
I have a chart with some option.
how to change the formatter function to have not the sum of product, but the number of lines 'sumed' so the number of line with the same produc.
 
`<ApexChart TItem="Balle"
Title="Balles Créées sur la période"
                           Options=optionsBallesCreate
                           @ref=chartBallesCreated>
                        <ApexPointSeries TItem="Balle"
                                     ShowDataLabels
                                     Items="GetBallesCreate()"
                                     SeriesType="SeriesType.Donut"
                                     PointColor="@(e => e.Materiaux.HexaColor)"
                                      XValue="@(e => e.Materiaux.Name)"
                                     YAggregate="@(e => e.Sum(e => (decimal)e.Poids))"
                                     OrderByDescending="e=>e.Y" />
                    </ApexChart>`

`    private ApexChartOptions<Balle> optionsBallesCreate = new ApexChartOptions<Balle>();`

`optionsBallesCreate = new ApexChartOptions<Balle>
                            {
                                Chart = new Chart
                                {
                                    Height = "350px"
                                },
                                Legend = new Legend
                                {
                                    Show = true
                                },
                                Theme = new Theme
                                {
                                    Mode = Mode.Light,
                                    Palette = PaletteType.Palette3
                                },
                                Tooltip = new Tooltip
                                {
                                    Y = new TooltipY
                                    {
                                        Formatter = @"function(value, opts) {
                                     if (value === undefined) {return '';}
                                     return  Number(value).toLocaleString() + ' Kg';}"
                                    },
                                    X = new TooltipX
                                    {
                                        Formatter = @"function(value, opts) {
                                                if (value === undefined) {return '';}
                                                return  opts.w.globals.categoryLabels[value-1] + ':' + value}"
                                    }
                                },
                                DataLabels = new DataLabels
                                {
                                    Formatter = @"function(value, opts) {
                                      return  Math.round(Number(value)) + '%';}"
                                }
                            };`

thinks a lot for your help

**Comment by joadan** [comment]
Hello, Not sure I fully understand the question, but if you want more control over the tooltip use the Custom Tooltip, https://apexcharts.github.io/Blazor-ApexCharts/features/tooltip
