### ISSUE TITLE
ApexGauge cannot be updated

### ISSUE THREAD

**Issue by krugertech** [apexcharts/Blazor-ApexCharts#214]
Hi There. 

Can we extend ApexGauge to allow redrawing or updating the control?

**Other chart components can be updated by calling:**
1. UpdateOptionsAsync(false, false, false);
2. RenderAsync()

**Why would this be needed?**
I have a scenario where when I need to flip between dark and light themes, and requires me changing my ApexGauge's Chart-ForeColor to adapt to the theme.

**Comment by joadan** [comment]
Hello,

The Gauge chart is just a simplified version of a radial bar chart with one series.
If you use the radial bar you will get all features.
https://apexcharts.github.io/Blazor-ApexCharts/radialbar-charts

Thank you
