### ISSUE TITLE
Roadmap for 1.0 release?

### ISSUE THREAD

**Issue by runtimeware** [apexcharts/Blazor-ApexCharts#217]
Is there a specific plan/roadmap for a 1.0 release of this lib?  Would be great to see what the project is aiming for to understand how outsiders can contribute and get it over the pre-release fence.  Thanks!

**Comment by joadan** [comment]
Hello,

Currently there are no mayor things we need to finish in order to make an offical release.
One thing that has been holding us back is just the fact that we are not using the component in any of our profesional work.
I made the wrapper as a exercise to learn blazor javascript interop.

**Comment by gabephudson** [comment]
First of all, thanks for providing this excellent wrapper library! Certainly, makes working with ApexCharts in Blazor much easier and developer friendly!

If you are essentially feature complete (excluding changes to ApexCharts itself), please consider publishing a 1.x release version (and Nuget). Many organizations have policies prohibiting "beta" or prerelease software in production apps. Perhaps give it a release number that includes the ApexCharts version included. For example, 1.3.36?

**Comment by thirstyape** [comment]
Hi @joadan, 

Is there anything holding this back right now? I am currently working on a PR to update the `ApexChartOptions` class as I see you have updated the JavaScript Apex library.

I would be happy to help with anything else to get to 1.0 as well.

**Comment by joadan** [comment]
Hi @thirstyape 

The only thing for me right now is that we don't have a good way to handle the options that can be both a single value or a list.
I really would like to make something that would be easier to handle. Changes to this will most certainly be a breaking change.

**Comment by thirstyape** [comment]
Yes, that makes sense to hold back on 1.0 if there will be that large of a breaking change. 

What is the goal for multiple options, would this be to enable passing options for each series in a multi-series chart?

**Comment by gabephudson** [comment]
Totally understand Joadan, thanks for responding. Sounds like an opportunity for a 1.x and 2.x branch. ;) 

As they say, beggars can't be chooser though.  Very happy to have this wrapper library to work with and appreciate your work on this.

**Comment by joadan** [comment]
Let's use this issue to discuss the single/multi value challange. https://github.com/apexcharts/Blazor-ApexCharts/issues/278

Please note I really understand the need to move this to production. 
Lets just at least discuss if we should do something or not.
Thank you for your patience.

**Comment by thirstyape** [comment]
Some other considerations prior to 1.0 that come to mind. These are either not a big deal or some may not be possible.

* Moving properties such as `ApexChartOptions<TItem>.HasDataPointLeave` to a separate internal class. 
* Remove anything marked as `[Obsolete]`.
* Update classes such as `JSDataPointSelection` to be internal.
* Move methods marked with `[JSInvokable]` to an internal class. Not sure if this is even possible, mainly just so people are not trying to use these methods.

@joadan I will have time tomorrow to test any of these that you think are worthwhile.

**Comment by joadan** [comment]
@thirstyape, would be great if you could look into the above.

One concern regarding removal Obsolete: The options class was originally generated automatically from the typescript definition file. I have a concern that there could be options that are valid but missing in documentation . One example is  AnnotationsXAxis.BorderWidth that is present in the typescript definition and is a valid option but missing in the documentation.

We should probably double check with the typescript definition, before removal.

**Comment by thirstyape** [comment]
Sure, I will create 2 branches, one for updating resources to be internal, and another for removal of obsolete properties. 

Is this the [typescript definition](https://github.com/apexcharts/apexcharts.js/blob/main/types/apexcharts.d.ts) you are referring to? I can compare this to the c#. Also, I can test out anything marked as obsolete to see if providing a value does anything.

**Comment by thirstyape** [comment]
Added a PR for internal.

Opened a [branch for obsolete](https://github.com/thirstyape/Blazor-ApexCharts/tree/9-remove-obsolete-content). I am wondering if removing the `[Obsolete]` attribute from the remaining properties is the way to go as they all exist in the TS definition. Then add XML commenting such as **/// Undocumented**. May also be worth looking for other undocumented properties that exist in the TS.

**Comment by gabephudson** [comment]
Thank you thirstyape and joadan for the 1.0 release! Congratulations!

Just updated and only had to make one small tweak (array to List) and 1.0 seems to be working fine and otherwise compatible with my (admittedly small) set of charts.
