### ISSUE TITLE
Cannot show repeated values on XAxis

### ISSUE THREAD

**Issue by wilsonmaf** [apexcharts/Blazor-ApexCharts#219]
Charts do not draw all the repeated values on XAxis except the first one.

For example, a list called datas has common x=2023-04-13, and y with different values.

The chart only shows the first record.

We have to manually add "XAxisType="XAxisType.Numeric" to the ApexChart component.

Then, the chart will show the rest.

Reference: https://stackoverflow.com/questions/76002318/blazor-apexcharts-repeated-values-on-xaxis/76002877#76002877

**Comment by joadan** [comment]
Hello,

I'll try to look inte this, but right now I don't have much time.

Thank you regards Joakim

**Comment by joadan** [comment]
Hello,

I believe this is the behavior in ApexChart.js. 
Please check https://codepen.io/joadan-the-sasster/pen/RweLMyZ
