### ISSUE TITLE
Missing Formatter property for DonutLabelTotal class

### ISSUE THREAD

**Issue by Boscarato** [apexcharts/Blazor-ApexCharts#222]
Hello,

I noticed that the _Formatter_ property is missing from the DonutLabelTotal class, but it seems to be supported by ApexCharts.
![Formatter](https://user-images.githubusercontent.com/46596694/232702497-8d5346e6-5747-448f-b44a-84c0bad8532f.png)

Do you plan to include it?

Thank you for your wonderful work!

**Comment by joadan** [comment]
Hello,

I'll try to fix this asap.

Thank you!

**Comment by joadan** [comment]
https://apexcharts.github.io/Blazor-ApexCharts/donut-charts#total

please note not yet released.

**Comment by joadan** [comment]
Fixed in  v0.9.21-beta
