### ISSUE TITLE
When RenderAsync and ResetSeriesAsync, chart loads data from "Items=" only after it is updated

### ISSUE THREAD

**Issue by fae909** [apexcharts/Blazor-ApexCharts#228]
Hi!

I found a bug when I tried to refresh chart without page refresh.

When RenderAsync and ResetSeriesAsync is used, chart load data from "Items=" only after its is updated and it is rendered with previous data.
It results chart is always behind one state compared to variable.

I tried these:
chart.RenderAsync();
chart.ResetSeriesAsync(true, true);

Code:

                            <ApexChart @ref=chart TItem="voltageData"
                                   Title="Voltage today"
                                   Options="@chartoptionsToday">

                                <ApexPointSeries TItem="voltageData"
                                             Items="teszt"
                                             Name="Votage"
                                             SeriesType="SeriesType.Line"
                                             XValue="@(e => e.time)"
                                             YAggregate="@(e => e.Sum(e => e.value))" />
                            </ApexChart>

   `record voltageData(string time, decimal value);`

Thank you in advance!

**Comment by joadan** [comment]
Hello,

Please try:
`await Task.Yield(); `
`await chart.RenderAsync();`

**Comment by fae909** [comment]
Hi,

You helped me a lot. 
Thank you very much!
