### ISSUE TITLE
Missing beforeZoom, beforeResetZoom events

### ISSUE THREAD

**Issue by iz-maersk** [apexcharts/Blazor-ApexCharts#229]
Hi! As was mentioned in previous issues, not all events were presented here. Could you please take a look into it, to have the ability to use these events for example to set the initial zoom (https://codepen.io/apexcharts/pen/BaKXaQB?editors=0010)? Thanks a lot!

**Comment by iz-maersk** [comment]
https://github.com/apexcharts/apexcharts.js/issues/1138

**Comment by joadan** [comment]
I will start working on this now

**Comment by thirstyape** [comment]
Added in #290, PR sent in

**Comment by joadan** [comment]
@thirstyape, This will only work in WASM and I don't see how we can support this in blazor server, or what do you think?
Regards Joakim

**Comment by thirstyape** [comment]
Ok, I can try to do some more testing a bit later. I had not thought about that difference and happened to be doing my tests in WASM.

Might need to add some more documentation to indicate that.

**Comment by joadan** [comment]
The challenge here is we need to use invokeMethodAsync in order to support both WASM and server. 
However here we are in syncronous javascript function and then it's not straight forward to wait for a result from an async method.

Same problem here: https://apexcharts.github.io/Blazor-ApexCharts/features/formatters#use%20dotnet

**Comment by joadan** [comment]
I'll add some documentation and a guard for now and then we can revisit.

**Comment by thirstyape** [comment]
Good to know it is a sync/async issue, I had been looking at the JS a little to see if async would be possible in certain areas.

**Comment by joadan** [comment]
Fixed in v1.1.0
