### ISSUE TITLE
RangeBar Overlap Issue

### ISSUE THREAD

**Issue by jbartlettii** [apexcharts/Blazor-ApexCharts#230]
#35 Added the support for grouped rangeBars however the overlap implementation seems to have a different behavior from the js library. For example if overlapping is enabled then you end up with something like 1112122232333 even though they are part of separate groups, if overlapping is disabled then you end up with a new row for every entry even if they were not going to overlap.

11111
           2222
                  33333

This means that overtime and with larger datasets you end up with n+1 escalating number of rows meaning tons of empty unused space. This does not seem to be the same behavior as the js library where you can end up with something like this where the space gets reused.

11111    222222
    3333333

[Implemented in the js library here with examples ](https://github.com/apexcharts/apexcharts.js/issues/1153)
Expected Behavior with Overlap flag disabled:
![image](https://github.com/apexcharts/Blazor-ApexCharts/assets/27874357/2a366253-a637-424b-ae54-fc6cbad71b78)

Current Behavior with flag off:
![image](https://github.com/apexcharts/Blazor-ApexCharts/assets/27874357/7469de7a-fd5e-4087-80ca-639494b52d80)

Because of this behavior the columns also end up shrinking with each new item because it adds an additional row for usage when it might be able to reuse space from a timeline that ended previously.

**Comment by joadan** [comment]
Hello,

Have you checked the sample, https://apexcharts.github.io/Blazor-ApexCharts/rangebar-charts#grouped
This should be the correct grouped behavior, right?
Sorry If I'm missing something obvious here.

**Comment by jbartlettii** [comment]
Not a problem, the sample looks fine and should be the correct behavior. The problems seem to begin when disabling overlap and enabling the groupedRows. So the following:

Horizontal = true,
RangeBarGroupRows = true,
RangeBarOverlap = false,

So the sample seems to have the correct behavior, but if we have multiple overlapping flags the chart seems to blow up. The sample only has:

Horizontal = true,
RangeBarGroupRows = true,

From my example above:
![image](https://github.com/apexcharts/Blazor-ApexCharts/assets/27874357/c2e56346-1757-4ed4-9b35-f007ea6ccc9e)

This image only has
Horizontal = true,
RangeBarOverlap = false,

Behavior is as expected each entry is split to another line, but lots of dead space, if I then add the flag to group the rows and switch to:

Horizontal = true,
RangeBarGroupRows = true,
RangeBarOverlap = false,

![image](https://github.com/apexcharts/Blazor-ApexCharts/assets/27874357/eca8ebe0-e2ab-4bc1-aab7-b54956f03576)

Explosion.

I would like to just get the graph from the first example, with the rows grouped as the JSLibrary or as the sample, but spliting instead of overlapping. Let me know if this helped or made more sense, otherwise I can definitely try to provide a minimal reproduction if that would help?

**Comment by joadan** [comment]
Hello,

Not sure I fully understand, is this possible in Apexchart.js? If not you need to create an issue in that repo.
If it is possible it would be great if  you could provide me with a codepen showing what you want. 

I'm not aware of any special thing the wrapper is doing here so if it works in js we should get it to work with the wrapper.
Thank you

**Comment by jbartlettii** [comment]
Not a problem, codepen for the js library is below: 

(https://codepen.io/jbartlettii/pen/NWOeevO)

Feel free to let me know if you would like me to format this differently. But basically, the top two groups are the best example, in the js library i'm seeing splitting instead of overlapping due to the flag but I am still getting the bars that do not overlap to have the same row so that the graph is not continuously expanding to a height of n. I haven't looked through the wrapper which I can definitely do if you would like but could it actually have something to do with how the data is passed to the js library rather than the flag implementation? It also could just be an error on my end if you are able to get this same example out.

**Comment by joadan** [comment]
Something like this https://apexcharts.github.io/Blazor-ApexCharts/rangebar-charts#overlap ?

**Comment by jbartlettii** [comment]
So, if for example that dataset from the below example on grouping has the flag turned on, I would expect only the integration group to have two rows, while all the other rows stay with only one row. So, the example above is totally correct about the splitting behavior, but I seem to notice the issue where the timelines are not split, the graph still grows by adding new rows when it shouldn't need to. Does that make sense? The splitting occurs when it should, when there would be overlap, but when overlap is not necessary, I was noticing that the graph was still adding new rows. 
![image](https://github.com/apexcharts/Blazor-ApexCharts/assets/27874357/67a6b5a7-7820-42ab-b6af-943f7b63c695)

So from the example above:
![image](https://github.com/apexcharts/Blazor-ApexCharts/assets/27874357/008e1021-c407-4891-a3f3-a8546255a1f4)
I would expect the pairs of Utility Usage, Economic Recovery, and GHG Inventory, WeSpire to be in the same row since there is no overlap that needs to be split out.

**Comment by jbartlettii** [comment]
Hmm never mind issue must be on my end, I ended up editing your example to try to demo what I was looking for and it seemed to work, so must be something to do with how I'm splitting my lists.

![image](https://github.com/apexcharts/Blazor-ApexCharts/assets/27874357/7c57421c-00a9-4073-8737-e0e61d2c4a8d)

Not my call but I would still change the activities to the below:

        activities.Add(new Activity { Person = "Bob", Name = "Code", Start = date.AddDays(-30), End = date.AddDays(-10) });
        activities.Add(new Activity { Person = "Bob", Name = "Code", Start = date.AddDays(-5), End = date.AddDays(5) });
        activities.Add(new Activity { Person = "Bob", Name = "Validate", Start = date.AddDays(-15), End = date });
        activities.Add(new Activity { Person = "Bob", Name = "Validate", Start = date.AddDays(-4), End = date.AddDays(5) });

        activities.Add(new Activity { Person = "Peter", Name = "Code", Start = date.AddDays(-35), End = date.AddDays(-6) });
        activities.Add(new Activity { Person = "Peter", Name = "Validate", Start = date.AddDays(-20), End = date.AddDays(-5) });

That way you can see the splitting behavior only occurs when needed.

I'll go ahead and close this out though since it doesn't seem to be a library issue at this point. Thanks so much for looking into it though!
