### ISSUE TITLE
Strange behavior if the plot is initialized empty

### ISSUE THREAD

**Issue by RDUser-dev** [apexcharts/Blazor-ApexCharts#231]
My application suffers from some problems of slow loading of graphs with many points.

I need to handle the possibility that the plot contains no Series.
Since the library doesn't seem to be able to handle this scenario, I decided skip the Blazor-AperCharts component render via a `@if`

Going through the documentation sample demo, I was able to replicate the behavior on the [performance](https://apexcharts.github.io/Blazor-ApexCharts/features/performance) page in server render mode.
In particular, I added the value 0 to the selection dropdown with the aim of simulating the absence of data to draw in the plot.
In doing so I noticed that:
- if the page is initially loaded with pointsToLoad pre-initialized to a value other than 0, the selection in the dropdown update the plot  very fast
- if instead the page is loaded starting from the situation in which pointsToLoad is 0, changing the selection on the dropdown takes a long time to update.

The situation in my application is more complex but the problem seems to be the same highlighted in this simple example.
Unfortunately I can't understand why the first case is fast and the second is slow. 
Can anyone give me some help?

I am attaching the change code to the original page [docs/BlazorApexCharts.Docs/Components/Features/Performance/Basic.razor](https://github.com/apexcharts/Blazor-ApexCharts/blob/master/docs/BlazorApexCharts.Docs/Components/Features/Performance/Basic.razor) :
``` C#
@using System.Diagnostics
@using System.Text.Json

<ItemSelect Label="Datapoints" Items=points @bind-SelectedValue=pointsToLoad Changed=LoadData />
@if (pointsToLoad != 0)
{
    <ApexChart TItem="TimeSeries"
           Title="Value"
           Height="150"
           XAxisType="XAxisType.Datetime"
           @ref=chart>

        <ApexPointSeries TItem="TimeSeries"
                     Items="timeSeries.Take(pointsToLoad)"
                     Name="Value"
                     SeriesType="SeriesType.Line"
                     XValue="@(e => e.Date.ToUnixTimeMilliseconds())"
                     YValue="@( e=> e.Value)"
                     Stroke="@(new SeriesStroke { Width = 2, Color="#1F15E5"})" />
    </ApexChart>
}

@if (isLoading)
{
    <h3>Loading<span class="animated-dots"></span></h3>
}
else
{
    <h3>@message</h3>
}

@code {
    private ApexChart<TimeSeries> chart;
    private List<int> points = new List<int> { 0, 100, 1000, 5000, 10000, 15000, 20000 };
    //private int pointsToLoad = 2;// <---------- FAST ISSUE EXAMPLE
    private int pointsToLoad = 0;// <---------- SLOW ISSUE EXAMPLE
    private List<TimeSeries> timeSeries = new TimeSeriesGenerator(25000).TimeSeries;
    private string message;
    private List<DataPoint<TimeSeries>> data;

    private bool isLoading;

    protected override void OnInitialized()
    {
        PopulateData();
    }

    private async Task LoadData()
    {
        var sw = new Stopwatch();
        sw.Start();
        isLoading = true;

        await Task.Delay(1);

        PopulateData();
        message = $"{pointsToLoad} Points: Populate Data {sw.ElapsedMilliseconds.ToString("N0")}ms, ";
        sw.Restart();
        await chart.UpdateSeriesAsync(false);
        sw.Stop();

        message += $"Update Chart {sw.ElapsedMilliseconds.ToString("N0")}ms";
        isLoading = false;
    }

    private void PopulateData()
    {

        data = timeSeries.Take(pointsToLoad).Select(e => new DataPoint<TimeSeries>
            {
                X = e.Date,
                Y = e.Value,
                Items = new List<TimeSeries> { e }
            }).ToList();
    }
}
```

**Comment by joadan** [comment]
Hello,

I updated the performance sample with an 0 points option, but I can't see any performance issues.
Please note that it is possible to have 0 points.
Normally when you have performance issues it is just to many svg objects. 
It's easy to forget axis labels, tick marks etc.

**Comment by joadan** [comment]
Hello,

I have updated the sample again. I can't see any slowness.
