### ISSUE TITLE
ApexRangeAreaSeries not recognized as a markup element in razor file, although ApexPointSeries recognized just fine.

### ISSUE THREAD

**Issue by idimou** [apexcharts/Blazor-ApexCharts#234]
After installing Blazor-ApexCharts in a brand new Blazor WASM project, on trying the sample code from https://apexcharts.github.io/Blazor-ApexCharts/rangearea-charts 
the ApexRangeAreaSeries not recognized as a markup element in razor file, although ApexPointSeries recognized just fine rights below it as shown in the sample.
Any ideas?

**Comment by joadan** [comment]
Hello,

Sorry the latest version is not released. Please give me an hour and I'll fix it.

**Comment by joadan** [comment]
I'm sorry but we have an nuget issue, it will take a bit longer to get the new release out.

**Comment by joadan** [comment]
v0.9.21-beta

**Comment by idimou** [comment]
Solved. That was blazing fast. 
Respect.
