### ISSUE TITLE
When changing the number of series of a chart this is not reflected when using RenderAsync()

### ISSUE THREAD

**Issue by hjrb** [apexcharts/Blazor-ApexCharts#235]
I use a chart with a dynamic number of series depending on a multi-selection select.
I create the series in a for loop in the Razor code.
When i change the selection and call 
await chartServiceUsageHistory.RenderAsync(); 
the change in the number of series is not drawn.
Only when I change the focus to another tab on the page and go back the change is drawn correctly.

**Comment by hjrb** [comment]
That does not work for me.
This does work: Task.Run(() => chart.RenderAsync().RunSynchronously());
Don't know if this is a safe way to do it.
I assume the issue is that calling RenderAsync within an event handler does not take effect as the changes in the data have not been reflected in the Blazor engine and hence the rendering result is using the old data. You need to exit the event handling, allow the Blazor engine to process the data changes. Then calling RenderAsync  should not even be required. The Blazor engine should trigger it automatically as it detects that the state has changed.

**Comment by hjrb** [comment]
P.s. THANK YOU for this great library!

**Comment by joadan** [comment]
Thank you,

I agree that the current method is not perfect, however there are more consideration to take into account. 
But if you feel that you have a better way you are more then welcome to create a PR.

**Comment by hjrb** [comment]
For me, the issue is resolved.
