### ISSUE TITLE
Add support for more chart types

### ISSUE THREAD

**Issue by joadan** [apexcharts/Blazor-ApexCharts#24]
Currently we don't support all chart types apex chart supports

**Comment by rf-0** [comment]
Hi, i cant find a roadmap under Git Projects or a Discord under main page, so would it be OK to request a chart here? Apologies if not.

My request would be support/addition for Candlestick charts. Thank you and love the work.

**Comment by joadan** [comment]
Hello,

We have a [branch ](https://github.com/apexcharts/Blazor-ApexCharts/tree/candle-stick) with support for all chart types that Apex charts is supporting. 
Not to much work left, a couple of breaking changes but it should be manageable.
All charts is working, left to do is to clean up the api, and some fixe issues with mixed charts.

I will try to find some time this week(end) to finalize it.

Thank you

**Comment by joadan** [comment]
All chart types is now supported in version 0.6.0-alpha.

Sample for CandleStick is [here](https://apexcharts.github.io/Blazor-ApexCharts/candlestick-charts)

Please note the breaking changes.

**Comment by rf-0** [comment]
Brilliant, thank you.

**Comment by joadan** [comment]
Clean up
