### ISSUE TITLE
AddPointAnnotationAsync when plotbarchart option horizontal = true

### ISSUE THREAD

**Issue by PatTheLad** [apexcharts/Blazor-ApexCharts#246]
Im trying to add annotationpoints to my chart.
The problem is, I cant set a string for my y axis.
`                    var pointAnnotation = new AnnotationsPoint
                        {
                            Y = tmpString, //string cant be converted into double
                            X = DateTime.Now.ToUnixTimeMilliseconds(),
                            Label = new ApexCharts.Label
                            {
                                Text = tmpString
                            }
                        };
                    chart?.AddPointAnnotationAsync(pointAnnotation, true);`
My chart options look like this -->
`options = new ApexChartOptions<MaschinenTimeStamp> //Settings for our chart
        {
            PlotOptions = new PlotOptions
            {
                Bar = new PlotOptionsBar
                {
                    Horizontal = true,  //Horizontal Chart option
                    RangeBarGroupRows = true,   //Group data
                }
            }
        };
        options.Legend = new ApexCharts.Legend { Show = false };    //Legend disabled because it's not needed 
        options.Chart.Height = "100%";`

**Comment by joadan** [comment]
Hello,

Horizontal = true will only flip the axis visually. 
I belive your tmpString should be on the X-Axis.
