### ISSUE TITLE
No Grouped Stacked Bars ?

### ISSUE THREAD

**Issue by IMBertDS** [apexcharts/Blazor-ApexCharts#247]
The JS version of apexcharts supports grouping stacks.
https://apexcharts.com/javascript-chart-demos/bar-charts/grouped-stacked-bars/

Is there any way of doing this with Blazor-ApexCharts ?

**Comment by joadan** [comment]
Hello,

Currently it's not possible because we are on an older Apexchart.js version. The plan is to upgrade once the Histogram issue is cleared out.

more info at https://github.com/apexcharts/apexcharts.js/issues/3807

**Comment by joadan** [comment]
I created a branch where this is supported, https://github.com/apexcharts/Blazor-ApexCharts/tree/grouped-stacked-bars

**Comment by IMBertDS** [comment]
Thanks !

**Comment by joadan** [comment]
Fixed in v0.9.22-beta

**Comment by obilge-cg** [comment]
> Fixed in v0.9.22-beta

Tried it today and its acting strange for me. the z-index of the series-2 is over series-1.
I can not hover the series-1, when you zoom in/out you see how series-2 is over 1.
