### ISSUE TITLE
Nonlinear gradient in mixed series (range series)

### ISSUE THREAD

**Issue by iz-maersk** [apexcharts/Blazor-ApexCharts#249]
I'm curious is it possible somehow to display a gradient not like an increased area, but from bottom to middle? from middle to top. Even better if the gradient will limit to another line that is approximately in the middle of the range series.
the desired gradient
![61c98f09-e47c-4a9b-9e53-deeffda68583](https://github.com/apexcharts/Blazor-ApexCharts/assets/125553125/50384df6-8b00-4cb2-b9dd-bb2b04a82dce)

here we have a range series with gradient and a line series(that also is represented as a range series, as line + range series had an error for some reason). so how to make the gradient here to be like in the image above (if that is possible)?
![image](https://github.com/apexcharts/Blazor-ApexCharts/assets/125553125/a1f108de-f998-4cf4-8b43-09a110f70c35)

**Comment by joadan** [comment]
Hello,

Please ask in the Apexchart repo, in here we are focused on the wrapper.
Thank you,
