### ISSUE TITLE
Incorrect Datetimes on X-Axis On Zoom/Scroll

### ISSUE THREAD

**Issue by DS-Drax** [apexcharts/Blazor-ApexCharts#254]
I have a line chart which uses DateTime as the X Axis and I've noticed an issue at a particular zoom level. 

At first the datetimes will be as you expect:

![image](https://github.com/apexcharts/Blazor-ApexCharts/assets/138772449/d6b0258e-074d-4dc7-aeac-f7b83a8c9d34)

But when the chart is scrolled to having 23:00 as the first entry visible, the X axis will incorrectly skip 00:00 and go to 1:00. This means that all times from what should be midnight onwards are out by 1 hour and so the data points do not correspond to the X axis times:

![image](https://github.com/apexcharts/Blazor-ApexCharts/assets/138772449/c5a5179a-b3e0-42f3-8f47-9c35e393bbdc)

If you scroll to the right just a little then the the times appear to be correct:

![image](https://github.com/apexcharts/Blazor-ApexCharts/assets/138772449/c45fd5be-484b-40e1-b65e-8b4473cd49f1)

It might be worth mentioning that I have DatetimeUTC set to false in the Xaxis labels setup.

If I need to provide any extra information please let me know.

Thanks

**Comment by DS-Drax** [comment]
Hi,

Is anyone able to confirm whether this is a bug?

**Comment by joadan** [comment]
Hello,

Sorry for  late reply, but this is not an easy thing to answer. 

If you can provide a repo where this can be reproduced we can take a look, but if there is bug it's most likely in the javascript code. If you can make a codepen and reproduce it in javascript you can create the bug in Apexcharts.js repo.
