### ISSUE TITLE
Remove Data from Series not possible

### ISSUE THREAD

**Issue by MPapst** [apexcharts/Blazor-ApexCharts#255]
Is it possible to remove data from a series without removing / rerendering the whole chart - like it is for appending data?

If it is possible and there is a way to do that on JS Level - let me know, I am willingly to contribute with a PR.

**Comment by joadan** [comment]
Hello 
Please check UpdateSeries https://apexcharts.github.io/Blazor-ApexCharts/methods/update-series

**Comment by MPapst** [comment]
That works like a charm - thanks a lot!
