### ISSUE TITLE
OrderByDescending

### ISSUE THREAD

**Issue by mdhampton** [apexcharts/Blazor-ApexCharts#262]
Not sure if I'm doing it wrong, or bug...

        <ApexPointSeries TItem="AccountsReceivable"
                            Items="AgingReport"
                            Name="AgingReport"
                            XValue="@(d=>d.BillingDate)"
                            YValue="@(d=>d.Dollars)"
                            OrderByDescending="@(e=>e.X)"
                            SeriesType="SeriesType.Line" />

So, BillingDate is a date time, and I would expect that the X axis would be oldest to youngest, but it shows as if the X axis is sorted ascending (or as it normally displays)

**Comment by joadan** [comment]
Hello, 

Sorry for  a late reply, It looks like Apexcharts.js always sort XAxis of type numeric or DateTime ascending.
