### ISSUE TITLE
'@ref=chart' is null

### ISSUE THREAD

**Issue by byrialsen** [apexcharts/Blazor-ApexCharts#267]
Hi.

My problem is that I don't understand when I can rely on the ```@ref=chart```. (Maybe the question here is just standard razor stuff)

If I override ```OnInitializedAsync()``` and does like this "pseudo-code":

```
await LoadDataAsync();
await chart.UpdateSeriesAsync(true);
```

Then chart reference is NULL and an exception is raised ofcourse.

If I add an extra delay like this:

```
await LoadDataAsync();
await Task.Delay(2000);
await chart.UpdateSeriesAsync(true);
```

Then it works, but there must be a better way.

**Comment by DaleCam** [comment]
Please see my solution here: https://github.com/apexcharts/Blazor-ApexCharts/issues/269
I think it would also apply to what you are doing :)

**Comment by byrialsen** [comment]
I ended up with a solution like that. Thanks for replying. @DaleCam.
