### ISSUE TITLE
Display 2 different types of data series on the same graph

### ISSUE THREAD

**Issue by bedudley** [apexcharts/Blazor-ApexCharts#268]
I need to display data points with their standard deviations shaded behind, as shown here:
![image](https://github.com/apexcharts/Blazor-ApexCharts/assets/21960225/f5bbb699-0f6f-46cc-8b29-f0a85f30a820)

I tried displaying an `ApexBubbleSeries` and an `ApexRangeSeries` on the same chart but always get a NullReferenceException when they are hosted within the same `<ApexChart></>` field: 
 ```
<ApexChart Height="100" TItem="GraphDataPoint" Title="" Options="_options" @ref="_chart">
        <ChildContent>
            <ApexBubbleSeries TItem="GraphDataPoint"
                              Items="GraphData"
                              XValue="i => i.xAxis"
                              YAggregate="i => i.First().yAxis"
                              ZAggregate="_ => 1"/>
            <ApexRangeSeries TItem="GraphStandardDeviationRange"
                             Items="StandardDeviations"
                             YMinValue="range => range.Min"
                             YMaxValue="range => range.Max"
                             XValue="range => range.XValue" />
        </ChildContent>
    </ApexChart>

```
The series display fine when split into two different charts.

Is this the correct way to display data points with their standard deviations shaded? If so, how do I correct these errors?
Or is there a better way to go about this?

Thank you!

**Comment by joadan** [comment]
Hello,
Sorry but it's not possible to mix a range series, https://github.com/apexcharts/apexcharts.js/issues/1165

You should get an exception like:

`Error: System.AggregateException: One or more errors occurred. (Chart Type RangeBar can not be mixed)
 ---> System.Exception: Chart Type RangeBar can not be mixed`
