### ISSUE TITLE
Setting Theme.Mode in OnInitializedAsync() has Issues

### ISSUE THREAD

**Issue by DaleCam** [apexcharts/Blazor-ApexCharts#269]
Hi! First of all thank you so much for such a great library!

I recently came across this bug.
Setting Theme.Mode in OnInitialized() is fine.

However if we use async code in OnInitializedAsync(), the Theme doesn't get rendered to the output (as per debug=true output below) and remains in Light Mode:
```
    private readonly ApexChartOptions<DateDecimalChartPoint> _options = new ();
    protected override async Task OnInitializedAsync()
    {
        var darkMode = await Theme.GetMode === ThemeMode.Dark;

        _options.Theme = new Theme
        {
            Mode = darkMode ? Mode.Dark : Mode.Light;
        };
    }
```

![image](https://github.com/apexcharts/Blazor-ApexCharts/assets/4400216/90610e91-9878-4928-93ae-4a81f0b33b69)

**Comment by DaleCam** [comment]
Please note I was able to solve this by not rendering the chart until it was fully initialised. For example:

```
@if(ChartInitialised){
    <ApexChart TItem="DateDecimalChartPoint" Title="Chart Title" ... 
}
```
then in the code block:

```
    private bool ChartInitialised = false;
    private readonly ApexChartOptions<DateDecimalChartPoint> _options = new ();

    protected override async Task OnInitializedAsync()
    {
        var darkMode = await Theme.GetMode === ThemeMode.Dark;

        _options.Theme = new Theme
        {
            Mode = darkMode ? Mode.Dark : Mode.Light;
        };
        ChartInitialised = true;
    }
```

**Comment by joadan** [comment]
Hello,

Yes when the chart is rendered the first time you have not set the Dark theme and there for it is rendered with the default value. One solution is to do what you already discovered not render the chart until all is set.  Another option is to re-render the chart once you have the correct settings.
