### ISSUE TITLE
Please provide Treemap

### ISSUE THREAD

**Issue by oschakravarthi** [apexcharts/Blazor-ApexCharts#27]
Hi,

Any plans of providing Treemap?

Thank you

**Comment by joadan** [comment]
Hi,

Yes our ambition is to support all charttypes that Apexchart supports. 
I'll have a look at what it takes to add treemap.

Regards Joakim

**Comment by joadan** [comment]
Hi again,

I have added treemap support, check the sample [here](https://apexcharts.github.io/Blazor-ApexCharts/treemap-chart)
Please note that I have not published a new nuget yet.

**Comment by joadan** [comment]
released in v0.4.1-alpha

**Comment by oschakravarthi** [comment]
Super. Thanks a lot
