### ISSUE TITLE
Help with doc?

### ISSUE THREAD

**Issue by jbaumflek** [apexcharts/Blazor-ApexCharts#270]
Hello, I am trying to figure out how to use YAggregate to pick a point's data rather than aggregate, because we have a custom aggregating function.  Maybe I'm not getting something conceptually, will try to figure out, but love to know what the data structure of Order is for 

orders = SampleData.GetOrders();

**Comment by joadan** [comment]
Hello, 

The structure is here https://github.com/apexcharts/Blazor-ApexCharts/blob/master/docs/BlazorApexCharts.Docs/Data/Order.cs

Please let me know if you have any more questions
