### ISSUE TITLE
PointColor with mixed charts not working

### ISSUE THREAD

**Issue by wintermuteconsult** [apexcharts/Blazor-ApexCharts#271]
For some reason I cannot get PointColor to work when mixing two charts? Is this a bug or is there a workaround somehow? I'm on version 0.9.21-beta.

Code snippet below to reproduce issue.

`
<ApexChart @ref="accumulatedCostChart" TItem="CostItem" XAxisType="XAxisType.Category" Height="200" Options="chartOptions">
        <ApexPointSeries TItem="CostItem"
                         Items="CostData.GetAccumulatedCosts(LastYearCosts)"
                         Name="Accumulated Costs 2022"
                         SeriesType="SeriesType.Area"
                         XValue="@(e => e.date.Day)"
                         YValue="@(e => Convert.ToDecimal(e.cost))"
                         Color="#e7e7e7" />

    <ApexPointSeries TItem="CostItem"
                     Items="CostData.GetAccumulatedCosts(context.Items)"
                     Name="Accumulated Costs 2023"
                     SeriesType="SeriesType.Bar"
                     XValue="@(e => e.date.Day)"
                     YValue="@(e => Convert.ToDecimal(e.cost))"
                     Color="#13A10E"
                     PointColor="e => GetPointColor(e)" />
</ApexChart>

@code {

    ApexChartOptions<CostItem> chartOptions = new();
    ApexChart<CostItem> accumulatedCostChart;

    protected override void OnInitialized()
    {
        chartOptions.Chart.Toolbar = new Toolbar { Show = false };
        chartOptions.Yaxis = new List<YAxis> { new YAxis { DecimalsInFloat = 0 } };
        chartOptions.Legend = new Legend { Show=false };
        chartOptions.Stroke = new Stroke { Show = false };
    }

    private string GetPointColor(CostItem item)
    {
        return item.forecast ? "#87FF5F" : "#13A10E";
    }
}
`

**Comment by joadan** [comment]
Hi,

I have added a sample, https://apexcharts.github.io/Blazor-ApexCharts/mixed-charts#pointcolor

Regards Joakim
