### ISSUE TITLE
Chart with dynamic height

### ISSUE THREAD

**Issue by byrialsen** [apexcharts/Blazor-ApexCharts#274]
I have a Blazor page with a MudPaper (content part) that dynamically adjust when the size of the Windows changes. (both width and height)

I placed my ApexChart inside this content component and the chart scales to the width and then height is scaled using the ratio build into ApexChartJS [(https://apexcharts.com/docs/options/chart/height/)](https://apexcharts.com/docs/options/chart/height/)

I would really like to have the height set dynamically in respect to the available height of the content component. Does anyone has a working solution to such task. My best guess is that it should be some mechanism to get the height of the container in runtime and then set the height of the chart according to that. 
(I need this because my web app tries to look like a standard desktop app adjusting content to windows size)

Thanks in advance?

**Comment by thirstyape** [comment]
I have not tried, but does the `UpdateOptionsAsync` method work to adjust the height? If so, you could then create an event using JSInterop and bind to the [window resize](https://developer.mozilla.org/en-US/docs/Web/API/Window/resize_event). This could be achieved using a `[JsInvokable]` function in your c# and triggering the update options method when it is called.

**Comment by joadan** [comment]
Hello,

Update options can be used to set the height, sample here: https://apexcharts.github.io/Blazor-ApexCharts/features/chart-size

**Comment by thirstyape** [comment]
If you are looking for the available height on the screen you will likely need to use a JSInterop function for that.

Not sure what you are looking to use the information for, but `Chart.Height` accepts percentage values. Might even work with **vh** values.
