### ISSUE TITLE
JavaScript security update recommendation

### ISSUE THREAD

**Issue by thirstyape** [apexcharts/Blazor-ApexCharts#277]
Hi @joadan,

I have been working on another PR and noticed that there are a couple of uses of `eval()` in the JS for this project. Based on how they are implemented I do not think it is a big issue; however, as per the [Mozilla Documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval#never_use_eval!) I think that it could be improved by using either the indirect eval method or a `Function()`.

Changing to the indirect method should be quite easy. Just update from `eval("(" + value + ")")` to `eval?.("\"use strict\"; (" + value + ")")`.

**Comment by joadan** [comment]
Hi,

Is it possible for you to make a PR?
Thank you,

**Comment by thirstyape** [comment]
For sure. I will take care of that either later today or tomorrow.
