### ISSUE TITLE
Better way to handle options that can be both single value or list

### ISSUE THREAD

**Issue by joadan** [apexcharts/Blazor-ApexCharts#278]
It is very common in Apecxchart.js that options can be either a single value or a list. 
Currently we don't have a good/consistent way to handle it .

**Comment by thirstyape** [comment]
Can you provide an example? I believe I am following, but would like to make sure.

**Comment by thirstyape** [comment]
Ok, what about a mode enum within the ValueOrList class? Having 3 options: auto, single, or all. Then just set the default value to auto; and for anyone wanting to specifically have a single item array the value can be updated to single.

I think either something like that will be required or it could be built into the constructor. So if the single item constructor is used it enters single item mode and if the list constructor is used it enters array mode. Could also do both so it can be changed after initial setup as well.

**Comment by joadan** [comment]
Hmm maybe I making this more complicated then it has to be..

In Apexchart.js you either pass in one value that is global or you pass in an array of values for example for each series.
There is really no option (I think) to provide an array with only some values, like I only want this to affect series no 2 and 3.
And even if that is the case how should we represent it? It could be solved if the generic is nullable.

I'm thinking it's  best to go with your proposal:

> I think that the ValueOrList may be on the right track. I would likely change the internal structure to always store values within a List. Then, when the value is being serialized just check the count; if it is 1, return list.First(), otherwise all values.
Implementing IList would also enable simplified management of the object as it would bring methods such as .Add(), .Remove(), and .Clear() into the mix. This should also allow keeping the existing constructors for one or multiple, as well as allowing direct assignment from an existing list.

This would make it fairly simple and easy to understand and still cover most(all?)  use cases.

**Comment by joadan** [comment]
Here is an branch https://github.com/apexcharts/Blazor-ApexCharts/tree/value-or-list 
@thirstyape,  what you think?

**Comment by thirstyape** [comment]
Looks great!

Very minor change, I would use `.AddRange()` in the `public ValueOrList(IEnumerable<T> list)` constructor to avoid additional assignment.

**Comment by thirstyape** [comment]
Oh and I would also add the following as it will allow casting between `List<T>` and `ValueOrList<T>`.

```
public static implicit operator List<T>(ValueOrList<T> source)
{
    return new List<T>(source);
}

public static explicit operator ValueOrList<T>(List<T> source)
{
    return new ValueOrList<T>(source);
}
```

**Comment by thirstyape** [comment]
And the converter can be updated as follows:

```
public override void Write(Utf8JsonWriter writer, ValueOrList<T> value, JsonSerializerOptions options)
{
    if (value == null || value.Count == 0)
        JsonSerializer.Serialize(writer, null, options);
    else if (value.Count == 1)
        JsonSerializer.Serialize(writer, value[0], typeof(T), options);
    else
        JsonSerializer.Serialize(writer, (List<T>)value, typeof(IEnumerable<T>), options);
}
```

**Comment by joadan** [comment]
branch has been updated

**Comment by thirstyape** [comment]
Very nice!

Note that I updated the operators above; nothing major, just changed them to both be implicit and also have the one for casting to `List<T>` just return the value collection to avoid the additional assignment and boxing.

Let me know if you need help going through the JS docs to find more properties that use the single value / array pattern.

**Comment by joadan** [comment]
after some more consideration I have another proposal.

Why not just use a List(IList)  and decorate the property with an Json converter attribute.

Example FillGradient.OpacityTo

``` 
 /// <summary>
 /// End color's opacity
 /// </summary>
 [JsonConverter(typeof(ListOrValueConverter<double>))]
 public IList<double> OpacityTo { get; set; }
```

The Converter:

```
    internal class ListOrValueConverter<T> : JsonConverter<IList<T>>
    {
        public override IList<T> Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            throw new NotImplementedException();
        }

        public override void Write(Utf8JsonWriter writer, IList<T> value, JsonSerializerOptions options)
        {
            if (value == null || value.Count == 0)
            {
                JsonSerializer.Serialize(writer, null, options);
            }
            else if (value.Count == 1)
            {
                JsonSerializer.Serialize(writer, value[0], typeof(T), options);
            }
            else
            {
                JsonSerializer.Serialize(writer, value, options);
            }
        }
    }
```

I have updated the branch with this proposal as well

@thirstyape, what do you think?
My take is that this is as simple as we can do it.. breaking changes to a minimum.
Only downside is that it's not obvious to the user what is going on, but we should add documentation.

**Comment by thirstyape** [comment]
What about using and adding classes such as `public class Color`?

I think this will provide the best of both worlds with regards to documentation and avoiding breaking changes. I have done several tests and am really liking the results.

**Documentation**

Using specific classes will enable providing documentation for each use case such as color, opacity, etc. It will allow retaining the JS documentation for each property while adding usage details from the base class. For example, `Color` could state that it accepts values in hex or named color formats.

```
public class LegendLabels 
{
    /// <inheritdoc cref="Color"/>
    /// <summary>
    /// Custom text colors for legend labels. Accepts an array of colors where each index corresponds to the series index
    /// </summary>
    public Color Colors { get; set; }
}

/// <remarks>
/// Details on acceptable values. i.e. '#00FF00' or 'green'
/// </remarks>
public class Color : ValueOrList<string> 
{
}
```

Hovering over the `LegendLabels.Colors` property then displays the JS documentation followed by the remarks on `Color`.

**Avoid Breaking Changes**

Changing `ValueOrList<T>` to be abstract and then using specific implementations with implicit operators can effectively avoid breaking changes altogether. I changed `FillGradient.OpacityTo` to the Opacity class and it did not break the examples in the docs. This was after applying the changes below to `Opacity`.

```
// Changes to ValueOrList<T>
public abstract class ValueOrList<T> : IList<T> // Needed to remove one of the implicit operators here
{
    public ValueOrList(params T[] list)
    {
        if (list.Any())
        {
            values.AddRange(list);
        }
    }
}

// Add casting operators to implementations of ValueOrList<T>
public static implicit operator List<string>(Color source) => source.values;
public static implicit operator Color(List<string> source) => new(source);
public static implicit operator Color(string source) => new(source);

// Updated constructors to implementations of ValueOrList<T>
public Color(params string[] values) : base(values) { }
public Color(IEnumerable<string> list) : base(list) { }

// Working implementations
Colors = new Color()
Colors = new Color("red")
Colors = new Color("red", "blue", "Orange", "Green")
Colors = new Color(new[] { "red", "blue", "Orange", "Green" })
Colors = new Color(new List<string>() { "red", "blue", "Orange", "Green" })
Colors = "red"
Colors = new List<string>() { "red", "blue", "Orange", "Green" }
```

**Bonus**

This implicit operator structure could event extend to properties such as `Chart.Height` where multiple types are accepted. Creating a class with operators for string, int, and double would ensure that bad values can be rejected without breaking good values. You can even throw exceptions from within the operator; so if an invalid height was entered the user would receive details right away. For example:

```
// Sample class
public class Height 
{
    public static implicit operator Height (string height) 
    {
        if (!height.All(x => char.IsDigit(x) || x == '%')) // Did not check for 'px' in this example
            throw new ArgumentException("Height values must contain only digits or the percentage sign", nameof(height));

        return new(height);
    }
}

// Good Examples
Height = "75%"
Height = 400
Height = "400"
Height = new Height(400)

// Bad Example
Height = "400mm"
```

**Comment by thirstyape** [comment]
I should have time for a PR today if you like. Do you know which properties will be affected?

**Comment by joadan** [comment]
Sound great, 
I'm afraid I don't have a list of affected properties.

**Comment by thirstyape** [comment]
Ok, I have added [this branch](https://github.com/thirstyape/Blazor-ApexCharts/tree/10-update-options-to-support-multi-datatype-properties). Some notes:

* Moved enums to bottom of ApexChartOptions file
* Added new ValueOrList class
* Added implementations for ValueOrList
* Tooltip.Custom and LegendLabels.Colors need review

Still to do:

* Update documentation
* Consider adding something for multi-type single values such as Height or FontWeight

@joadan let me know how to continue and I should have time to wrap this up tomorrow.

**Comment by joadan** [comment]
This looks really good, 

I went through the types script definition and picked out the multi type properties.
This list includes all I could find but I don't think we should address all of them. For sure we should update the single/list properties.

[ApexMultiType.txt](https://github.com/apexcharts/Blazor-ApexCharts/files/12495503/ApexMultiType.txt) 

Thank you for all you work!

**Comment by thirstyape** [comment]
There is also `type ApexTooltip = { custom?: ((options: any) => any) | ((options: any) => any)[] }`.

**Comment by thirstyape** [comment]
I have added another commit, should just be documentation now. 

I agree that the single values with multiple data types do not need to be addressed; at least not in this issue. So far the best I can think of is having public private pairs of values. For example:

```
/// <summary>
/// Font-weight for the axis label
/// </summary>
public object FontWeight
{
    get
    {
        if (fontWeightString != null)
            return fontWeightString;

        return fontWeightDouble;
    }
    set
    {
        if (value == null)
        {
            fontWeightString = null;
            fontWeightDouble = null;
        }
        else if (value.GetType() == typeof(string))
        {
            fontWeightString = (string)value;
            fontWeightDouble = null;
        }
        else if (double.TryParse(value.ToString(), out double parsed))
        {
            fontWeightString = null; 
            fontWeightDouble = parsed;
        }
        else
        {
            throw new InvalidCastException();
        }
    }
}

private string fontWeightString;
private double? fontWeightDouble;
```

**Comment by thirstyape** [comment]
@joadan Sent in the PR.
