### ISSUE TITLE
Chart is exceeding page height

### ISSUE THREAD

**Issue by oschakravarthi** [apexcharts/Blazor-ApexCharts#28]
The chart is exceeding the client height (or the visible screen area). I want the chart to be 100% in width but height should not exceed the visible area. Please have a look at the screenshot.  

Please help me asap. I have a client demo :-(

![image](https://user-images.githubusercontent.com/29388049/135365350-3e5c305d-c1a8-4b89-90d7-a10e0240f732.png)

**Comment by joadan** [comment]
Hello,

I'm sorry but I no expert on apexcharts, please check the [Documentation Height](https://apexcharts.com/docs/options/chart/height/#) for guidence.

If you have questions about how the chart behaves it's probably better to ask them in the apex chart repo, or stackoverflow.

**Comment by joadan** [comment]
Clean up
