### ISSUE TITLE
More Than 2 Series With Multiple Y Axis

### ISSUE THREAD

**Issue by DS-Drax** [apexcharts/Blazor-ApexCharts#280]
Hi,

Is there a way to assign a series to a particular Y- Axis? E.g state an index or a name?

The sample in the docs only uses 2 series and so I know that works on indexing. But indexing generally appears to index based on the order of the series passed to the order of the Y Axis. The Apex Charts docs state that you can use the series name which I tried but doesn't appear to work.

What's the best approach to be explicit assigning a particular series to a particular Y Axis?

Thanks

**Comment by joadan** [comment]
Hello,

I have updated the sample to include 3 series with two axis, please see https://apexcharts.github.io/Blazor-ApexCharts/features/axis

**Comment by DS-Drax** [comment]
Hi Joadan,

Thanks for updating the docs. That confirms my thinking in that it's index based, i.e, the series order matches the Y Axis order in order to assign a series to a Y Axis. 

As a suggestion, I think it would be good if somehow this wrapper can make use of Apex Charts functionality to assign a series to a Y Axis based on a name as seen here in _3 series with 2 Scales_ [Apex Charts](https://apexcharts.com/docs/chart-types/multiple-yaxis-scales/#:~:text=By%20default%2C%20each%20index%20of%20Y-axis%20corresponds%20to,target%20by%20specifying%20yaxis.seriesName%20when%20building%20y-axes%20array.) assuming possible.
