### ISSUE TITLE
 await GetDataUriAsync(options) does not work

### ISSUE THREAD

**Issue by ElskePM** [apexcharts/Blazor-ApexCharts#282]
Hello,

In my project I am using the function GetDataUriAsync(), which worked fine first but suddenly it seems broken.
When called, it gets stuck in an infinite state of loading and it will nog complete the task. 

Does someone recognize this problem?

**Comment by joadan** [comment]
Have you checked this: https://github.com/apexcharts/Blazor-ApexCharts/issues/257

**Comment by ElskePM** [comment]
Yes, that solution didn't help...

**Comment by joadan** [comment]
Not sure what we can do to troubleshot this from our end.
Is it possible for you to provide a repo where we can reproduce the issue?

Regards Joakim
