### ISSUE TITLE
Please set some default values for width and height

### ISSUE THREAD

**Issue by oschakravarthi** [apexcharts/Blazor-ApexCharts#29]
Please set some default values for width and height

![image](https://user-images.githubusercontent.com/29388049/135373638-85f8a3b2-eb1f-41cb-81d3-b737c67c8012.png)

**Comment by joadan** [comment]
When null the default values in apexchart is used:

[Height](https://apexcharts.com/docs/options/chart/height/#) 'auto'
[Width](https://apexcharts.com/docs/options/chart/width/#) '100%'
