### ISSUE TITLE
how to set the width property to 100%?

### ISSUE THREAD

**Issue by EduardoMariano** [apexcharts/Blazor-ApexCharts#293]
Hi, is there a way to set the chart width to 100% of the parent (container) width?

I have tried to do:

**Width = "@("100%")"**

But it is not worked for me.

**Comment by joadan** [comment]
Hi,

I have added an sample, https://apexcharts.github.io/Blazor-ApexCharts/features/chart-size#Percentage

**Comment by EduardoMariano** [comment]
Perfect, it worked well for me, thanks for your help.
