### ISSUE TITLE
Annotations on same Axis drawing annotation label at wrong position.

### ISSUE THREAD

**Issue by HeathAndrew** [apexcharts/Blazor-ApexCharts#304]
Hi all,
I've been working on a graph that emulates an oscilloscope, i.e. with cursors that draw on the graph and can be manipulated. I'm pretty happy with the result but noticed some behavior that looks unintended.

When drawing the second annotation on an axis it will draw the annotation label(The little box that sits on the annotation)at the position of previously specified position. 
![EditThisONe](https://github.com/apexcharts/Blazor-ApexCharts/assets/84323875/acb25e7e-52da-4563-954a-a9135bbfc221)
please excuse the black areas.
This gif shows the issue, so when incrementing small amounts with the dial it looks fine because the position is only a small distance away from previous location. when selecting on the graph the annotation draws correctly at the right position but the Square box of the label is still drawn at the previous Position. the text of the label is drawn at the correct position. 

The order of events when a datapoint is selected are:
1. Data Point Selected from graph (either by selecting or by incrementing with dial) 
2. new annotation B with unique ID is created
3. annotation B is added to the chart using AddYAxisAnnotationAsync
4. annotation A is cleared with its unique ID using RemoveAnnotationAsync

I have tried the following order that works but makes it display of the annotation flicker which I'm trying to avoid:
1. Data point selected from the graph
2. annotation A is cleared with its unique ID using RemoveAnnotationAsync
3. annotation B is created with unique ID is created 
4. annotation B is added to the chart using addYAxisAnnotationAsync

If anyone can help, or if you need/want a minimal repo to i can try and get one to replicate the issue. 
Cheers!

**Comment by joadan** [comment]
Hello,

If you can provide a minimal repo I can take a look.

**Comment by HeathAndrew** [comment]
Will try and get one set up today!

**Comment by HeathAndrew** [comment]
Sorry had a busy week, Am still going to make a small repo

**Comment by HeathAndrew** [comment]
Okay, adapted one of my other repos to demonstrate the problem.
repo is here: https://github.com/HeathAndrew/BlazorChartMiniRepo

once launched just click load data and wait for annotations to draw, then select the "Amp" Cursor with the drop down.
then use the buttons to change the position, you should see the annotation line and text move but the little backing box is drawing at the previous position.

**Comment by joadan** [comment]
Hi, I ran the sample and was able to reproduce.
But I'm afraid that I'm not sure what the problem is. 

Just like you wrote it works if you change the order, remove first an then add.
That looked ok to me and I could not see any flickering.
