### ISSUE TITLE
Looping charts not update when page changed

### ISSUE THREAD

**Issue by syahiedkhalil** [apexcharts/Blazor-ApexCharts#306]
Hi, thank you for the hardwork for this chart wrapper. I hope you guys is in good condition.

I try to loop the chart for every chart in list. It worked like charm. However, the issue is, when i changed the page using pagination, the list of charts(numbers in list) is changing, but not the charts. If anyone has idea on how can i solved this issue, please, feel free to comment. Below is my code:

![image](https://github.com/apexcharts/Blazor-ApexCharts/assets/71052527/3d0c58e5-8d13-431f-ac68-836b5d79a516)
![image](https://github.com/apexcharts/Blazor-ApexCharts/assets/71052527/4bf787c4-77ba-4b1d-ae62-e2340c541303)
![image](https://github.com/apexcharts/Blazor-ApexCharts/assets/71052527/7f939dd9-2786-40ab-9593-527ccf31e303)
![image](https://github.com/apexcharts/Blazor-ApexCharts/assets/71052527/cbe454cd-5731-4caa-9e8a-5884bf776f4c)

**Comment by joadan** [comment]
Hello,

I belive the problem is taht you have the same @ref for all charts

**Comment by syahiedkhalil** [comment]
Hello @joadan , thank you for response,

how can i make the @ref for each chart? because chart update can only update once

**Comment by joadan** [comment]
> because chart update can only update once

Not sure I understand what do you mean.

**Comment by TIAcode** [comment]
I just had a similar situation. I "fixed" it with a button to show / hide the chart - after hiding and showing again the data in the chart got updated.

**Comment by joadan** [comment]
Clean up
