### ISSUE TITLE
Stacked Bar Chart datalabel is not visible when the bar's height is too small.

### ISSUE THREAD

**Issue by dineshjethoe** [apexcharts/Blazor-ApexCharts#308]
![image](https://github.com/apexcharts/Blazor-ApexCharts/assets/21182176/c3d176ec-5a1d-4f7b-b249-3f3a7c57160f)

**Comment by joadan** [comment]
Hello,

This is a question for apexcharts.js, here you can get some additional information, https://stackoverflow.com/questions/75741021/how-to-display-values-to-the-right-of-the-bars-that-are-not-have-enough-space-fo
