### ISSUE TITLE
Conditional coloring of bars

### ISSUE THREAD

**Issue by dineshjethoe** [apexcharts/Blazor-ApexCharts#309]
How to get this done in Blazor? The bar's color is based on the value. 
E.g.: https://codepen.io/apexcharts/pen/RwRNXzX

**Comment by joadan** [comment]
hello, please check https://apexcharts.github.io/Blazor-ApexCharts/bar-charts#point%20colors

**Comment by dineshjethoe** [comment]
> hello, please check https://apexcharts.github.io/Blazor-ApexCharts/bar-charts#point%20colors

This worked for me. Thank you. 
`Color="e=> GetColor(e)"`
