### ISSUE TITLE
Set Chart Height to 100%?

### ISSUE THREAD

**Issue by aliocamlibel** [apexcharts/Blazor-ApexCharts#31]
Hi, is there a way to set the chart height to 100% of the parents height? I am on version 0.2.4-Alpha as I am still using .NET Core 3.1.

I have tried to do:
`options.Chart.Height = 100%`

and set the component's height to:
`Height = "@("100%")"`

But neither worked for me.

**Comment by joadan** [comment]
Hi,

According to [https://github.com/apexcharts/apexcharts.js/issues/140](https://github.com/apexcharts/apexcharts.js/issues/140) it should be possible if the parent container has a set height.

**Comment by joadan** [comment]
Clean up
