### ISSUE TITLE
context.DataPoint.FillColor never set

### ISSUE THREAD

**Issue by itniels** [apexcharts/Blazor-ApexCharts#310]
## Information
Type: BUG
Blazor-ApexCharts v1.2.1
BlazorServer .NET 7.0

## Description
It seems when creating a custom tooltip using `<ApexPointTooltip>` then `@context.DataPoint.FillColor` is always empty, so there is no way to determine the color of the hovered item and color the popup accordingly.

I have tried with Theme palette and custom colors, the result is the same.

Thanks 🙂

**Comment by joadan** [comment]
Here is an sample: https://apexcharts.github.io/Blazor-ApexCharts/features/tooltip#point%20color

**Comment by itniels** [comment]
@joadan Thank you very much.
Ahh I see, it has to be manually set in your example.

There is no way to set it based on the hovered item color from the palette?

**Comment by joadan** [comment]
Hello,

I'm not aware of any way to get the color when specified in the theme palette.
