### ISSUE TITLE
Feature Request: include Js files in a more Blazor like way

### ISSUE THREAD

**Issue by wolfgangschneider** [apexcharts/Blazor-ApexCharts#317]
If its possible with your design it would be nice include the .js files in a more Blazor like style. In my opinion a component should be used in the most simple way:
 * Add Nuget Package
 * add using

 
 Blazor has a nice feature to load the JS files in the component itself:
  var module = await jsRuntime.InvokeAsync<JSObjectReference>("import", "./_content/MyComponents/exampleJsInterop.js");  
  await module.InvokeAsync<string>("showPrompt", message);

**Comment by joadan** [comment]
Hello,

Yes, I agree that would be great. 
If you feel up to it PR's are more then welcome.

**Comment by wolfgangschneider** [comment]
Hi

Unfortunately my JS skills are to less to understand the  js code.


I was able to load the blazor-apex-charts as module  ,  It  able to call  “await JSHandler.RenderChartAsync();”  that function also worhed well till “chart = new ApexCharts(container, options);”  this function goeas deep into the “apexcharts.js” filt , (it still is includes l with the html scriopt tag.  And throws an exception chart not defined.

Wolfgang

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by wolfgangschneider** [comment]
Hi - I made some changes but I am to stupid to Pusch the changes (please advice me)
Anyhow  here are the changes files

[Blazor-ApexCharts-changes.zip](https://github.com/apexcharts/Blazor-ApexCharts/files/13208716/Blazor-ApexCharts-changes.zip)


And of course remove bothscript Tags form _host.schtml and Indexhtml

**Comment by joadan** [comment]
#321

**Comment by joadan** [comment]
Thank you for the pull request! It's now merged.

**Comment by joadan** [comment]
I added window.ApexCharts = ApexCharts and it seems to be working

**Comment by joadan** [comment]
Fixed in v2.0.0
