### ISSUE TITLE
Docs (Wasm): RangeArea in Chart Gallery doesn't display properly

### ISSUE THREAD

**Issue by digitaldirk** [apexcharts/Blazor-ApexCharts#320]
Hi,

When on this page of the docs: [https://apexcharts.github.io/Blazor-ApexCharts/](https://apexcharts.github.io/Blazor-ApexCharts/), the RangeArea example at the bottom of the page does not display the chart property. I cloned the repo and ran both the Server and Wasm versions, and this issue only occurs in the Wasm version on the Chart Gallery page (this does not happen on the RangeArea page: [https://apexcharts.github.io/Blazor-ApexCharts/rangearea-charts](https://apexcharts.github.io/Blazor-ApexCharts/rangearea-charts)). It seems the live docs are using Wasm.

 I could not find an obvious issue, I am new to ApexCharts so my troubleshooting is basic. I tried Edge, Chrome, Firefox on desktop and mobile and all gave the same results.

**Wasm**
![image](https://github.com/apexcharts/Blazor-ApexCharts/assets/22691956/ff12fd6b-4cc1-4f21-b519-0f4b69ee45fc)
 
**Server**
![image](https://github.com/apexcharts/Blazor-ApexCharts/assets/22691956/da51784f-bceb-4f3a-8c73-9e9d39a2a9a8)

 Thanks

**Comment by joadan** [comment]
Hi, thank you for reporting.
I managed to get it working locally in wasm but still it is not working on https://apexcharts.github.io/Blazor-ApexCharts/,

**Comment by joadan** [comment]
Fixed!
