### ISSUE TITLE
Y Axis zooming

### ISSUE THREAD

**Issue by g-fleming** [apexcharts/Blazor-ApexCharts#322]
For line charts, the X axis has zoom control with buttons as well as mouse drags across an area. I don't believe there is a way to do this with the Y axis (correct me if I am wrong). This would be a useful feature in regions of the charts where the delta Y value between sequential points is small relative to Y range and needs to be zoomed in for waveform analysis.

**Comment by joadan** [comment]
Hello,

Have you checked https://apexcharts.com/docs/options/chart/zoom/ and the type propery?
For detailed question on how apexcharts.js works it better to open issues in the apexcharts.js repo, here we focus on the blazor-wrapper.

Thank you

**Comment by g-fleming** [comment]
Ok thanks! you are right. I do see more options available on apexcharts website. I will close this issue.
