### ISSUE TITLE
Working with series in Blazor

### ISSUE THREAD

**Issue by christiankasongo** [apexcharts/Blazor-ApexCharts#324]
Hello, I want to add a bar chart on my blazor component. There is no examples (https://apexcharts.github.io/Blazor-ApexCharts/bar-charts ) that shows how to work with series.

I would like to do something like this
var options = {
          series: [{
          name: 'Net Profit',
          data: [44, 55, 57, 56, 61, 58, 63, 60, 66]
        }, {
          name: 'Revenue',
          data: [76, 85, 101, 98, 87, 105, 91, 114, 94]
        }, {
          name: 'Free Cash Flow',
          data: [35, 41, 36, 26, 45, 48, 52, 53, 41]
        }],
Thank you

**Comment by joadan** [comment]
Hello,

I have added a sample, https://apexcharts.github.io/Blazor-ApexCharts/bar-charts#included%20model
