### ISSUE TITLE
Styling not applied in Blazor component

### ISSUE THREAD

**Issue by Dyllaann** [apexcharts/Blazor-ApexCharts#325]
Hi there,

I'm trying to make some charts with Apexcharts. We're using datetime on X axis, and applied custom styling to rotate the labels.
There is also a rotate 90 given for the series label
Unfortunately, it's not being applied in the live chart itself. When downloading the png version of the chart it does apply.

![image](https://github.com/apexcharts/Blazor-ApexCharts/assets/7451618/24754f96-9aae-40a8-a603-c1260624eb27)

The png downloaded from the chart:

![image](https://github.com/apexcharts/Blazor-ApexCharts/assets/7451618/7c6f5aff-c405-448f-a80c-7d7499cea941)

Code:

```csharp
private ApexChartOptions<TicketsPerDay> Options { get; set; } = new()
    {
        Xaxis = new XAxis
        {
            Labels = new XAxisLabels
            {
                Rotate = -45,
                RotateAlways = true
            }
        },
        Yaxis = new List<YAxis>()
        {   
            new()
            {
                SeriesName = "MySeries",
                Title = new AxisTitle { Text = "Title", Rotate = (double)90 },
                DecimalsInFloat = 0
            }
        }
    };

```

How can I make sure the styling is also applied to the chart on the page itself?

**Comment by joadan** [comment]
Hello,

There should be nothing special here, I added a sample https://apexcharts.github.io/Blazor-ApexCharts/features/axis#rotate%20labels.

Have you assigned your options to the chart?

**Comment by DionWezz** [comment]
Yeah we do apply the options but they won't apply in the blazor page.
But when downloading the image it works

The blazor page:
![image](https://github.com/apexcharts/Blazor-ApexCharts/assets/33034471/6852e0e8-3e96-4533-ae7e-4ec4ffd783b7)

The export png
![eee7fdea015e46488c7d9a2b57eb026e](https://github.com/apexcharts/Blazor-ApexCharts/assets/33034471/1fc3e44a-9596-41bc-834d-d6d6062c6bbc)

**Comment by joadan** [comment]
Hello,

Have you looked at the sample?

**Comment by DionWezz** [comment]
> Hello,
> 
> Have you looked at the sample?

Yes the Apex Graph uses the options as shown in the sample. And yes I do include them in the <apexcharts> element.
Some of the options do affect the styling of the graph like the Type = XAxisType.Datetime but most of them do not affect the chart in any way.

Can it be some clashing stylesheets? or other problems with stylesheets?

Thanks in advance!

**Comment by Dyllaann** [comment]
I noticed the debug option specified in the Sample.
When adding that, there is chart output logged in the browser debug console. In there I could find the option is passed on
![image](https://github.com/apexcharts/Blazor-ApexCharts/assets/7451618/61b9cbb7-5a9a-45e8-9d75-adb2c9bb3a03)

Like @DionWezz mentioned, the HTML rendered version doesn't apply the rotation and/or other styling arguments we pass. The export image function does contain the requested rotation. (See images from an earlier comment as a reference)

**Comment by joadan** [comment]
Hello,

If you make a simple example in your code like the sample, is it working?
If yes add more logic and then you can pinpoint where it fails.

**Comment by joadan** [comment]
You can check the rotation in the svg element:

![2023-11-09 14_55_42-Blazor ApexCharts Documentation](https://github.com/apexcharts/Blazor-ApexCharts/assets/8363110/bc312ec2-202e-41df-9728-4b9e5a89c272)

**Comment by DionWezz** [comment]
We found it was an issue with our stylingsheets afterall.
Tailwind added a rotate 0 to the labels :(
Thanks for your help!

**Comment by joadan** [comment]
Great! 
Please don't forget to star the repo if you find it useful.
