### ISSUE TITLE
Stacked bar chart PlotOptionsBarDataLabels MaxItems property not working

### ISSUE THREAD

**Issue by nikhazy** [apexcharts/Blazor-ApexCharts#327]
Hi all,

First of all thanks for this wrapper, I like it so much!
I would like to have a stacked bar chart with labels JUST when i have less than X elements. According to the description
_(Maximum limit of data-labels that can be displayed on a bar chart. If data-points exceed this number, data-labels won't be shown.)_
of PlotOptionsBarDataLabels.MaxItems, it should do that.
But if I add this property to the example code like MaxItems=1:
![image](https://github.com/apexcharts/Blazor-ApexCharts/assets/60614819/a3db7bd9-f226-4b1f-a080-46437c783e01)

It still shows the labels.

Am I wrong, or i dont use it well?
Thanks for your response in advance!

**Comment by joadan** [comment]
Hello,

I'm sorry but I'm not familiar with the MaxItems property. I think it's probably better to ask in apexcharts.js repo.
