### ISSUE TITLE
exception accured when dynamic remove charts

### ISSUE THREAD

**Issue by ken1234l** [apexcharts/Blazor-ApexCharts#328]
I use a list to control charts add/remove on the view dynamically,  add is perfect, but when do remove, error like below sometimes happened:   

「Chart 7add47026b8146339fc7466da39115e5 must have at least one series」

Did I miss some setting when remove the chart?

**Comment by joadan** [comment]
Hello, I was able to reproduce this by switching pages multiple times on the demo site.

**Comment by joadan** [comment]
#336

**Comment by joadan** [comment]
I have made some improvments in v2.0.0. 
Could you please update and close if it is fixed.

Thank you

**Comment by ken1234l** [comment]
> I have made some improvments in v2.0.0. Could you please update and close if it is fixed.
> 
> Thank you

I will try it, thank for the improvement

**Comment by ken1234l** [comment]
> I have made some improvments in v2.0.0. Could you please update and close if it is fixed.
> 
> Thank you

I update to v2.0.0, 「Chart 7add47026b8146339fc7466da39115e5 must have at least one series」has gone.

I try to add/remove charts like what I done before, the view update will not be stopped by the error, but sometimes, after I remove a chart, one of the left charts will  stop update itself (I still do not know the reason), but the exception isuue has gone, I will close the issue.
