### ISSUE TITLE
Chart with two y-axis and two x-axis per serie. 

### ISSUE THREAD

**Issue by dineshjethoe** [apexcharts/Blazor-ApexCharts#329]
Hi there, 

is there a way to generate a chart with two y-axis and two x-axis per serie. The chart would display rectangles/squares per serie. 
For example: 
Y-axis: (2023-01-01, 2023-01-05), (2023-01-06, 2023-01-15), (2023-01-15, 2023-02-03) -> (startdate, enddate)
X-axis: (01, 02), (02 - 03), (03 - 05) -> (start week, end week)

Each serie has the combination of a (startdate, enddate) and (start week, end week).

Any suggestions? Perhaps another chart library or option in Blazor (wasm)?

**Comment by joadan** [comment]
Hello, Have you looked at RangeBar, https://apexcharts.github.io/Blazor-ApexCharts/rangebar-charts
