### ISSUE TITLE
Realtime Live chart doesn't work like JS equivalent

### ISSUE THREAD

**Issue by Reotte** [apexcharts/Blazor-ApexCharts#330]
I checked here for solution about this, Append data adds data seamlessly just as expected but does not remove the first data (I mean does not "scroll" through).

I want to be able to show only 15 data points on screen, without wiggly animations.

Some referred to UpdateSeriesAsync here but even on demo page that doesnt look right at all.

Basically these two does not look identical at all, while it is referred here before, that they have same purpose.

https://apexcharts.com/javascript-chart-demos/line-charts/realtime/

https://apexcharts.github.io/Blazor-ApexCharts/methods/update-series#realtime

**Comment by joadan** [comment]
Hello,

I have updated the sample, https://apexcharts.github.io/Blazor-ApexCharts/methods/update-series#realtime 
The key is to use the XAxis -Range property. 

In this example I use the AppendDataAync I don't have to serialize more then I have to, but you could also use the UpdateSeriesAsync.

**Comment by Reotte** [comment]
Thanks a lot!

Well I realized that wasn't my problem at all. When I tried your example I still got that "piling up". Looks like my issue was the "Range" property. I have that now and its working like expected!

Also updating series with `await chart1.UpdateOptionsAsync(true, true, false);` so it doesnt look like scrumbling.

Here's my code for future reference

`private async Task UpdateChartSeries()
{
	if (dataPointCounter > 10)
	{
		await chart1.UpdateOptionsAsync(true, true, false);
		dataPointCounter = 0;
	}

	ChartData prevData = chartData1.Last();

	ChartData newData = new ChartData
		{
			X = prevData.X + 1,
			A = GetNextData(prevData.A),
			B = GetNextData(prevData.B),
			C = GetNextData(prevData.C),
			D = GetNextData(prevData.D),
			E = GetNextData(prevData.E),
			F = GetNextData(prevData.F),
			G = GetNextData(prevData.G)
		};

	chartData1.RemoveAt(0);
	chartData1.Add(newData);

	StateHasChanged();

	dataPointCounter++;

	await chart1.AppendDataAsync(new List<ChartData> { newData });
}`
