### ISSUE TITLE
Add stackOnlyBar option from ApexCharts.js

### ISSUE THREAD

**Issue by jordanknapp00** [apexcharts/Blazor-ApexCharts#334]
If you try to create a stacked bar chart that also includes multiple line series, the line series don't render correctly. The lines are also stacked, meaning that if you had one line that was at y=1000 and another at y=500, the second one would render at y=1500.

[This appears to be an issue with ApexCharts.js](https://github.com/apexcharts/apexcharts.js/issues/907). The solution they appear to have taken is adding an option called [`stackOnlyBar`](https://github.com/apexcharts/apexcharts.js/pull/3891), which causes only bar series to be rendered as stacked.

Would it be possible to add this option to Blazor-ApexCharts? As of right now, all we have is the basic stacked option that applies to the entire chart.

**Comment by joadan** [comment]
Hello,

No problem to add it, but I don't 't think it's released yet. 
As far as I can see it's not included in Version 3.44.0.

**Comment by jordanknapp00** [comment]
Yes, you are correct, my bad. I look forward to this feature being added.

**Comment by joadan** [comment]
@jordanknapp00, I have added it in Release v2.2.0.
