### ISSUE TITLE
blazor_apexchart undefined

### ISSUE THREAD

**Issue by TehGM** [apexcharts/Blazor-ApexCharts#339]
After updating to v2.0.0 and removing the JS includes from _Host.cshtml file (as recommended in v2.0.0 changelog), I am getting this error in browser console:
![image](https://github.com/apexcharts/Blazor-ApexCharts/assets/9112561/53ad7415-551c-49e1-a2b6-847ab0f722c6)

Of course charts do not load anymore.  
Re-adding the JS files changes nothing, as these files are no longer included with the library.

.NET 8. Issue doesn't happen on library version 1.3.0.

**Comment by joadan** [comment]
Hello,

I'm not sure what could be the issue.
I have created a sample project in .Net8 and it seems to be working, https://github.com/joadan/Apexcharts.DotNet8

**Comment by lpolacek** [comment]
@TehGM Did you find source of the problem?

I have same problem, updating from 1.0.0 .NET 7 to 2.1.0 .NET 8, but for different functions.
![image](https://github.com/apexcharts/Blazor-ApexCharts/assets/97942747/624cb989-39fa-47a6-b345-721fe6f00a0b)
![image](https://github.com/apexcharts/Blazor-ApexCharts/assets/97942747/6e15ddf3-248d-47f4-8ae5-c63a059c3cd1)
