### ISSUE TITLE
Different Marker Sizes

### ISSUE THREAD

**Issue by Nick-L** [apexcharts/Blazor-ApexCharts#340]
I have a chart with 2 series on it one being a scatter plot and the other being a range area I am trying to remove the marker dots for the range area chart as they are not needed and make the chart cluttered. It looks like this is supported in apex charts [Example From Apex Charts](https://apexcharts.com/javascript-chart-demos/mixed-charts/line-scatter/) but it seems in the wrapper maker size is limited to a single double for value as opposed to other marker options such as color that can have multiple values. I am wondering if I am missing something or if this is a feature that is not supported by the wrapper.

Thanks for any help you can provide.

**Comment by joadan** [comment]
Hello,

You should be able to set the Marker -Size to a list.

`        options.Markers = new Markers
            {
                Size = new List<double> { 1, 3 }
            };`

**Comment by Nick-L** [comment]
Thanks. I swear I tried this on Friday before posting but must have imagined that thanks for the help.
