### ISSUE TITLE
Second x value always missing when XAxisType is DateTime

### ISSUE THREAD

**Issue by JoeFarrera** [apexcharts/Blazor-ApexCharts#342]
Versión 2.1.0

On a bar chart with XAxisType as Datetime, the second value is skipped. The tooltip has the correct value for the x-axis position as shown in the screen capture. 

If the zoom is changed, on occasions the missing bar appears, but by default it is always missing.

I can see no errors on the  (Chrome) browser console.

Code below.

<img width="1260" alt="BlazorAjaxChartDateTime" src="https://github.com/apexcharts/Blazor-ApexCharts/assets/170438/f565ba56-fc7f-4b8f-b7f6-7662ba7e91cf">

`@page "/GraphTest"

<PageTitle>Graph</PageTitle>

<MudContainer>
    <ApexChart TItem="MyData"
               Title="Sample Data" 
               Options="ChartOptions"
               >

        <ApexPointSeries TItem="MyData"
                         Items="Data"
                         Name="Some Value"
                         SeriesType="SeriesType.Bar"
                         XValue="e => e.DiaHora"
                         YValue="e=> e.SomeValue" /> 

    </ApexChart>
</MudContainer>

@code {
    private List<MyData> Data { get; set; } = new();
    private ApexChartOptions<MyData> ChartOptions { get; set; } = new();
    protected override void OnInitialized()
    {

        DateTime startTime = DateTime.Now;
        DateTime startOfHour = new DateTime(startTime.Year, startTime.Month, startTime.Day, startTime.Hour, 0, 0, 0);
        Random rnd = new Random();
        for (int i = 0; i < 4; i++)
        {
            Data.Add(new MyData { SomeValue = rnd.Next(1, 11), DiaHora = startOfHour.AddHours(i) });
        }

        ChartOptions.Xaxis = new XAxis
            {
                Type = XAxisType.Datetime,
                Labels = new XAxisLabels
                {
                    DatetimeUTC = false,
                    RotateAlways = false,
                }
            };

        ChartOptions.Tooltip = new ApexCharts.Tooltip
            {

                X = new TooltipX
                {
                    Format = "HH:mm"
                }
            };
    }

    public class MyData
    {

        public DateTime? DiaHora { get; set; }
        public int SomeValue { get; set; }
    }
}
`

**Comment by joadan** [comment]
Hello,

I believe this is the same as reported here, https://github.com/apexcharts/apexcharts.js/issues/4111

**Comment by JoeFarrera** [comment]
Yes it is. My apologies, should have seen that, thanks.

**Comment by joadan** [comment]
Fixed in apexcharts.js
