### ISSUE TITLE
UpdateSeriesAsync not animating?

### ISSUE THREAD

**Issue by Jako731** [apexcharts/Blazor-ApexCharts#345]
Hi,

I have an `<ApexChart @ref="chart">....</ApexChart>` and whenevery i try to update the chart with `chart.UpdateSeriesAsync()`, it updates the content for the chart but doesnt display any animations despite have animation set in the options (Initial render animations show).

Is there something im missing?

**Comment by joadan** [comment]
Hello,

I don't know what could be the issue, have you checked the sample at https://apexcharts.github.io/Blazor-ApexCharts/methods/update-series

**Comment by Jako731** [comment]
Turns out somewhere `options.Series` is null so i just had to put in a check for that
