### ISSUE TITLE
Choose Toolbar items in Area Chart

### ISSUE THREAD

**Issue by mattiaslundborg** [apexcharts/Blazor-ApexCharts#346]
I dont want to show all toolbar items/icons. Is there away to get rid of some of them?

This removes everything:
Toolbar = new Toolbar
{
    Show = false
},

But i want to keep some and remove some. Is there a way to do this?

If this doesn't work, how do i zoom out from my area chart if i have Toolbar.Show set to false?

**Comment by joadan** [comment]
Hello,

I added a sample here https://apexcharts.github.io/Blazor-ApexCharts/features/toolbar#hide%20icons

Documentation https://apexcharts.com/docs/options/chart/toolbar/

**Comment by mattiaslundborg** [comment]
Thank you! Appreciate the fast support!
