### ISSUE TITLE
Timeline charts?

### ISSUE THREAD

**Issue by Mr-Technician** [apexcharts/Blazor-ApexCharts#35]
Do you have plans to support timeline charts like these here? They appear to be modified bar charts but I wasn't able to replicate them with this library.

https://apexcharts.com/javascript-chart-demos/timeline-charts/

**Comment by joadan** [comment]
Hi,
This should be possible.
I have added a [sample](https://apexcharts.github.io/Blazor-ApexCharts/rangebar-charts)  check Date Range

Please let me know if you still have questions.

**Comment by Mr-Technician** [comment]
Thanks so much!

**Comment by Mr-Technician** [comment]
How about a chart like this? https://apexcharts.com/javascript-chart-demos/timeline-charts/multiple-series-group-rows/

I don't see a way to specify x/y and also indicate what row the item should be in.
