### ISSUE TITLE
Conflict with BlazorMonaco

### ISSUE THREAD

**Issue by Crazy1van** [apexcharts/Blazor-ApexCharts#355]
When using Apexcharts 2.0 or higher and using BlazorMonaco at the same time, I encounter an error:  "SVG is not defined".

I suspect that there is some sort of javascript conflict between these two nuget packages.  I know this is very specific, but BlazorMonaco is a fairly popular component.

Steps to reproduce:
- Create a new Blazor Server project.
- Add Apexcharts package and include a chart on main page,
- Add BlazorMonaco package (including the three _content scripts in _Layout.cshtml per instructions).
- Run the project.  As soon as the chart tries to draw, it generates an unhandled exception.

It worked fine on version 1.3.0 and below.

**Comment by Alexr03** [comment]
I am encountering the same issue any help with this would be appreciated. 👍🏼

**Comment by Alexr03** [comment]
Came across this issue on the BlazorMonaco https://github.com/serdarciplak/BlazorMonaco/issues/59
You can use the solution provided and it fixed my issues. 

The prebuilt version only comes with json/yaml support but you can rebuild it with the languages you want.

**Comment by Crazy1van** [comment]
@Alexr03, thanks for that.  That does appear to work, but unfortunately (AFAIK) Microsoft does not support loading Monaco in this manner, so it's more of a workaround rather than a viable solution (at least for us).  We will probably just stay on 1.3.0 until this is resolved in BlazorMonaco (hoping).  We may need to start looking into other charting solutions, although I do really like ApexCharts.

**Comment by Alexr03** [comment]
Are you sure they don't support it? They do provide documentation on it. https://github.com/microsoft/monaco-editor/blob/main/docs/integrate-esm.md

For us at least, we have forked the repo, modified the webpack config to add the languages we need and serving the built files in our blazor app. Its fixed the issues we were having when using ApexCharts, Monaco & XTerm

**Comment by Crazy1van** [comment]
I see what you're saying.  Yes, it looks like they support using webpack which bypasses the loader method responsible for this conflict.   I'll investigate this as an alternative.  Honestly, this still doesn't look "clean" since BlazorMonaco is not intended to be used this way, and it introduces additional complexity to our builds (by having to use webpack).

**Comment by joadan** [comment]
Hello,

I bit late to the party here but is there anything we can do on the Blazor-Apexcharts side to help with this issue?

**Comment by Crazy1van** [comment]
@joadan, thanks for your reply.  I have not troubleshot this (we are so busy), but it appears that Blazor-ApexCharts 2.0 introduced something new that conflicts with BlazorMonaco's loader.js (written by Microsoft).  I am hoping that whatever is causing this conflict could be "fixed" (I realize this is not a bug, per se).  I described how to reproduce in the OP.

**Comment by Alexr03** [comment]
> Hello,
> 
> I bit late to the party here but is there anything we can do on the Blazor-Apexcharts side to help with this issue?

I believe its related to this issue. https://github.com/serdarciplak/BlazorMonaco/issues/20

**Comment by joadan** [comment]
@Alexr03, thank you.

@Crazy1van, in 2.0 Blazor-Apexcharts started using ECMAScript Modules (ESM) to lazy load the javascript file.
This according to blazor docs https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/?view=aspnetcore-8.0#javascript-isolation-in-javascript-modules.

I believe this issue is on the BlazorMonaco side, a workaround is proposed by @Alexr03 https://github.com/apexcharts/Blazor-ApexCharts/issues/355#issuecomment-1849189290 

Not sure if there is anything more we can do here, or?

**Comment by joadan** [comment]
I was able to work around by using this fix, https://github.com/serdarciplak/BlazorMonaco/issues/81#issuecomment-1874646448

**Comment by StephenOTT** [comment]
@joadan are you using the latest versions of each library?

**Comment by joadan** [comment]
@StephenOTT, sorry I was to fast..  I had to make a custom build in order to make it work.
https://github.com/microsoft/monaco-editor/blob/main/docs/integrate-esm.md

**Comment by StephenOTT** [comment]
@joadan 
I was able to make it work with this update to index.html:

```
<script src="_content/BlazorMonaco/jsInterop.js"></script>
<script src="https://cdn.jsdelivr.net/npm/monaco-yaml-prebuilt/dist/monaco-editor.min.js"></script>
```
