### ISSUE TITLE
Get DataUri renders white square in the graph

### ISSUE THREAD

**Issue by DionWezz** [apexcharts/Blazor-ApexCharts#356]
If we retrieve the image uri with the GetDataUriAync() function and render the image there appears a white square.
The same goes for the image on your website if we change the background color of the div to black:

<img width="539" alt="image" src="https://github.com/apexcharts/Blazor-ApexCharts/assets/33034471/f5969b37-9a37-4734-a457-e5606fdff195">

**Comment by joadan** [comment]
Hello,

I don't see how this can be an issue in the wrapper..
Can you reproduce it in pure apexcharts.js?

**Comment by DionWezz** [comment]
We do use the C# wrapper function for this. I do not use the javascript.

**Comment by joadan** [comment]
Hi,

My point is that this is the behavior of the apexchart.js component. 
Not much we can do in the wrapper, it's better that you raise the issue in the apexchart.js repo.

**Comment by DionWezz** [comment]
> Hi,
> 
> My point is that this is the behavior of the apexchart.js component. Not much we can do in the wrapper, it's better that you raise the issue in the apexchart.js repo.

Is it possible that you move this issue to the right repo?

**Comment by joadan** [comment]
> Is it possible that you move this issue to the right repo?

Sorry, I can not do that. Please raise the issue there.

Thank you
