### ISSUE TITLE
Tooltip not showing zero values on Line Chart

### ISSUE THREAD

**Issue by Nephim** [apexcharts/Blazor-ApexCharts#364]
This issue is the same as:

https://github.com/apexcharts/apexcharts.js/issues/4149
![290297569-5ffa2236-3758-485e-b8b1-d8e2bf2b85f8](https://github.com/apexcharts/Blazor-ApexCharts/assets/39805658/a4e6ee65-4106-4284-ae67-0690fe0e38a6)

However its also present in the Blazor wrapper.

As I commented on that issue, there is a property on the tooltip saying

``` js
tooltip: {
   hideEmptySeries: false,
}
```

This is not mirroed in C#,

Does anyone know of a workaround to set the underlying JS value?

**Comment by joadan** [comment]
Hi,

We should be able to add this property later today.

**Comment by joadan** [comment]
Hi,

Added the property in v2.2.1. 

@Nephim Would be great if you could test it and close the issue if it works.

Thank you

**Comment by Nephim** [comment]
Hello @joadan,

I've just tested it and works as I expected.

Thank you very much for the quick solution 👍
