### ISSUE TITLE
Area chart svg lines funky after .NET 8 upgrade

### ISSUE THREAD

**Issue by keenan-chiasson** [apexcharts/Blazor-ApexCharts#376]
After updating my project to .NET 8 the area charts are displaying buggy behavior
<img width="537" alt="image" src="https://github.com/apexcharts/Blazor-ApexCharts/assets/113039829/155277ae-7027-4f11-bdd3-ab93447028a2">

After testing with my team, we noticed that the behavior occurs due to null values and only on area charts, not on line charts.

**Comment by nmakhmutov** [comment]
<img width="1392" alt="Screenshot 2024-01-04 at 19 04 06" src="https://github.com/apexcharts/Blazor-ApexCharts/assets/28149951/1760a84e-e9e1-40af-8bde-bb3dd31e3c4b">

Yes, I faced with the same problem with SeriesType.Area

**Comment by keenan-chiasson** [comment]
Disabling animation seems to be a usable workaround until this is fixed

**Comment by joadan** [comment]
According to https://github.com/apexcharts/apexcharts.js/issues/4154 this has been fixed in apexcharts.js

I'll close the issue, please re-open if problem persists.
