### ISSUE TITLE
How to re-scale Y Axis when (un)zooming?

### ISSUE THREAD

**Issue by sam-wheat** [apexcharts/Blazor-ApexCharts#379]
Chart below looks flat because Y Axis is compressed.  Desired:  Y-Axis scaled to actual values +- 10% or something close.

Have seen this:  https://apexcharts.com/docs/zooming-in-category-x-axis/ and this:  https://apexcharts.com/docs/methods/#resetSeries but it does not have desired effect.

![image](https://github.com/apexcharts/Blazor-ApexCharts/assets/16885210/89507f92-bd63-425d-8e6e-b9c35bd6ad20)

**Comment by joadan** [comment]
Hi,

Have you checked [autoScaleYaxis](https://apexcharts.com/docs/options/chart/zoom/#autoScaleYaxis)

**Comment by sam-wheat** [comment]
Thank you.
