### ISSUE TITLE
difficulty with simple line chart implementation

### ISSUE THREAD

**Issue by wvmstr** [apexcharts/Blazor-ApexCharts#38]
I have not been able to get my first line chart off the ground, and have an exception that does not give me any clues what steps to take next:

blazor.server.js:1 
        
       [2021-11-27T17:42:13.572Z] Error: System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'source'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at ApexCharts.ApexPointSeries`1.GetData()
   at ApexCharts.ApexChart`1.SetSeries()
   at ApexCharts.ApexChart`1.Render()
   at ApexCharts.ApexChart`1.OnAfterRenderAsync(Boolean firstRender)
   --- End of inner exception stack trace ---

`@page "/linechart"

@using ServerAdv.Data
@using ClassLibraryHm
@using System.Net.Http
@using MudBlazor
@*using ApexCharts*@
@using BlazorApexCharts

@inject IHttpClientFactory _clientFactory

<MudContainer>
    <ApexChart TItem="HatchDataDto"
               Title="Order Net Value">

        <ApexPointSeries TItem="HatchDataDto"
                         Items="hatchdata"
                         Name="Data H"
                         SeriesType="SeriesType.Line"
                         XValue="@(e => e.dateIndex)"
                         YValue="@(e => e.DataH)"
                         OrderBy="e=>e.X" />

        <ApexPointSeries TItem="HatchDataDto"
                         Items="hatchdata"
                         Name="Data L"
                         SeriesType="SeriesType.Line"
                         XValue="@(e => e.dateIndex)"
                         YValue="@(e => e.DataL)"
                         OrderByDescending="e=>e.X" />
    </ApexChart>
</MudContainer>

@code {
    private List<HatchDataDto> hatchdata { get; set; }

    string baseUrl = "https://localhost:44344";

	protected override async Task OnInitializedAsync()
	{
		var httpClient = _clientFactory.CreateClient("ServerAPI");
		httpClient.DefaultRequestHeaders.Add("Accept", "application/json");

		hatchdata = await httpClient.GetFromJsonAsync<List<HatchDataDto>>($"{baseUrl}/api/Hatch/ByDataId/{469}");
	}
}`

[
  {
    "id": 13733,
    "hatchMainId": 469,
    "dataH": 1136,
    "dataL": 7012,
    "dateIndex": 1
  },
  {
    "id": 13734,
    "hatchMainId": 469,
    "dataH": 1134,
    "dataL": 6978,
    "dateIndex": 2
  },
  {
    "id": 13735,
    "hatchMainId": 469,
    "dataH": 1128,
    "dataL": 6997,
    "dateIndex": 3
  } etc
]

What am I doing wrong here?

**Comment by joadan** [comment]
Hi,

Try to wrap the chart in an if statement..
something like this..

```
@if (hatchdata != null) 
{
<ApexChart>
...
</ApexChart>
}

```
Please give it a try.. if you have issues just let me know.

**Comment by wvmstr** [comment]
Ah yes!  That was it.

Thnx
