### ISSUE TITLE
TimeStamps in chart 1 hour later then they should be

### ISSUE THREAD

**Issue by PatTheLad** [apexcharts/Blazor-ApexCharts#381]
When I load data from my backend everything looks fine and 
even when I load it in the chart for only one day everything again looks just fine.
But when I load mutliple days (only sometimes) every timestamp moves 1 hour into the future.

How it looks wrong with 2 days (one hour later then it should be)
![image](https://github.com/apexcharts/Blazor-ApexCharts/assets/132983689/ffbaa3bf-2b23-42d4-a849-508eb2a7a1cc)

How it should be
![image](https://github.com/apexcharts/Blazor-ApexCharts/assets/132983689/a9209d07-ce8e-4d68-89d5-32a273f4053d)

Thanks in advance for your help!

**Comment by meronz** [comment]
Could this be already fixed in ApexCharts.js 3.45.2? 

Possibly related PR https://github.com/apexcharts/apexcharts.js/pull/4159

**Comment by joadan** [comment]
> Could this be already fixed in ApexCharts.js 3.45.2?
> 
> Possibly related PR [apexcharts/apexcharts.js#4159](https://github.com/apexcharts/apexcharts.js/pull/4159)

Could be, I don't have the details. I'll try to prepare a new version that we can try.

**Comment by joadan** [comment]
please check version 2.3.0

**Comment by PatTheLad** [comment]
Thank you all for the fast answers!
The problem didnt show up again (seems to be fixed).
