### ISSUE TITLE
How to catch Clicks on Annotations?

### ISSUE THREAD

**Issue by raceecondition** [apexcharts/Blazor-ApexCharts#383]
[https://apexcharts.com/docs/options/annotations/](https://apexcharts.com/docs/options/annotations/) shows there is mouseEnter, mouseLeave and click Events on Annotations. How can i get that functionality?

**Comment by joadan** [comment]
Hello,

Currently this is not available. I'll try to have a look if it can be implemented.

**Comment by joadan** [comment]
Sample at, https://apexcharts.github.io/Blazor-ApexCharts/features/annotations#events

Please note this is not released yet.
Looks like there is an issue with dynamically added annotations, most likely this is an limitation in apexchart.js, https://codepen.io/joadan-the-sasster/pen/WNmdNRq

**Comment by joadan** [comment]
fixed in version 2.3.0,  https://github.com/apexcharts/Blazor-ApexCharts/releases/tag/v2.3.0
