### ISSUE TITLE
Setting Stacked to true causes console error.

### ISSUE THREAD

**Issue by Mr-Technician** [apexcharts/Blazor-ApexCharts#39]
Setting `Stacked` to true causes this error to appear in the console:

![image](https://user-images.githubusercontent.com/26885142/144101420-a731f2cb-7424-4f62-8439-b85e98177503.png)

https://github.com/apexcharts/Blazor-ApexCharts/blob/6217b63d477e46d4c3ca68347bf560af18171a44/src/Blazor-ApexCharts/Models/ApexChartOptions.cs#L338

I'm using a range bar chart.

**Comment by Mr-Technician** [comment]
Maybe this is only supported for bar and not range bar charts?

I'm trying to collapse multiple bars into a single horizontal line like below:

![image](https://user-images.githubusercontent.com/26885142/144102022-8236b624-3722-4d58-978c-d140044b129a.png)

**Comment by joadan** [comment]
Hi,

I added support for this in 0.9.0-beta.
Please check https://apexcharts.github.io/Blazor-ApexCharts/rangebar-charts#grouped
