### ISSUE TITLE
How do i do RangeBar Charts?

### ISSUE THREAD

**Issue by oOJoshOo** [apexcharts/Blazor-ApexCharts#391]
they arent available in the SeriesType

**Comment by joadan** [comment]
Hi,
Have you checked the samples, https://apexcharts.github.io/Blazor-ApexCharts/rangebar-charts

**Comment by oOJoshOo** [comment]
Nope thats what i needed Thank you :D

**Comment by oOJoshOo** [comment]
Where can I view the sample data? So that I know how to feed the chart.

**Comment by joadan** [comment]
Hi the samples are part of the rep, https://github.com/apexcharts/Blazor-ApexCharts/tree/master/docs/BlazorApexCharts.Docs
