### ISSUE TITLE
stepSize is missing form x and y axis

### ISSUE THREAD

**Issue by LagunaRyan** [apexcharts/Blazor-ApexCharts#396]
For both `Xaxis` and `Yaxis`, there should be a `stepSize` property.

[xaxis docs](https://apexcharts.com/docs/options/xaxis/)
> stepSize refers to the interval between consecutive values on an x-axis. It determines how the values on the axis are spaced or displayed. If the step size is set to 10, the axis might display values like 0, 10, 20, 30, and so on.

**Comment by joadan** [comment]
Fixed in v2.3.1
