### ISSUE TITLE
Annotations multiline support - Solution proposal

### ISSUE THREAD

**Issue by peterboccia** [apexcharts/Blazor-ApexCharts#408]
Hi all,

after a lot of research I found out that ApexCharts has changed the annotations to support multiline.
I tried all before: \n, <br /> etcetera, but neither works. And the problem was: in the annotation (X or Y indiscriminately) the property text is use to hold string or array of strings if you want multiple lines to show.
Unfortunately in C# we don't have the discriminated union so we need to choose: object to handle everything and put a comment on it, or directly use a List<string> as type.
I made the changes as List<string> and it worked: samples of annotations still work as before, added a new one to handle two lines and works as expected.
Maybe, it could be easier to handle an object because this would affects the retro-compatibility of the library.
I'll make the changes and push the PR.
Thanks in advance for you attention

**Comment by joadan** [comment]
Hi,

Your PR has been accepted and merge into the main branch. 
I will prepare a release in a couple of days.
