### ISSUE TITLE
Thousand Separator

### ISSUE THREAD

**Issue by yadoy666** [apexcharts/Blazor-ApexCharts#41]
Hi, i am new in apexcharts and so far it's looks good. 
I have one question, how to format number use thousand separator? for example 1000000 become 1.000.000
Usually in C#,  i use syntax like this =>  String.Format(_id, "{0:N0}", 1000000); 
where _id is indonesian cultureinfo. 

Thanks for your help.

**Comment by joadan** [comment]
Hello,

Currently it's only possible to use javascript to format values. Apexchart has a concept of formatters that you can pass in to format values. Something like this.

`
        options.Yaxis = new List<YAxis>();
        options.Yaxis.Add(new YAxis
            {
                Labels = new AxisLabels
                {
                    Formatter = @"function (value) { return Number(value).toLocaleString() }"
                }
            }
        );
`
I updated the sample [https://apexcharts.github.io/Blazor-ApexCharts/area-charts](https://apexcharts.github.io/Blazor-ApexCharts/area-charts)  Fill 

We understand that this is not ideal, there is an open issue to support formatting using C# instead, #37

**Comment by yadoy666** [comment]
@joadan thanks for your quick reply.
