### ISSUE TITLE
Custom tooltip ignored 

### ISSUE THREAD

**Issue by Domivan** [apexcharts/Blazor-ApexCharts#410]
Starting from version 2.3.2 ApexPointTooltip stopped rendering as if it was not in the markup
Version 2.3.1 worked
![image](https://github.com/apexcharts/Blazor-ApexCharts/assets/4354000/1da2fea0-57b8-4bfb-8b24-cc098aa32964)

**Comment by joadan** [comment]
Hi,

Have you cleared the browser cache?
Do you have any errors in the console.

It works for me...

![image](https://github.com/apexcharts/Blazor-ApexCharts/assets/8363110/456ee04e-f4c4-4cc0-a89d-6cb1a1821c7f)

**Comment by Domivan** [comment]
Ok, really, thanks.
The problemwas on my side.
