### ISSUE TITLE
First-timer to this library...doesn't do anything :-(

### ISSUE THREAD

**Issue by johnds1974** [apexcharts/Blazor-ApexCharts#411]
Hi

I'm using this for the first time (v2.3.3), followed the instructions on the intro page, added a new razor page in my test project (Blazor Server with Interactive Rending turned on), added the sample chart code, ran it, and nothing appears.

Eventually, without any indication from the docs, I think. I had to download Apexcharts javasript files into my wwwroot/js folder, ran it again, and no change.

How on earth do I get a chart to show up on a page??

**Comment by joadan** [comment]
Hi,

Please have a look at this sample repo... 

https://github.com/joadan/WebAppChartsServer
