### ISSUE TITLE
TickAmount wrong enum value

### ISSUE THREAD

**Issue by peterboccia** [apexcharts/Blazor-ApexCharts#413]
There is a typo in the [TickPlacement](https://github.com/apexcharts/Blazor-ApexCharts/blob/be637d81c644f46ae9c2cee891851b0155a4e36f/src/Blazor-ApexCharts/Models/ApexChartOptions.cs#L5562) enum that will not affect the chart options when serialized.
The enum value `Beteween` should be `Between` as explained in the ApexCharts [docs](https://apexcharts.com/docs/options/xaxis/#tickPlacement) so when we use the current enum value, it would never affect the chart.
I already created a fix and I'll create a pull request.

**Comment by joadan** [comment]
Released in v3.0

Thank you
