### ISSUE TITLE
Chart not updating after asynchronous call

### ISSUE THREAD

**Issue by Domivan** [apexcharts/Blazor-ApexCharts#416]
First call UpdateSeriesDelay method not cause to update chart

 private int GetRandom => new Random().Next(1, 12);

 private async Task UpdateSeriesDelay()
 {
     await Task.Delay(10); // this blocks first chart update
     
     ShowData = Data.Take(GetRandom).ToList();
     await chart.UpdateSeriesAsync(true);
 }

 private async Task UpdateSeries()
 {
     ShowData = Data.Take(GetRandom).ToList();
     await chart.UpdateSeriesAsync(true);
 }
 
 Test project:
[https://github.com/Domivan/MudTests](url)

**Comment by joadan** [comment]
Hi,

Please try to add a StateHasChanged().



```
private async Task UpdateSeriesDelay()
{
    await Task.Delay(10); // this blocks first chart update
    ShowData = Data.Take(GetRandom).ToList();
    StateHasChanged();
    await chart.UpdateSeriesAsync(true);
}
```

**Comment by Domivan** [comment]
Great! Thank you!
