### ISSUE TITLE
multiple chart.AppendDataAsync(newData); will freeze the browser

### ISSUE THREAD

**Issue by BvdPutten** [apexcharts/Blazor-ApexCharts#418]
I was testing the line chart example mentioned in [https://apexcharts.github.io/Blazor-ApexCharts/methods/append-data](https://apexcharts.github.io/Blazor-ApexCharts/methods/append-data). When having an update every second or so, the browser (Chrome) will use a huge amount of resources and the page will not or very slow respond. Have I created a memory leak or something like it?

**Comment by joadan** [comment]
Hi,

Not sure I'm missing something here but if you append data more memory will be used.
