### ISSUE TITLE
Make the Annotation to the background of the series

### ISSUE THREAD

**Issue by annLiu310** [apexcharts/Blazor-ApexCharts#419]
![image](https://github.com/apexcharts/Blazor-ApexCharts/assets/32078412/6c587bfe-4caa-4f02-ad1f-77492a77c48f)

I found that the annotation is at the top of the series, changing the series color.
Is it possible to put it the the background of the series?

**Comment by digitaldirk** [comment]
I haven't got this to work yet, but maybe try z-index values for the annotation and lines?

**Comment by joadan** [comment]
Hi

This question is better to raise in the apexchart.js repo. 

Thank you
