### ISSUE TITLE
Detailed example for ApexRangeSeries

### ISSUE THREAD

**Issue by vadimffe** [apexcharts/Blazor-ApexCharts#42]
Hejsån! Great charts, just wish there would be more detailed examples somewhere and wider audience for keeping this repo alive and actively maintained. I have got majority of examples working, but can't figure out how you managed ApexRangeSeries functioning.

I have seen documentation: https://apexcharts.github.io/Blazor-ApexCharts/rangebar-charts

Basically I am trying to imitate GanttChart with this chart, so I came up with this model:

```
    protected async override Task OnInitializedAsync()
    {
      this.ProjectsList = await this.HttpClient.GetFromJsonAsync<IEnumerable<Project>>("api/Projects");

      this.InitializeGanttChartOptions();

      this.GanttChart = this.ProjectsList
      .Select(s => new GanttChartModel
      {
        XAxisValue = s.Name,
        YAxisValue = new List<decimal> { s.ProjectStartDate.Ticks, s.ProjectEndDate.Ticks },
      }).ToList();
    }
```
Then razor part:
```
  <ApexChart TItem="GanttChartModel"
           Title="Gantt view"
           Options=Options
           XAxisType="XAxisType.Datetime">
    <ApexRangeSeries TItem="GanttChartModel"
                   Items="this.GanttChart"
                   XValue="@(e => e.XAxisValue)"
                   YValue="@(e => e.YAxisValue)" />
  </ApexChart>
```
So at this point YValue is decimal, but for getting range it should be `public IEnumerable<decimal> YAxisValue { get; set; }`. How to get it working?

My model:
```
  public class GanttChartModel
  {
    public object XAxisValue { get; set; }
    public IEnumerable<decimal> YAxisValue { get; set; }
  }
```

**Comment by joadan** [comment]
Hi, 

I understand the issue, I'm working on a fix to make this easier.

**Comment by vadimffe** [comment]
@joadan there are might be some easier implementation with either List or Array I guess. Anyway got it working with: 

```
      List<GanttChartModel> result = new List<GanttChartModel>();
      this.ProjectsList.ForEach(r => {
        result.Add(new GanttChartModel
        {
          XAxisValue = r.Name,
          YAxisValue = r.ProjectStartDate.AddDays(1)
        });
        result.Add(new GanttChartModel
        {
          XAxisValue = r.Name,
          YAxisValue = r.ProjectEndDate.AddDays(1)
        });
      });
```

Currently looking for solution to:

1. Control Height of chart dynamically, based on number of items (can be done with some formula, need to test)
2. Have a control on steps. Is there any way?:

- to have more steps = dates on X axis?
- in different format = custom format for example (dd.mm.yyyy)?
- align labels on X axis for example vertically?

I mean these X axis labels:
![image](https://user-images.githubusercontent.com/72302395/149963902-8cd580c1-9a8f-40cb-8eb4-acda741326c0.png)

**Comment by joadan** [comment]
I have now added the option to set YMin/Max value on the ApexRangeSeries. 
Check it out at https://apexcharts.github.io/Blazor-ApexCharts/rangebar-charts#date%20range . 
There is a new nuget version 0.6.1-alpha.

Formatting Datetime X Axis is described here, https://apexcharts.com/docs/datetime/
Docs for the X-Axis options, here https://apexcharts.com/docs/options/xaxis/

For the dynamic height I guess you should be able to set the the height on the chart calculated from the number of items in the list.

Please let me know if there are questions.

**Comment by vadimffe** [comment]
Good improvement with YMin/Max, especially for such a novice guy like me. Easier to understand the logic of populating charts!

According to documentation it seems like setting ticks is not possible in DateTime scenario...

> tickAmount: Number
> Number of Tick Intervals to show.
> 
> **Note: tickAmount doesn’t have any effect when xaxis.type = datetime**
> 
> If you have a numeric xaxis xaxis.type = 'numeric', you can specify tickAmount: 'dataPoints' which would make the number of ticks equal to the number of dataPoints in the chart.

That's clear then. I can probably close this issue.

**Comment by joadan** [comment]
Hi,

Yes I came to the same conclusion that is not possible when having xaxis.type = datetime.
I guess you could use numeric type and then use the formaters to format the values. 

I'll try to set up sample when time allows.

**Comment by joadan** [comment]
Clean up
