### ISSUE TITLE
How can I remove a point from the graph?

### ISSUE THREAD

**Issue by Boobert21** [apexcharts/Blazor-ApexCharts#425]
Hi all! I apologize if this topic already exists :)
I'm adding points on using 

`timeSeries.AddRange(newData);

await chart.AppendDataAsync(newData);`

 , but is there a way to remove a point from the graph dynamically? For example, when adding a point, I put an object in the list that describes the point. But if I delete, for example, the first object from the list, and use the previous methods, then the point will not disappear on the graph, although it is not in the list. I also tried to create a ready-made copy of the list and pass exactly the copy to the method, but this did not help.
If anyone knows the answer, please tell me! Thank you very much in advance!

**Comment by joadan** [comment]
Hi,

I'm afraid there is no explicit method to remove data, but you should be able to use UpdateSeriesAsync method to provide a new set of data.

Sample here, https://apexcharts.github.io/Blazor-ApexCharts/methods/update-series

**Comment by Boobert21** [comment]
Hello! Thank you for your quick response.
In my project I want to use dynamic "real time" graphs. The point is that in the cycle a new object (point) is added to the list (series) and entered on the graph. But, in order not to cause the graph to overflow, when adding a certain number of points, the first objects from the list begin to be deleted. And if you use the method of updating the graph, then everything works out. But then there is no talk about beauty and smoothness. The schedule begins to rebuild, performing an animation that is unpleasant to watch. The "live" chart becomes unreadable for the user. Maybe there is a way to beautifully get rid of the first point in the list? Or at least disable animation when updating the graph?
Thank you in advance!
