### ISSUE TITLE
Bad perfomance Syncronized Charts with brush

### ISSUE THREAD

**Issue by Domivan** [apexcharts/Blazor-ApexCharts#426]
Syncronized Charts with brush works with very low performance when there are markers on the main chart (Value)
Already at a series of > 100 points, a strong drop in performance is noticeable. Please tell me the solution to the problem.

**Comment by Domivan** [comment]
I discovered that the problem is related to the presence of the <ApexPointTooltip></ApexPointTooltip> tag
If you override tooltips on a chart, it will always render with markers whether you want it to or not.
And then the performance of Brush Chart drops.

**Comment by joadan** [comment]
Hi,

My understanding is that markers are required for a line chart in order to have a custom tooltip in apexcharts.js.
This is why the wrapper automatically adds them, https://github.com/apexcharts/Blazor-ApexCharts/blob/cb8961d2423a63216afe21a3d0eed15c46e49555/src/Blazor-ApexCharts/ApexChart.razor.cs#L612

**Comment by Domivan** [comment]
That's right, and that's the problem.
Here's the marker and the built-in tooltip that only appears when you hover over the mouse, right?
![image](https://github.com/apexcharts/Blazor-ApexCharts/assets/4354000/17d643ba-f663-4e08-bbde-df88d1032d35)
We need the same behavior for custom tooltips.
Or solve the performance issue with markers enabled. I believe the problem correlates with the previously identified
[issue 1778](https://github.com/apexcharts/apexcharts.js/issues/1778)

**Comment by joadan** [comment]
hi,

If you want a custom tooltip for a line with no markers then you will have to do it with javascript.
Please see sample here: https://apexcharts.github.io/Blazor-ApexCharts/features/tooltip-javascript

>  Or solve the performance issue with markers enabled. I believe the problem correlates with the previously identified [issue 1778](https://github.com/apexcharts/apexcharts.js/issues/1778)

Please note that apexcharts.js is creating the chart using svg each object in the chart is an svg element.
The more elements you add the more work the browser has to do, and I'm afraid that we don't see any magic solution to this.
