### ISSUE TITLE
Axis title name that is too long is truncated

### ISSUE THREAD

**Issue by warpor** [apexcharts/Blazor-ApexCharts#430]
The original title of the axis was "Very long and beauty testing line for example", but in the end all that's left is "Very long and beauty testing line for exam".
![изображение](https://github.com/apexcharts/Blazor-ApexCharts/assets/31928576/7b968d92-5a45-470e-a8eb-36d890425852)
In the apex charts we can pass list of strings for multiline text(check this issue https://github.com/apexcharts/apexcharts.js/issues/388).

I suggest using the class from this commit(https://github.com/apexcharts/Blazor-ApexCharts/pull/409) and using it to be able to pass list of strings to titles

**Comment by joadan** [comment]
Fixed

**Comment by joadan** [comment]
fixed in v3.2.0
