### ISSUE TITLE
Determine when the chart has finished loading

### ISSUE THREAD

**Issue by danielchalmers** [apexcharts/Blazor-ApexCharts#432]
Looking to be able to show a loading indicator while the actual javascript chart is loading. This is especially important in the context of #360.

https://github.com/apexcharts/Blazor-ApexCharts/assets/7112040/213c684b-a4aa-40d0-85d4-9c2d13fcb089

You can see a blank page for a bit.

---

Suggestion: OnLoaded event or a property that can be used to switch states and show the chart once it's ready.

**Comment by joadan** [comment]
Hi,

Have you checked the events samples, https://apexcharts.github.io/Blazor-ApexCharts/events/chart-setup

**Comment by danielchalmers** [comment]
> Hi,
> 
> Have you checked the events samples, https://apexcharts.github.io/Blazor-ApexCharts/events/chart-setup

Wow, can't believe I missed that. Thank you so much!

**Comment by danielchalmers** [comment]
@joadan it does seem like there's some main thread blocking on phones


https://github.com/apexcharts/Blazor-ApexCharts/assets/7112040/95893ccd-3222-4002-91e6-60302227ec31

compared to desktop


https://github.com/apexcharts/Blazor-ApexCharts/assets/7112040/db788c62-8576-4d74-8e53-d4b031965c2b

have you seen this anywhere before?
