### ISSUE TITLE
Pie Chart component doesn't properly fit the parent container height when set to 100%

### ISSUE THREAD

**Issue by LukeConfait** [apexcharts/Blazor-ApexCharts#435]
Hi

I'm trying to get the pie chart to fill the parent container with the height set to 100% and the legend at the bottom. The container is resizable but seems to always have a fixed space at the bottom. 
![Screenshot 2024-03-20 120343](https://github.com/apexcharts/Blazor-ApexCharts/assets/86744792/e9527ca2-ad53-469a-8eeb-72a19c3785ef)
Looking in Dev tools it appears the chart and legend are rendered in this foreignObject while the parent svg component does take up the full size of the parent container.
![Screenshot 2024-03-20 121824](https://github.com/apexcharts/Blazor-ApexCharts/assets/86744792/0611905c-b5d4-4d6a-b8fa-c401216cf23d)
For reference my chart options are:

    ApexChartOptions<Tuple<decimal, string, string>> _chartOptions = new()
    {
        Chart = new Chart()
        {
            Height = "100%",
            Width = "100%",
        },
        PlotOptions = new PlotOptions
        {
            Pie = new PlotOptionsPie
            {
                DataLabels = new PieDataLabels
                {
                    Offset = -10,
                    MinAngleToShowLabel = 20,
                },
            }
        },
        DataLabels = new DataLabels
        {
            Style = new DataLabelsStyle
            {
                FontSize = "14px",
                FontWeight = 200,

            },
            Background = new DataLabelsBackground
            {
                Enabled = true,
                ForeColor = "#000000"

            },
            DropShadow = new DropShadow
            {
                Enabled = false
            }
        },
        Tooltip = new Tooltip
        {
            Y = new TooltipY { }
        },
        Legend = new Legend
        {
            Position = LegendPosition.Bottom,
            FontSize = "14px",
            HorizontalAlign = ApexCharts.Align.Center,
        }
    };

As far as I can tell this is specific to Blazor-ApexCharts after I tested it in this CodePen https://codepen.io/Luke-Confait/pen/OJGpyWd. 

Thanks

**Comment by joadan** [comment]
Hi,

I'm sorry but I don't think this is an issue in the wrapper.

You codepen is not matching you blazor sample code.
One tip is to set the debug flag on the component and then you can check the options sent to javascript in the browser console.

**Comment by LukeConfait** [comment]
Hi, 
Thanks for reply, I have updated the codepen and written some blazor code that should be roughly the same. After updating it I am now seeing the behavior on the apex charts js side as well. So it would appear it is actually an issue on that end after all.
This is how it looks on the codepen, 
![image](https://github.com/apexcharts/Blazor-ApexCharts/assets/86744792/e981dc2f-bf62-41fa-9a4c-1346f7d952a4)

and this is how it looks in my blazor code.
![image](https://github.com/apexcharts/Blazor-ApexCharts/assets/86744792/efe687e2-f727-487d-b580-003fc5851b45)

```
@page "/testpage"
@using ApexCharts

<div style="height:200px; width:400px; border-width:2px; border:solid"> 
    <ApexChart TItem="Tuple<decimal, string>"
               Options="@_chartOptions"
               Debug="true">
        <ApexPointSeries TItem="Tuple<decimal, string>"
                         Items="@_data"
                         Name="Name"
                         SeriesType="@SeriesType.Pie"
                         YValue="@(e => e.Item1)"
                         XValue="@(e => e.Item2)"
                         ShowDataLabels="true"/>
    </ApexChart>
</div>

@code {
    List<Tuple<decimal, string>> _data = new()
    {
        Tuple.Create((decimal)44, "data1"),
        Tuple.Create((decimal)55, "data2"),
        Tuple.Create((decimal)13, "data2"),
        Tuple.Create((decimal)33, "data2"),
    };

    ApexChartOptions<Tuple<decimal, string>> _chartOptions = new()
        {
            Chart = new Chart()
            {
                Height = "100%",
            },

            Legend = new Legend
            {
                Position = LegendPosition.Bottom,
                FontSize = "14px",
                HorizontalAlign = ApexCharts.Align.Center,
            }
        };
}
```

**Comment by joadan** [comment]
Hi,

If you believe this is an issue in apexcharts.js you should raise an issue in that repo.
Thank you,
