### ISSUE TITLE
[Bug] TooltipHoverFormatter is deserialized as a string, resulting in a "not a function" error when using shared tooltips

### ISSUE THREAD

**Issue by SparkyTD** [apexcharts/Blazor-ApexCharts#449]
When specifying a custom tooltip formatter using `ApexChartOptions<T>.Legend.TooltipHoverFormatter`, the browser throws an exception when the user tries to hover over the area chart, as it tries to call a string like a function. 

The problem comes from `blazor-apexcharts.js` that has [custom logic](https://github.com/apexcharts/Blazor-ApexCharts/blob/master/src/Blazor-ApexCharts/wwwroot/js/blazor-apexcharts.js#L424) for evaluating function-like string parameters coming from .NET, but it doesn't include TooltipHoverFormatter. I think the solution is as simple as adding ` || key === 'tooltipHoverFormatter'` at the end of that if statement.

**Comment by joadan** [comment]
>  I think the solution is as simple as adding ` || key === 'tooltipHoverFormatter'` at the end of that if statement.

Yes, that is correct
