### ISSUE TITLE
BUG Creating a chart in a MudBlazor Dialog (modal)

### ISSUE THREAD

**Issue by RHaughton** [apexcharts/Blazor-ApexCharts#454]
I get a null reference exception when trying to create a chart in a mudBlazor Dialog. When I open the same component in a single page I get no issue at all.
I have no idea where to look to fix this issue?

**Comment by joadan** [comment]
Hi,

I'm sorry but I don't know MudBlazor that well.
Do you think it's possible for you to provide a minimal repo to reproduce the issue.
