### ISSUE TITLE
How to remove or hide the points on a line?

### ISSUE THREAD

**Issue by dineshjethoe** [apexcharts/Blazor-ApexCharts#455]
Hi there,
How can I get rid of those circles on the line? I have set the Marker size to 0 but that does not help. 
See screenshot.
![yOhvPbwEwz](https://github.com/apexcharts/Blazor-ApexCharts/assets/21182176/7c2d50b3-3efe-424d-b7b8-7d02ef2c443d)

**Comment by joadan** [comment]
Hi,

Are you using custom tooltips? If so the markers are required for the custom tooltip to work.
If that is not acceptable please use a javascript tooltip instead.

**Comment by dineshjethoe** [comment]
I got it working by removing the PointColor property from the ApexPointSeries with 'SeriesType="@SeriesType.Line"', 👍 . I had to use the PointColor  for the _Bars_ only.
