### ISSUE TITLE
Null Value

### ISSUE THREAD

**Issue by DBESSIERE** [apexcharts/Blazor-ApexCharts#46]
Hi and thanks for this blazor ApexCharts.js wrapper.
According the documentation : 
    /// And according to the demos, data can contain null.
    /// https://apexcharts.com/javascript-chart-demos/line-charts/null-values/
but unfortunatly this is not the case.
Do you expect to support null YValue in the future?
Thanks again for your work.

**Comment by joadan** [comment]
Hi,

This is looks like a bug, we should support null values. 
Let me take a look

**Comment by joadan** [comment]
please check, https://apexcharts.github.io/Blazor-ApexCharts/line-charts#null%20values 
this will be available in a new release in a couple of days

**Comment by DBESSIERE** [comment]
Thanks so much

**Comment by joadan** [comment]
Fixed in v0.7.0-beta
