### ISSUE TITLE
Show Y value on the pie sector

### ISSUE THREAD

**Issue by BekAllaev** [apexcharts/Blazor-ApexCharts#463]
Hey guys. 
Is it possible to show Y value on the pie chart secotr?

For example, on this chart we can see how much space some sector(in percentage) takes.

![image](https://github.com/apexcharts/Blazor-ApexCharts/assets/37025308/8af8acbf-dc98-4399-a3f3-10a4bbb6cb19)

You can see that I hovered mouse over USA and it shows value - 122. So instead of percentages on the sector I want to show number 122.
Thanks!

**Comment by joadan** [comment]
Hi I have added a sample, https://apexcharts.github.io/Blazor-ApexCharts/pie-charts#label%20formatter
