### ISSUE TITLE
OnLegendClicked being triggered only when clicking on the first element in the legend

### ISSUE THREAD

**Issue by Vunlinur** [apexcharts/Blazor-ApexCharts#464]
Description:
The OnLegendClicked event is triggered only when clicking on the first element in the legend. Any subsequent elements do not trigger this event.
Occurs at least for Pie and Donut charts. Not tested for other chart types.

Repro Steps:
1. Create a Donut or a Pie chart with more than 1 element in the data series.
2. Subscribe to the OnLegendClicked event.
3. Click on each element in the legend while monitoring that event.

Result:
Notice that only clicking on the first element triggers OnLegendClicked

**Comment by Vunlinur** [comment]
Update:
I just managed to inject my own callback directly into the wrapped JS, thinking it's something on the wrapper's side, but the new behavior is exactly the same.

**Comment by joadan** [comment]
This will be fixed in the next version, sample here, https://apexcharts.github.io/Blazor-ApexCharts/events/legend-click#no%20axis%20chart

**Comment by joadan** [comment]
Fixad in 3.5
