### ISSUE TITLE
System.NullReferenceException is thrown on Page load

### ISSUE THREAD

**Issue by mmaestro16** [apexcharts/Blazor-ApexCharts#465]
I am facing issues with version 3.3. 

When I come to the page it throws an exception 

`
ExceptionType: System.NullReferenceException
Exception: Object reference not set to an instance of an object.
`

If I click ob button TEST then it reloads sometimes and gets data, but not all the times properly.

A lot of times I get that chart
![image](https://github.com/apexcharts/Blazor-ApexCharts/assets/170923545/92fd80e2-81dd-44e1-b5d0-2aff906f0219)

Expected behaviour is this case
![image](https://github.com/apexcharts/Blazor-ApexCharts/assets/170923545/9bc005f1-fed3-4c5b-a4ba-7641c859c277)

If I press F5 to refresh site I get this + an exception
![image](https://github.com/apexcharts/Blazor-ApexCharts/assets/170923545/8bd71349-e926-4966-a987-3aadb10757e1)

This is the code where you are able to reproduce all the issues.

`@page "/test"

<button class="btn btn-primary" @onclick="@(() => ReadTObjects())" > TEST </button>

<br />
<br />

<div style="overflow-x: auto;">
    <div class="d-flex" style="height: 400px; min-width: 500px">
        <div class="chart">
            <ApexChart @ref="departmentFinishedChart" 
                        TItem="TestObject"
                        Title="By departments"
                        Options="departmentFinishedOptions" >

                <ApexPointSeries TItem="TestObject"
                                    Items="departmentFinished"
                                    Name="Finished"
                                    SeriesType="SeriesType.Bar"
                                    XValue="@(x => x.Department)"
                                    YAggregate="@(x => x.Sum(y => (decimal)y.Count))" />
            </ApexChart>

        </div>
        <div class="chart">
            <ApexChart @ref="categoryFinishedChart"
                        TItem="TestObject"
                        Title="By categories"
                        Options="categoryFinishedOptions">

                <ApexPointSeries TItem="TestObject"
                                    Items="categoryFinished"
                                    Name="Finished"
                                    SeriesType="SeriesType.Bar"
                                    XValue="@(x => x.Department)"
                                    YAggregate="@(x => x.Sum(y => (decimal)y.Count))" />
            </ApexChart>
        </div>
    </div>
</div>

@code {
    IEnumerable<Object1> objectList = new List<Object1>();
    IEnumerable<TestObject> combinedGroup = new List<TestObject>();

    List<TestObject> departmentFinished = new();
    ApexChartOptions<TestObject> departmentFinishedOptions = new();
    ApexChart<TestObject> departmentFinishedChart = new();

    List<TestObject> categoryFinished = new();
    ApexChartOptions<TestObject> categoryFinishedOptions = new();
    ApexChart<TestObject> categoryFinishedChart = new();

    protected override async Task OnInitializedAsync()
    {
    }

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            await ReadTObjects();
        }
    }

    private async Task ReadTObjects()
    {
        GetData();

        PrepareDataByDepartment();
        PrepareDataByCategory();

        UpdateCharts();
    }

    private void GetData()
    {
        objectList = new List<Object1>();
        objectList = objectList.Append(new Object1()
        {
            Department = "Department 1",
            Category = "Category 1",
            CompletitionDate = DateTime.Now
        });

        objectList = objectList.Append(new Object1()
        {
            Department = "Department 1",
            Category = "Category 2",
            CompletitionDate = DateTime.Now
        });

        objectList = objectList.Append(new Object1()
        {
            Department = "Department 1",
            Category = "Category 3",
            CompletitionDate = DateTime.Now
        });

        objectList = objectList.Append(new Object1()
        {
            Department = "Department 2",
            Category = "Category 1",
            CompletitionDate = DateTime.Now
        });

        objectList = objectList.Append(new Object1()
        {
            Department = "Department 2",
            Category = "Category 2",
            CompletitionDate = DateTime.Now
        });

        objectList = objectList.Append(new Object1()
        {
            Department = "Department 3",
            Category = "Category 3",
            CompletitionDate = DateTime.Now
        });

        objectList = objectList.Append(new Object1()
        {
            Department = "Department 3",
            Category = "Category 1",
            CompletitionDate = DateTime.Now
        });

        objectList = objectList.Append(new Object1()
        {
            Department = "Department 4",
            Category = "Category 2",
            CompletitionDate = DateTime.Now
        });
    }

    private void PrepareDataByDepartment()
    {
        var completionGroup = objectList.OrderBy(x => x.Department)
                                        .ThenBy(x => x.CompletitionDate?.Month)
                                        .GroupBy(x => (x.Department, (int?)x.CompletitionDate?.Month))
                                        .Where(g => g.Key.Item2.HasValue) // Remove null months
                                        .ToList();

        var convertedCompletionGroup = ConvertToTestObject(completionGroup);

        combinedGroup = convertedCompletionGroup;

        departmentFinished = convertedCompletionGroup
            .GroupBy(group => group.Department) // Group by department
            .Select(group => new TestObject
                {
                    Department = group.Key,
                    Month = 0, 
                    Count = group.Sum(g => g.Count), // Summing up the counts
                })
            .OrderByDescending(x => x.Count)
            .ToList();

        StateHasChanged();
    }

    private void PrepareDataByCategory()
    {
        // Group kaizenList by department and completition month
        var completionGroup = objectList.OrderBy(x => x.Category)
                                        .ThenBy(x => x.CompletitionDate?.Month)
                                        .GroupBy(x => (x.Category, (int?)x.CompletitionDate?.Month))
                                        .Where(g => g.Key.Item2.HasValue) // Remove null months
                                        .ToList();

        // Convert entryGroup and completionGroup to KaizenGroup
        var convertedCompletionGroup = ConvertToTestObject(completionGroup);

        categoryFinished = convertedCompletionGroup
            .GroupBy(group => group.Department) // Group by department
            .Select(group => new TestObject
                {
                    Department = group.Key,
                    Month = 0,
                    Count = group.Sum(g => g.Count), // Summing up the counts
                })
            .OrderByDescending(x => x.Count)
            .ToList();

        StateHasChanged();
    }

    private IEnumerable<TestObject> ConvertToTestObject(IEnumerable<IGrouping<(string, int?), Object1>> groups)
    {
        return groups.Select(group => new TestObject
            {
                Department = group.Key.Item1,
                Month = group.Key.Item2.HasValue ? group.Key.Item2.Value : default, 
                Count = group.Count(),
            });
    }

    #region Charts

    async void UpdateCharts()
    {
        try
        {
            departmentFinishedOptions = SetChartOptions();
            categoryFinishedOptions = SetChartOptions();

            //await departmentFinishedChart.UpdateOptionsAsync(redrawPaths: true, animate: true, updateSyncedCharts: true);
            await departmentFinishedChart.UpdateSeriesAsync();
            //this solves error: Object reference not set to an instance of an object.
            //but we get flashing effect 
            //await Task.Delay(100);
            await departmentFinishedChart.RenderAsync();

            //await categoryFinishedChart.UpdateOptionsAsync(redrawPaths: true, animate: true, updateSyncedCharts: true);
            await categoryFinishedChart.UpdateSeriesAsync();
            await categoryFinishedChart.RenderAsync();

            StateHasChanged();
        }
        catch (Exception e)
        {
            //         logger.LogError($@"Failed to update chart | {nameof(TObjectStats)} | {nameof(UpdateCharts)} |
            // ExceptionType: {e.GetType()}
            // Exception: {e.Message}
            // StackTrace: {e.StackTrace}");
        }
    }

    public ApexChartOptions<TestObject> SetChartOptions()
    {
        var options = new ApexChartOptions<TestObject>
            {
                Xaxis = new XAxis
                {
                    Labels = new XAxisLabels
                    {
                        Style = new AxisLabelStyle
                        {
                            FontSize = "11px"
                        }
                    }
                },
                Title = new Title
                {
                    Align = ApexCharts.Align.Center,
                    Style = new TitleStyle
                    {
                        FontSize = "18px",
                        FontWeight = 100
                    }
                },
                Chart = new Chart
                {
                    Toolbar = new Toolbar
                    {
                        Show = false
                    },
                    Stacked = true,
                    Height = "100%",
                },
                PlotOptions = new PlotOptions
                {
                    Bar = new PlotOptionsBar
                    {
                        ColumnWidth = "40%",
                        Horizontal = false,
                        DataLabels = new PlotOptionsBarDataLabels
                        {
                            Total = new BarTotalDataLabels
                            {
                                Style = new BarDataLabelsStyle
                                {
                                    FontWeight = "600",
                                    Color = "#FFFFFF"
                                },
                                Formatter = @"function (value){return parseFloat(value).toLocaleString('" + CultureInfo.CurrentCulture.Name + "');}"
                                // Formatter = @"function(value, opts) {return Math.round(Number(value));}"
                            }
                        },
                    },
                },
                DataLabels = new DataLabels
                {
                    Background = new DataLabelsBackground
                    {
                        ForeColor = "#000000",
                    }
                },
                Colors = new List<string>() { "#1B6EC2" }
            };

        options.Yaxis = new List<YAxis>();
        options.Yaxis.Add(new YAxis
            {
                Labels = new YAxisLabels
                {
                    Formatter = @"function (value){return parseFloat(value).toLocaleString('" + CultureInfo.CurrentCulture.Name + "');}"
                }
            });

        return options;
    }

    #endregion

    public class TestObject()
    {
        public string Department { get; set; }
        public int Month { get; set; }
        public int Count { get; set; }
    }

    public class Object1()
    {
        public string Department { get; set; } = string.Empty;
        public string Category { get; set; } = string.Empty;
        public DateTime? CompletitionDate { get; set; }
    }
}

`

**Comment by mmaestro16** [comment]
Additionally I have an question how to get rid off those horizontal lines.
I tried a lot of different things but without any success.

![image](https://github.com/apexcharts/Blazor-ApexCharts/assets/170923545/13d82684-ba96-4da0-9191-7009454b8f67)

**Comment by itniels** [comment]
I am also seeing a lot of issues with rendering the chart on page load etc, no matter how I check if my chart reference is null, it isn't but ApexCharts throws exception with null ref and does not render the chart.

I have tried to run both `.RenderAsync()` and `.UpdateSeriesAsync(false)` in a for-loop with try-catch, but still it does not render even with no exceptions, so very hard to do a consistent page load where data can take time to load in.

**Comment by ShahryarSaljoughi** [comment]
Calling `StateHasChanged()` before using `UpdateSeriesAsync()` solved the problem for me.
The sample code in official docs does that too.  
Sample is here: https://apexcharts.github.io/Blazor-ApexCharts/features/chart-data
