### ISSUE TITLE
Series state refreshes on UpdateSeriesAsync

### ISSUE THREAD

**Issue by RagnarSmari** [apexcharts/Blazor-ApexCharts#469]
When I hide a series from a chart and then call UpdateSeriesAsync() the series that was hidden now shows. Is there some way to maintain the hidden state after updating series?

I have chart with a couple series and user can hide/show them but I still want to update the data of the hidden series in the background.
Just a problem for the users that when a series is updated, all the hidden series are now showing.

**Comment by joadan** [comment]
Hi,

I'm sorry I don't think it is possible in apexcharts.js
