### ISSUE TITLE
Feature Request: Timeline Charts

### ISSUE THREAD

**Issue by hannahihayes** [apexcharts/Blazor-ApexCharts#470]
Hi,

I was just wondering if there was any plan to add in the ApexCharts.js timeline/range-bar charts any time in the future?

Thanks.

**Comment by joadan** [comment]
Hi,

This should be supported, please check https://apexcharts.github.io/Blazor-ApexCharts/rangebar-charts

**Comment by hannahihayes** [comment]
Apologies, I must have missed that. Thank you for pointing me in the right direction.
