### ISSUE TITLE
how to multi-axis?

### ISSUE THREAD

**Issue by HarvieKrumpet** [apexcharts/Blazor-ApexCharts#474]
I find your chart system the cleanest way to run advanced charts in blazor. including having pan and zoom. but I havent been able to combine a bar and line chart such that they both have independent y axis scales. I know its in the native charting api. but I am not understanding how to do this purely from the blazor client side. I do run code-behind with a reference to it if that helps. For instance barchart being volume of a stock and line being the price

I also want to additionally add markers that are scaled with the line chart but independent of the y ticks. for instance, the markers would indicate past buy/sell orders.

**Comment by joadan** [comment]
Hi,

Have you checked samples at https://apexcharts.github.io/Blazor-ApexCharts/features/axis

**Comment by joadan** [comment]
Clean up
