### ISSUE TITLE
Legends on graph with huge data

### ISSUE THREAD

**Issue by psharma-stfc** [apexcharts/Blazor-ApexCharts#475]
Hi, Thank you! this project is incredible and has greatly simplified graph integrations.

My graph contains four series, each with approximately 16,000 points, and the entire dataset refreshes every second. I am trying to add a legend to it, but due to the large amount of data, clicking on the legend to toggle a series makes the graph unresponsive, causing memory usage to spike to 100% and crash.

Do you have any suggestions how to fix this?

So far I have tried: 1. Default functionality 2. Custom -Hide/Show on some checkbox click.

**Comment by joadan** [comment]
Hello,

Apexcharts.js is svg based, this means that all objects, datapoints, labels etc are svg nodes. 
If you have to many objects (nodes) then it just to much for the browser to handle.
Check the sample https://apexcharts.github.io/Blazor-ApexCharts/features/performance to get a understanding on the limitations.

**Comment by psharma-stfc** [comment]
I understand, thank you for replying!
