### ISSUE TITLE
ApexCharts is not defined

### ISSUE THREAD

**Issue by OrionRiftStudios** [apexcharts/Blazor-ApexCharts#49]
I am using Blazor Server with NET 6 I followed the instructions but I am getting this error

ReferenceError: ApexCharts is not defined
    at Object.renderChart (https://localhost:5001/_content/Blazor-ApexCharts/js/blazor-apex-charts.js:195:9)
    at https://localhost:5001/_framework/blazor.server.js:1:3501
    at new Promise (<anonymous>)
    at Tt.beginInvokeJSFromDotNet (https://localhost:5001/_framework/blazor.server.js:1:3475)
    at https://localhost:5001/_framework/blazor.server.js:1:71773
    at Array.forEach (<anonymous>)
    at Tt._invokeClientMethod (https://localhost:5001/_framework/blazor.server.js:1:71759)
    at Tt._processIncomingData (https://localhost:5001/_framework/blazor.server.js:1:69801)
    at bt.Tt.connection.onreceive (https://localhost:5001/_framework/blazor.server.js:1:64201)
    at WebSocket.o.onmessage (https://localhost:5001/_framework/blazor.server.js:1:48517)

and here is the the razor component 

```
 <ApexChart Title="Profit Flow" TItem="ProfitModel">
                          <ApexPointSeries
                           TItem="ProfitModel"
                           Items="Profits"
                           XValue="@(e=> e.Category)"
                           YAggregate="@(e=> e.Sum(e=> e.Profit))"
                          ></ApexPointSeries> 

                       </ApexChart>

```

I added ApexCharts in the _imports.razor
in the host file 

    <script src="_content/Blazor-ApexCharts/js/apex-charts.min.js"></script>
    <script src="_content/Blazor-ApexCharts/js/blazor-apex-charts.js"></script>
    <script src="_framework/blazor.server.js"></script>

do you know if I am missing something?

I checked the examples but I could not find anything different.

 Thank you!

**Comment by joadan** [comment]
Looks ok to me.. 

Give me a couple of hours and I will look into it.

**Comment by OrionRiftStudios** [comment]
Thank you so much!

**Comment by joadan** [comment]
Hello,

Looks like in Net 6 you should put the javascript references in the _Layout.cshtml file.

Put this just before that blazor.server.js 

 **<script src="_content/Blazor-ApexCharts/js/apex-charts.min.js"></script>**
 **<script src="_content/Blazor-ApexCharts/js/blazor-apex-charts.js"></script>**
 <script src="_framework/blazor.server.js"></script>

I created a new sample repo, https://github.com/joadan/BlazorApexChartsDotNet6

**Comment by OrionRiftStudios** [comment]
Thank you let me check

**Comment by OrionRiftStudios** [comment]
I tested your example and myself and it is working with blazor server.

In my project I am using MudBlazor  and I got the issue I posted before.

I created a new project using the Mudblazor template  and the this library is not working with MudBlazor I don't know exactly why. 
Thank you for taking time for this.

**Comment by OrionRiftStudios** [comment]
I fixed the issue pasting in the _host file this.
    <script src="_content/Blazor-ApexCharts/js/apex-charts.min.js"></script>
    <script src="_content/Blazor-ApexCharts/js/blazor-apex-charts.js"></script>
