### ISSUE TITLE
Problem with multiaxis

### ISSUE THREAD

**Issue by CavalornGothic** [apexcharts/Blazor-ApexCharts#491]
I have a problem using Apex with a connection to Blazor. When I add two Y-axes, one has Min,Max in the range of -20000 to 20000 and the other has 0 to 100, then the series from 0-100 is spreading on the graph, can this be fixed somehow? Is configuring something wrong ? I send two pictures and code with settings

![apex](https://github.com/user-attachments/assets/63e25bbc-ff19-4f89-920d-0887427595fe)
![apex2](https://github.com/user-attachments/assets/69f67dd1-a83d-4aae-a485-11d429ee3737)
[code.zip](https://github.com/user-attachments/files/16348728/code.zip)

**Comment by joadan** [comment]
Hi,

Have you checked the samples, https://apexcharts.github.io/Blazor-ApexCharts/features/axis

**Comment by joadan** [comment]
Clean up
