### ISSUE TITLE
StackType.Percent100 seems to have stopped working

### ISSUE THREAD

**Issue by jbaumflek** [apexcharts/Blazor-ApexCharts#496]
I last updated my local repo in Nov, 23.  I just pulled the latest, and a report I have using the stacked bar chart, with StackType.Percent100 is no longer working.  The three series are overlaying one another.  Any suggestions for other options that might interfere with the stack working properly?

**Comment by joadan** [comment]
Hi 

Not sure what could be the problem here.
But it looks like the sample works, https://apexcharts.github.io/Blazor-ApexCharts/bar-charts#stacked%20100%
