### ISSUE TITLE
Responsive options are not working in Blazor-ApexCharts

### ISSUE THREAD

**Issue by priyanka0102** [apexcharts/Blazor-ApexCharts#499]
Responsive options are not working in Blazor-ApexCharts. I have tried javascript documentation but it is not working in blazor. Also not getting any example of responsive for Blazor Apex Chart.

**Comment by joadan** [comment]
I'll look into this now

**Comment by joadan** [comment]
demo: https://apexcharts.github.io/Blazor-ApexCharts/features/responsive
Please note, not yet released

**Comment by joadan** [comment]
fixed in Release v3.5.0
