### ISSUE TITLE
Working with large amount of data freezes the app

### ISSUE THREAD

**Issue by SSenshi147** [apexcharts/Blazor-ApexCharts#50]
Hi there!

First off thank you for your work, I find ApexCharts amazing, and it's very nice to be able to use it in Blazor.

My problem is with the handling of large amount of data. I'm trying to draw a chart which consists of ~10000 X-Y key-value pairs, however this amount simply makes the entire app (I'm working in WebAssembly) unusable for a good 10-15 seconds, and even after it loads, it's still very slow.

My question is whether there's any solution for this problem; for example not rendering all the points, only every N-th one (at 10k points this would still make a nice chart I think), or loading the values dynamically, not all of them at the same time, etc.

Thank you!

**Comment by SSenshi147** [comment]
Edit: as it can be seen at [ApexCharts](https://apexcharts.com/features/) it should be able to handle this much data.

**Comment by joadan** [comment]
Hi, 

I'm looking into this now, looks like serializing is slow.
I have made some test but I have not yet found the core issue.

There will always be an overhead compare to pure javascript, we have to serialize the data and then send it via interop to javascript also running in WASM will add some extra overhead, unless you run AOT.

You could prepare the data before sending the chart to reduce the number of datapoints, that for sure would speed it up.

I'll continue to troubleshoot.

**Comment by joadan** [comment]
I have made some changes please take a look here, https://apexcharts.github.io/Blazor-ApexCharts/features/performance 
This is probably the numbers we should expect, at least for now.
10 000 points render in a second

This is not released I still have some more work to do.

**Comment by SSenshi147** [comment]
Wow, this looks promising!
Thank you!

**Comment by joadan** [comment]
Fixed in 0.8.0-beta
