### ISSUE TITLE
Blazor Apex Charts not working in Server Side Render

### ISSUE THREAD

**Issue by genifycom** [apexcharts/Blazor-ApexCharts#500]
Create a standard Blazor Web App with interactive mode None (i.e. Server Side Rendering only). Use .Net 8.

Add a new page with one of the Apex samples on it.

The page opens without error but the Apex Charts does not show.

**Comment by joadan** [comment]
Hi, 
You are correct blazor-apexcharts requires interactivity.
This is part of the documentation:

### .NET 8
If you are on .NET 8 you need to set the rendermode to Interactive.
*Interactive Server, Interactive WebAssembly or Interactive Auto*
