### ISSUE TITLE
Accessing the method highlightSeries programmatically

### ISSUE THREAD

**Issue by bradleykeith** [apexcharts/Blazor-ApexCharts#504]
Hi!

Is there currently any way to access the highlight series method or any work arounds to be able to use this functionality? 

Thanks!

**Comment by joadan** [comment]
The HighlightSeries method was added in apexcharts.js 3.53.0 that was released yesterday. I have added support for it in the wrapper and it will be in the next release.

**Comment by joadan** [comment]
Demo here: https://apexcharts.github.io/Blazor-ApexCharts/methods/highlight-series

**Comment by bradleykeith** [comment]
Perfect, thank you!
