### ISSUE TITLE
The custom colors in the legend of the heat map do not correspond to the configured colors

### ISSUE THREAD

**Issue by e271** [apexcharts/Blazor-ApexCharts#505]
Hallo. I just noticed this.

This can be seen on the examples of Blazor ApexCharts:
![image](https://github.com/user-attachments/assets/dee334bc-7a69-4834-b372-117ca86b7b91)

The graphic itself is correct. It's only a problem with the legends colors.

https://apexcharts.github.io/Blazor-ApexCharts/heatmap-charts

**Comment by joadan** [comment]
Thank you, fixed
