### ISSUE TITLE
UpdateSeries method doesn't work in combination with InvokeAsync(StateHasChanged)

### ISSUE THREAD

**Issue by compScienceFan** [apexcharts/Blazor-ApexCharts#51]
Hi!

Really like your work, wrapper worked like a charm so far. But I think I've found a bug.
I am using UpdateSeries method in a timer callback and everything works fine. But when I also add InvokeAsync(StateHasChanged) to callback (to update UI), chart doesn't update anymore. It is also worth mentioning that when I remove Options parameter from ApexChart component UpdateSeries works again.

Sample code (Blazor Server, .NET 5):

```
@using ApexCharts;
@using System.Timers
@implements IDisposable

<input @bind-value="text" />

@*remove Options and UpdateSeries() will work with InvokeAsync(StateHasChanged)*@
<ApexChart @ref="chart" Height="400" Width="600" TItem="Data" Options="Data.GetOptions()">
    <ApexPointSeries SeriesType="SeriesType.Bar"
                     TItem="Data" Items="dataList"
                     XValue="@(data => "xVal")" YValue="@(data => data.Value)" />
</ApexChart>

@code {
    class Data
    {
        public int Value { get; set; }

        static Random random = new();
        public static ApexChartOptions<Data> GetOptions()
        {
            ApexChartOptions<Data> options = new();
            options.Yaxis = new() { new() { Min = 0, Max = 50 } };
            return options;
        }

        public Data()
        {
            Value = random.Next(1, 30);
        }

        public void Update()
        {
            Value = random.Next(1, 30);
        }
    }

    List<Data> dataList = new();

    ApexChart<Data> chart;

    string text = "text";

    private bool timerInitialized;
    private Timer timer;

    protected override void OnInitialized()
    {
        for (int i = 0; i < 5; i++)
        {
            dataList.Add(new());
        }
    }

    protected override void OnAfterRender(bool firstRender)
    {
        if (firstRender && !timerInitialized)
        {
            timerInitialized = true;
            timer = new Timer(2000);
            timer.Elapsed += async delegate { await UpdateChartSeries(); };
            timer.Enabled = true;
        }
    }

    private async Task UpdateChartSeries()
    {
        foreach (var data in dataList)
        {
            data.Update();
        }

        text = dataList[0].Value.ToString();
        await InvokeAsync(() => StateHasChanged()); // comment this line for UpdateSeries() to work again

        await chart.UpdateSeries();
    }

    public void Dispose()
    {
        timer?.Stop();
        timer = null;
    }
}
```

**Comment by joadan** [comment]
Hi,

Thank you for reporting. I'm working on a preformance issue right now, but I'll look at this as soon as I can.

**Comment by joadan** [comment]
Hello, 

I added this sample to, https://apexcharts.github.io/Blazor-ApexCharts/bar-charts#dynamic%20update
I can't reproduce the error in either WASM or Server mode.

Please note that I have made some changes, but I can't really see why it should make a difference.

Good to know is that in the new version there is a breaking change: All async Methods are now prefixed with Async.
For example: chart.UpdateSeries() will be chart.UpdateSeriesAsync();

I will release the new version during the weekend.

**Comment by compScienceFan** [comment]
Maybe UpdateSeriesAsync makes the difference. Or is it just a name change? I will test the program again, when you release the new version.

If I knew you were going to add my sample to your website, I would have written a prettier one as it has some things hardcoded :)

**Comment by joadan** [comment]
It should be just a name change,  I have changed som other stuff, but I can see how that would affect this.
My plan was to improve sample you send but I wanted to change as little as possible to test your issue.

If you like you can make a pull request to improve samples, that is much apricated.

**Comment by compScienceFan** [comment]
Great job with the update, now it works fine, so you can close this issue.

Your samples look pretty good, so I don't think they need updating. Also you already have dynamic update sample at [https://apexcharts.github.io/Blazor-ApexCharts/methods/update-series], so you could remove my sample.

Otherwise if I find some extra time, I could try to add some samples.
