### ISSUE TITLE
Introduce ChartService

### ISSUE THREAD

**Issue by joadan** [apexcharts/Blazor-ApexCharts#518]
We should add a optional  ChartService  that that would:

- Make it possible to pre load javascript files
- Make it possible to set Global Options
- Keep track of all rendered charts so it's possible to re-render 
- Make Localization more straight forward by using the global options
- Make it possible to have an auto localize function  (under investigation)

Work has started in branch https://github.com/apexcharts/Blazor-ApexCharts/tree/add-chart-service 

Ambition is to make this without any breaking changes but it will be release in a new major version.

**Comment by mjacob2** [comment]
hi there! 'IServiceCollection' does not contain a definition for 'AddApexCharts' and no accessible extension method 'AddApexCharts' accepting a first argument of type 'IServiceCollection' could be found (are you missing a using directive or an assembly reference?) I see in V 3.5 there is no service available?

**Comment by joadan** [comment]
Hi,

This is not yet released. It will be part of next major version 4.0.

**Comment by mjacob2** [comment]
I see. I wouldn't have to bother you with this question if such a note appeared here: https://apexcharts.github.io/Blazor-ApexCharts/chart-service :)

**Comment by joadan** [comment]
Fixed in 4.0
