### ISSUE TITLE
A Virus?

### ISSUE THREAD

**Issue by twojnarowski** [apexcharts/Blazor-ApexCharts#520]
Since yesterday, Eset Endpoint Security started showing me an alert about Blazor ApexCharts nuget.
Here are the details:
\.nuget\packages\blazor-apexcharts\3.4.0\lib\net6.0\Blazor-ApexCharts.dll;
Suspicious Object;
Cured by deleting;
Event occurred while trying to access file by using: C:\Windows\explorer.exe;

**Comment by joadan** [comment]
Hi, not sure what could be the issue here. 
Do you have any more details?

**Comment by twojnarowski** [comment]
I am also not sure and I don't have more details. Maybe ESET had a false positive. Nothing else happened after that one alert. Just wanted

**Comment by henkmollema** [comment]
I've the same problem Only with version 3.4.0 and .NET 6. Other versions and TFM's are fine.

**Comment by joadan** [comment]
Clean up
