### ISSUE TITLE
Cannot get charts to work as components

### ISSUE THREAD

**Issue by AlexW68** [apexcharts/Blazor-ApexCharts#541]
This was all working pre .net 8, absolutely sure it's something to do with interactive mode.

This is a Blazor Server project, all other components are working fine, I use MudBlazor as the main framework component.

The master layout page has the following.

```
<MudThemeProvider Theme="@this.currentTheme"
                  IsDarkMode=@userPreferenceService.DarkMode
                  DefaultScrollbar=true @rendermode="new InteractiveServerRenderMode()"/>
<MudPopoverProvider/>
<MudDialogProvider @rendermode="new InteractiveServerRenderMode()"/>
<MudSnackbarProvider @rendermode="new InteractiveServerRenderMode()"/>

```

If I create a blazor page with the chart it works as expected. 

What is not working is the chart as a component, it's not calling any of the event handlers and not displaying anything at all.

Page with the component embedded in it has 

`@rendermode InteractiveServer`

near the top

then in the page

`<DemoChart/>`

It does not work as a component.

I am clearly missing something; any help would be great.

**Comment by VaclavElias** [comment]
Not sure if it is related. Check your browser console for errors. I upgraded from `3.5.0` to `4.0.0` and had many errors.

Not sure what was the cause, but I had to provide chart id for all my Blazor components.

```html
<ApexChart TItem="IdNameDto"
                           Height="Height"
                           Options="ChartOptionsFactory.CreateSemiDonutChartOptions(Color, Id)"
                           @ref="_chart">
                    <ApexPointSeries TItem="IdNameDto"
                                     Items="Data"
                                     Name="Gross Value"
                                     SeriesType="SeriesType.Donut"
                                     XValue="@(e => e.Name)"
                                     YValue="@(e => e.Id)" />
                </ApexChart>
```

```csharp
    public static ApexChartOptions<IdNameDto> CreateSemiDonutChartOptions(string color, string id)
    {
        var options = new ApexChartOptions<IdNameDto>()
        {
            Chart = new()
            {
                ParentHeightOffset = -50,
                Sparkline = new() { Enabled = true },
                Width = "100%",
                Id = id,
            },
            Colors = [color, "#EEEEEE"],
            PlotOptions = new PlotOptions
            {
                Pie = new PlotOptionsPie
                {
                    StartAngle = -90,
                    EndAngle = 90,
                }
            }
        };

        return options;
    }
```

**Comment by AlexW68** [comment]
Thank you for the reply, I don't get any errors in the console at all, I tried to work out your code and could not work out ID (or Color), but it did not work sadly even hacking Id and Color with any values.

if I put the @page "/myurl" at the top it works perfectly as a page, just not as a component.

I am going to fire up the original ApexCharts js stuff to see if that works I had that running well in a project a while back.

thanks again.

**Comment by joadan** [comment]
Clean up
