### ISSUE TITLE
Global Options Error

### ISSUE THREAD

**Issue by salgaard** [apexcharts/Blazor-ApexCharts#543]
**Hello! i have an error when i try to add global options:**

![image](https://github.com/user-attachments/assets/0529abbb-e0f1-48b9-a3b9-b9926d16dd87)

It works great when i dont add any options.

**this is the error:**

![image](https://github.com/user-attachments/assets/05504282-c9e5-4500-b6eb-d3ca164320c8)
![image](https://github.com/user-attachments/assets/e921dfa7-9a0a-45c2-bff7-34fe938aa2f4)

**my setup:**

blazor web app .net 8

![image](https://github.com/user-attachments/assets/c10c1eed-4e2d-408c-9c33-20048b8d05b1)

i use mudblazor component library

i have @using ApexCharts in _imports.razor

i have nuget: "Blazor-ApexCharts" Version="4.0.0"

**Comment by PVNagel** [comment]
+1

**Comment by salgaard** [comment]
this is my solution right now:

 public static Theme GetTheme => new Theme { Mode = Mode.Dark, Palette = PaletteType.Palette1 };

then adding Options to each chart:
<ApexChart TItem="ElspotPrice" Options="new ApexChartOptions<ElspotPrice>{ Theme = GetTheme }" >

**Comment by joadan** [comment]
Hello,

Make sure you have cleaned your solution, also good to delete bin and obj folders. 
Make sure you are not running a cached javascript version.

**Comment by joadan** [comment]
Hi, has this been resolved?

**Comment by salgaard** [comment]
> Hi, has this been resolved?

im sorry, i will go test it right now!

**Comment by salgaard** [comment]
> Hello,
> 
> Make sure you have cleaned your solution, also good to delete bin and obj folders. Make sure you are not running a cached javascript version.

It worked! thank you very much :)
