### ISSUE TITLE
Request to support for Treemap https://apexcharts.com/docs/chart-types/treemap-chart/

### ISSUE THREAD

**Issue by yashshah7575** [apexcharts/Blazor-ApexCharts#547]
Hi, 

Thank you for creating this library it is pretty awesome. I hope to contibute to this code base in some freetime. 

Is there a plan to add Tree map chart?

https://apexcharts.com/docs/chart-types/treemap-chart/

**Comment by joadan** [comment]
Hi, It should already be supported.
There is one example in the Chart Gallery

**Comment by yashshah7575** [comment]
I was able to figure this out. Thanks.
