### ISSUE TITLE
Update Documention

### ISSUE THREAD

**Issue by WukovatzD** [apexcharts/Blazor-ApexCharts#55]
Update documention with latest changes

Many functionalities and settings are only found under "apexcharts.js". Is there a way to add some settings like colours etc to your documentation?

Add version change history?

**Comment by joadan** [comment]
Hi 

Documentation should be up to date with the latest changes.  
However sometimes I have to test some things that have not been released, I try to make it more clear when that is the case.

Do you have anything specific that you see now that is not correct?
I'll try to add version history going forward.

**Comment by WukovatzD** [comment]
Thank you for the fast response
First of all, I would like to thank you for your great work!

I have edited my initial issue to make it more specific.
