### ISSUE TITLE
Please use Dictionary<Type, JsonSerializerOptions>  instead of Dictionary<string, JsonSerializerOptions> 

### ISSUE THREAD

**Issue by oschakravarthi** [apexcharts/Blazor-ApexCharts#56]
Hi,

We are getting strange issues. The Json which gets generated by this chart is getting messed up. 
After troubleshooting, we found that the issue is in ChartSerializer. 

Requesting the below changes in ChartSerializer.

```
private static Dictionary<Type, JsonSerializerOptions> _serializerOptions = new Dictionary<Type, JsonSerializerOptions>();
var key = typeof(TItem);
```

![image](https://user-images.githubusercontent.com/29388049/157607857-96f26175-de4a-41ab-bb6e-19debbe03b7f.png)

**Comment by joadan** [comment]
Hi,

I have made the update, new release should be available soon.

**Comment by joadan** [comment]
Fixed in [Release v0.8.2-beta](https://github.com/apexcharts/Blazor-ApexCharts/releases/tag/v0.8.2-beta)

**Comment by oschakravarthi** [comment]
Thank you.

**Comment by joadan** [comment]
Thanks
