### ISSUE TITLE
PlotOptionsBar doesn't contain borderRadius

### ISSUE THREAD

**Issue by shareonline** [apexcharts/Blazor-ApexCharts#58]
Great implementation so far! Trying to do some dashboarding with this, and so far really pleased. Great work!

I noticed the PlotOptionsBar doesn't have input for borderRadius 
![image](https://user-images.githubusercontent.com/17081368/158146834-61e3e8e8-e06f-4de3-b602-e9d0f7a93d8d.png)
It does however have input for Ending and StartingShape. It just doesn't seem to have any impact.

But as far as I can see on apex, there is a "difference" on bar charts and column charts, which I guess is sort of the same.

**Comment by joadan** [comment]
Hello,

Thanks for reporting this. 
Looks like I have missed some changes in the ApexChart.js options.
I'll try to address this as soon as I can.

**Comment by joadan** [comment]
Fixed in  v0.9.0-beta
