### ISSUE TITLE
All X values in a single row in Timeline chart

### ISSUE THREAD

**Issue by oschakravarthi** [apexcharts/Blazor-ApexCharts#59]
Hi,
I have data like below.  (Time ranges of when my machine was up and down)
It is getting plotted like 
![image](https://user-images.githubusercontent.com/29388049/158502950-bbf08840-9286-4e96-b969-544b66a2ba17.png)

I want it to be plotted like 
![image](https://user-images.githubusercontent.com/29388049/158503174-ae8f18cb-c724-4503-98d4-e8b7f35dcec1.png)

Any solution?

```
series: [
          // George Washington
          {
            name: 'MachineState',
            data: [
              {
                x: 'Up',
                y: [
                  new Date(1789, 3, 30).getTime(),
                  new Date(1797, 2, 4).getTime()
                ]
              },{
                x: 'Down',
                y: [
                  new Date(1797, 2, 4).getTime(),
                  new Date(1801, 2, 4).getTime()
                ]
              },
			  {
                x: 'Up',
                y: [
                  new Date(1792, 3, 30).getTime(),
                  new Date(1795, 2, 4).getTime()
                ]
              },
			  
            ]
          },
		   
```

**Comment by joadan** [comment]
Hi,

I added support for this in 0.9.0-beta.
Please check https://apexcharts.github.io/Blazor-ApexCharts/rangebar-charts#grouped
