### ISSUE TITLE
Hello,

### ISSUE THREAD

**Issue by ShrewdMensch** [apexcharts/Blazor-ApexCharts#70]
Hello,
I am still getting the error and I have updated to version 0.9.3-beta.

Below is my .csproj file:

![image](https://user-images.githubusercontent.com/56337863/161432888-a134ae55-cdf0-460f-9d2b-2ba3b2a1d3f4.png)

Kindly assist.
THanks

_Originally posted by @ShrewdMensch in https://github.com/apexcharts/Blazor-ApexCharts/issues/68#issuecomment-1086880732_

**Comment by joadan** [comment]
Sorry for this, please try [v0.9.4-beta](https://github.com/apexcharts/Blazor-ApexCharts/tree/v0.9.4-beta)

I close this issue now and I'll re-open the original issue,.
