### ISSUE TITLE
No X Axis Labels in DateTime LineChart

### ISSUE THREAD

**Issue by maxreb** [apexcharts/Blazor-ApexCharts#71]
I think after commit https://github.com/apexcharts/Blazor-ApexCharts/commit/21434e3775b717ea71f73090ad118af726944870 X-Axis labels for DateTime LineCharts won't show up anymore:
![image](https://user-images.githubusercontent.com/39700092/161615645-f1c13fd4-9f56-4907-ad92-d8b130a06ee7.png)
the only way I found to display something in the x-axis is by adding the Labels.Formatter manually:
```
options.Xaxis = new()
        {
            Labels = new()
            {
                Show = true,
                Formatter = "function(value){return value;}"
            },
            //...
```
which will show the epoch unix time in ms:
![image](https://user-images.githubusercontent.com/39700092/161615923-98cd06e2-106c-4fe4-a2ec-d471ab0eb805.png)

**Comment by joadan** [comment]
Thanks for reporting... 

I'll ahve a look

**Comment by joadan** [comment]
Hmm it works for me in the samples 
https://apexcharts.github.io/Blazor-ApexCharts/line-charts#datetime

![image](https://user-images.githubusercontent.com/8363110/161617072-b4f7cbd2-ee9f-478f-a622-ff2237134ccb.png)

**Comment by maxreb** [comment]
> Hmm it works for me in the samples

Yes, for me too. But I'm not sure if the newest version is hosted. If you download the current version (0.9.4) via NuGet or clone this repository and start the Docs Sample it won't show anymore.
