### ISSUE TITLE
How to Multiple Y-axis

### ISSUE THREAD

**Issue by semukov** [apexcharts/Blazor-ApexCharts#74]
Hi!
Can i do chart with two Y-axis. I didn't find any example.
I need two Y-axis. First from left Y-axis and from rigth Y-axis. I need use two series on chart with one X-axis

**Comment by joadan** [comment]
Hi
We don’t have a sample for it yet, but have you checked the docs at https://apexcharts.com/docs/chart-types/multiple-yaxis-scales/

**Comment by semukov** [comment]
Thank you, @joadan!
Good Job!
Here is a simple sample for multiple Y-axis:

`<ApexChart Options="@options" TItem="AmountRateItem" >
        <ApexPointSeries TItem="AmountRateItem"
                         Items="AmountRateItems"
                         Name="Amount"
                         SeriesType="SeriesType.Line"
                         XValue="@(e => e.Date.ToShortDateString())"
                         YAggregate="@(e => e.Sum(e => (decimal)e.Amount))"
                         OrderByDescending="e=>e.X" />

        <ApexPointSeries TItem="AmountRateItem"
                         Items="AmountRateItems"
                         Name="Rate"
                         SeriesType="SeriesType.Line"
                         XValue="@(e => e.Date.ToShortDateString())"
                         YAggregate="@(e => e.Sum(e => (decimal)e.Rate))"
                         OrderByDescending="e=>e.X" />        
    </ApexChart>

@code {       
    private ApexChartOptions<AmountRateItem> options;
    private IEnumerable<AmountRateItem> AmountRateItems;

    protected override void OnInitialized() {
        options = new ApexChartOptions<AmountRateItem> {
            Yaxis = new List<YAxis> {
                new YAxis { Title = new AxisTitle{ Text = "Series A"  } },
                new YAxis { Title = new AxisTitle{ Text = "Series B"  }, Opposite = true },
            }
        };

        AmountRateItems = new List<AmountRateItem>() {
             new AmountRateItem {
                 Date = DateTime.Parse("30.11.2021"), Amount = 750, Rate = 7.8
             },
             new AmountRateItem {
                 Date = DateTime.Parse("31.12.2021"), Amount = 600, Rate = 8.3
             },
             new AmountRateItem {
                 Date = DateTime.Parse("31.01.2022"), Amount = 700, Rate = 5
             },
             new AmountRateItem {
                 Date = DateTime.Parse("28.02.2022"), Amount = 650, Rate = 9.5
             },
             new AmountRateItem {
                 Date = DateTime.Parse("31.03.2022"), Amount = 300, Rate = 8
             },
             new AmountRateItem {
                 Date = DateTime.Parse("04.04.2022"), Amount = 250, Rate = 7
             },
             new AmountRateItem {
                 Date = DateTime.Parse("05.04.2022"), Amount = 200, Rate = 6.3
             }
        };
    }

    public class AmountRateItem {
        public DateTime Date { get; set; }
        public double Amount { get; set; }
        public double Rate { get; set; }
    }
}`
