### ISSUE TITLE
Legend not showing when there is only 1 ApexPointSeries

### ISSUE THREAD

**Issue by emmanuelpare** [apexcharts/Blazor-ApexCharts#75]
![image](https://user-images.githubusercontent.com/6441000/162527669-4a83a52d-e2fc-48a2-aefb-2ae6fa732ffb.png)
![image](https://user-images.githubusercontent.com/6441000/162527737-50f45251-954c-43f5-a626-cdaaf357e6ae.png)

Hi when there is only 1 Series in the chart the Legend is not showing.... As you can see in my screenshot it work for the first one but not for the second chart (legend appear if Iam adding a dummy serie).   Is this expected?  I would like to always show the legend even if there is only 1 item.

Btw Iam following you development its the best solution for charts in Blazor!

**Comment by joadan** [comment]
Hi,

Have you tried to set the Legend option ShowForSingleSeries to true?
I believe the default value is false.

**Comment by dwildcash** [comment]
We’ll look like you are absolutely right I was not aware of that option! Will try it tomorrow!  Thanks to have checked

**Comment by joadan** [comment]
Clean up
