### ISSUE TITLE
Bar Chart With Markers

### ISSUE THREAD

**Issue by ckieler86** [apexcharts/Blazor-ApexCharts#76]
Hello, 

I want to start by saying thanks for this great repo!

I was hoping to create a graph like this :

![image](https://user-images.githubusercontent.com/62707326/162530112-17d075fb-40b4-4a2e-8d7b-c6165731177f.png)

Link to the [Apex Doc here](https://apexcharts.com/javascript-chart-demos/bar-charts/bar-with-markers/#)

 I don't believe this is currently possible to do with what's available. Am I correct in this statement?

**Comment by joadan** [comment]
Hi,

I'm afraid you are correct, it's currently not supported.
I'll try to add it asap, it's a priority.

**Comment by joadan** [comment]
I added a sample https://apexcharts.github.io/Blazor-ApexCharts/bar-charts#markers
Please note this is not released.

**Comment by joadan** [comment]
Fixed in v0.9.6-beta

**Comment by ckieler86** [comment]
Thank you for the quick update! It's working beautifully.
