### ISSUE TITLE
Make it possible to serialize custom data to a datapoint

### ISSUE THREAD

**Issue by joadan** [apexcharts/Blazor-ApexCharts#79]
We should provide an option to pass additional data to be serialized to a datapoint. This is convienient for custom data that needs to be available on the javascript side. For exampel using in javascript formatters.

**Comment by joadan** [comment]
Some ideas https://github.com/apexcharts/apexcharts.js/issues/1873

**Comment by joadan** [comment]
Sample https://apexcharts.github.io/Blazor-ApexCharts/features/formatters#pass%20extra%20data

**Comment by ckieler86** [comment]
The .Extra property does not appear to be available in v0.9.6.0, am I missing something? 

![image](https://user-images.githubusercontent.com/62707326/163202048-d0f498c1-cebf-4c70-b06f-da60175fb9db.png)

**Comment by joadan** [comment]
Sorry I was unclear, it is not released. I wanted to be sure this is what you wanted before releasing

**Comment by ckieler86** [comment]
@joadan  Yes, this will work great!

**Comment by joadan** [comment]
Fixed in v0.9.7-beta
