### ISSUE TITLE
CAN'T COMBINE HISTOGRAM WITH OTHER CHART TYPES

### ISSUE THREAD

**Issue by ShrewdMensch** [apexcharts/Blazor-ApexCharts#84]
Hello,

I tried to combine Histogram with a line chart (for my use case), unfortunately, I go this error:

**[2022-05-06T18:24:04.023Z] Error: System.AggregateException: One or more errors occurred. (Chart Type Histogram can not be mixed)
 ---> System.Exception: Chart Type Histogram can not be mixed
   at ApexCharts.ApexChart`1.GetMixedChartType(ChartType chartType)
   at ApexCharts.ApexChart`1.SetSeries()
   at ApexCharts.ApexChart`1.PrepareChart()
   at ApexCharts.ApexChart`1.RenderChartAsync()
   at ApexCharts.ApexChart`1.OnAfterRenderAsync(Boolean firstRender)
   --- End of inner exception stack trace ---**

Kindly help look into it.

Thanks

**Comment by joadan** [comment]
Hi,

I'm sorry but I don't belive it's possible to mix a histogram with otherchart types in apexcharts.js.

**Comment by joadan** [comment]
You might be able to get a similar effect by setting the bar columwidth to 100%. 
PlotOptions -Bar -ColumnWidth.

**Comment by ShrewdMensch** [comment]
Oh! I have tried that and it works!

Thanks
