### ISSUE TITLE
@ref combined with PointSeries parameter

### ISSUE THREAD

**Issue by WukovatzD** [apexcharts/Blazor-ApexCharts#85]
I'm sorry that I have to open another issue already. I have not managed to use the functions of `PointColor` when I want to update a chart at the same time. The colors are not displayed. Furthermore the labels are not displayed correctly. Only `series-x` is displayed.

Could it be that I have overlooked some option or is this currently not yet implemented?

**Comment by joadan** [comment]
Hi,

This looks like a bug, I'll look into it.

**Comment by joadan** [comment]
@WukovatzD, Could you please provide some details on how to reproduce.

You are using the PointColor function and the UpdateSeries Method?
What chart type are you using? You mention the labels are not correct, in what way?

If you could use one of the existing samples and just add code to reproduce that would help a lot.

**Comment by WukovatzD** [comment]
Below the important parts of my code:
```csharp
@if (_data is not null)
{
    <ApexChart Width="350" @ref="@_chart" TItem="CurrentValueWithTimeMarkDetailCountRecord">
        <ApexPointSeries TItem="CurrentValueWithTimeMarkDetailCountRecord"
                     Items="_data"
                     Name="States"
                     SeriesType="SeriesType.Pie"
                     XValue="@(e => e.Name)"
                     PointColor="@(e => StateRepository.Data.First(x => x.Id == e.Id).HexColor)"
                     YAggregate="@(e => e.Sum(x => x.Count))" />
    </ApexChart>
}

@code {
    [Parameter] public int UnitId { get; set; }

    private List<CurrentValueWithTimeMarkDetailCountRecord> _data = new();
    private ApexChart<CurrentValueWithTimeMarkDetailCountRecord> _chart;

    private Task _backgroundUpdateTask;
    private bool _disposed;

    protected override void OnAfterRender(bool firstRender)
    {
        if (!firstRender) return;

        _backgroundUpdateTask = Task.Run(async () =>
        {
            while (!_disposed)
            {
                await UpdateChartSeries();
                await Task.Delay(2000);
            }
        });
    }

    private async Task UpdateChartSeries()
    {
            if (_disposed) return;

            await SetData();
            await _chart.UpdateSeriesAsync(false);
            //await InvokeAsync(StateHasChanged);
    }

    private async Task SetData()
    {
        // Setting data this way is not working either
        //_data = await MachineRepositoryService.GetMaschineValuesWithDetailGroupCountAsync(UnitId);

        _data.Clear();
        _data.AddRange(await MachineRepositoryService.GetMaschineValuesWithDetailGroupCountAsync(UnitId));
    }

    public void Dispose()
    {
        _disposed = true;
        _chart?.Dispose();
    }
}
```
The graphics below is the outcome:
![grafik](https://user-images.githubusercontent.com/57444032/167561844-72865b21-5d51-4e6d-835f-3507c3c47985.png)

The set of colors which should be there:

```
#ff0000
#00c800
#00aaff
#ffaa00
#ffff00
#55ffff
#c86400
#aa55ff
#989c9b
```

Setting the colors the way below works for the colors, however not for the labels. Furthermore using `PointColor` in the ApexPointSeries is not working in both cases:
```
    private void SetOptions()
    {
        _options.Labels = StateRepository.Data.Select(x => x.Name).ToList();
        _options.Colors = StateRepository.Data.Select(x => x.HexColor).ToList();
    }
```

If I omit the `@ref` it works as desired. So my assumption is that it has to do with the `@ref`...
Hope this helps. If you need some more information just let me know! 

Thank you for taking care of this problem!!

**Comment by joadan** [comment]
Hi,

Thank you for your example.
Could you do test to change the series type to bar instead of Pie  to see if you get the same issue. 
I'm pretty sure this is related to how NoAxisCharts work in Apexcharts. 

Onther test could be to render the chart instead of UpdateSeries.

**Comment by WukovatzD** [comment]
> 

Switching the chart type to `Bar` was successful. Labels and Colors are displayed in the correct way. Updating (UpdateSeries) is working with `Bar` too!

`UpdateOptionsAsync` results in that the chart is printed in the correct colors and labels and updated.

`RenderAsync` seems to work as well.

I hope my test result will help you!
Best regards
DW

**Comment by joadan** [comment]
Thank you,

The result is what I expected, for your use case using a no axis chart I would say that you should use UpdateOptionsAsync rather then UpdateSeriesAsync. The reason for this is that UpdateSeries is only sending the series data, and for a no axis chart this is limited to the values, all other settings like labels and colors are set in the options. 

Please let me know if this would work for you.

**Comment by WukovatzD** [comment]
Great jeah it will work! Could you add this information into documentation?

Thanks for the fast reply helped me a lot!

**Comment by joadan** [comment]
Great, Yes I will update the documentation.
