### ISSUE TITLE
How do I make a negative Bars in Blazor-ApexChart

### ISSUE THREAD

**Issue by ShrewdMensch** [apexcharts/Blazor-ApexCharts#86]
Please, is it possible to make the colors of bars red if the value is negative with Blazor-ApexChart. If yes, I would love to know how I can achieve that. I have tried the demo/documentation website, but I did not find any similar example.

Thanks

**Comment by joadan** [comment]
Hi,

Please check this, https://apexcharts.github.io/Blazor-ApexCharts/bar-charts#negative%20values

**Comment by ShrewdMensch** [comment]
Hi,
Sorry for delayed response from me.

This does not seems to work for me when the Bar Chart is mixed with line chart(s) or other type of supported chart(s).
How do I make it work in this scenario?

**NB: I am also passing an instance of ChartOptions to the ApexChart component.**

Thanks
