### ISSUE TITLE
Negatives Bars doesn't seem to work in mixed charts

### ISSUE THREAD

**Issue by ShrewdMensch** [apexcharts/Blazor-ApexCharts#88]
Hi,
Sorry for delayed response from me.

This does not seems to work for me when the Bar Chart is mixed with line chart(s) or other type of supported chart(s).
How do I make it work in this scenario?

**NB: I am also passing an instance of ChartOptions to the ApexChart component.**

Thanks

_Originally posted by @ShrewdMensch in https://github.com/apexcharts/Blazor-ApexCharts/issues/86#issuecomment-1129838242_

**Comment by joadan** [comment]
Hello,

Currently Apexcharts.js do not support negative colors for line and area charts.

https://github.com/apexcharts/apexcharts.js/issues/596

**Comment by ShrewdMensch** [comment]
Thanks for the information but I don't mean a negative line or area chart. What I meant was that when I combine bar chart with a line chart (mixed chart), the bars with negative values can not be given a certain color.
