### ISSUE TITLE
Radar Chart Notations

### ISSUE THREAD

**Issue by WukovatzD** [apexcharts/Blazor-ApexCharts#89]
Hello!

Could you a the Radar Chart type to the documentation?
In addition: No notations next to the chart are shown.

The blue signed parts should show the name of the the value, shoudn´t they?
Below the chart:

![grafik](https://user-images.githubusercontent.com/57444032/169255836-62e56e0a-c9d4-490f-bae5-224ff59152ab.png)

**Comment by joadan** [comment]
Hi,
Looks like a bug, I’ll look into it.

**Comment by joadan** [comment]
please check https://apexcharts.github.io/Blazor-ApexCharts/radar-charts 

This fix is not yet released

**Comment by joadan** [comment]
Fixed in v0.9.10-beta
