### ISSUE TITLE
ApexChart.Chart.Height and ApexChart.Chart.Width not working 

### ISSUE THREAD

**Issue by ckieler86** [apexcharts/Blazor-ApexCharts#90]
Hello, 

Great work so far on this library! 

I noticed when setting ApexChart.Chart.Height and ApexChart.Chart.Width I do not see a difference in the height and width of the chart. Am I doing something wrong or is it not working? 

![image](https://user-images.githubusercontent.com/62707326/169563858-a6c59420-f4b8-4d2f-99df-8dd6a030958e.png)

**Comment by joadan** [comment]
Thank you for reporting.

This is a bug. You can set the width and height on the Razor component  but you can't set it directly in the options.
A fix is coming soon.

**Comment by joadan** [comment]
Fixed in v0.9.10-beta
