### ISSUE TITLE
Can't find JS Files. 

### ISSUE THREAD

**Issue by QuietDesperationDev** [apexcharts/Blazor-ApexCharts#93]
Getting this current error message: 
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not find 'blazor_apexchart.renderChart' ('blazor_apexchart' was undefined).
      Error: Could not find 'blazor_apexchart.renderChart' ('blazor_apexchart' was undefined).

Scripts: 
![image](https://user-images.githubusercontent.com/98842760/170120694-44f651a2-c14c-498d-a6f1-5eae0ac3fb4f.png)

Everything is added to the _imports.razor page. 

.NET 6 Blazor WASM

**Comment by joadan** [comment]
Hi, 

this is strange, have you checked the browser network tab, If you see any errors?

![image](https://user-images.githubusercontent.com/8363110/170676161-2087e249-e64b-4bf6-ab4c-32e37172c695.png)

**Comment by JawadJaber** [comment]
I have noticed this issue appears in MS Edge, while in Chrome it is ok.

**Comment by joadan** [comment]
Hi,

I created a minimal sample, https://github.com/joadan/WasmBlazorApexChartsSample. 
This works for me in Chrome, Firefox and Edge.

Could you try it out?

**Comment by JawadJaber** [comment]
I tried it, it works fine in Edge. May be it is caching problem.

**Comment by QuietDesperationDev** [comment]
I came back to look at this to see if it had been resolved or not. While looking around this morning it doesn't look like the files are being output to _content on build either.

**Comment by QuietDesperationDev** [comment]
I just created a new Blazor Server App (.NET 6, VS 2022) and this is the error that it is producing with that application. 

![image](https://user-images.githubusercontent.com/98842760/177354347-77094c9e-26a9-4367-bf43-8d9afda1776e.png)

I am going to play around with it a bit more today and report back if I figure anything out.

**Comment by QuietDesperationDev** [comment]
I was actually able to resolve this by making the script reference the first reference to external scripts in my body tag.
