### ISSUE TITLE
Line Chart XAxis and YAxis Label Color not working

### ISSUE THREAD

**Issue by taylorjimbo** [apexcharts/Blazor-ApexCharts#94]
I can change the grids lines and background and the font size, but I can seem to change either the X or Y axis label colors.

`options.Grid = new Grid { BorderColor = "Red" };

        options.Xaxis = new XAxis
        {
            AxisBorder = new AxisBorder { Show = false },
            AxisTicks = new AxisTicks { Show = false },
            Tooltip = new AxisTooltip { Enabled = false },
            Labels = new XAxisLabels { Style = new AxisLabelStyle { Colors = new ApexCharts.Color { String = "Red" }, FontSize = "20" } }
        };

        options.Yaxis = new List<YAxis>
        {
            new YAxis
            {
                AxisTicks = new AxisTicks { Show = false },
                AxisBorder = new AxisBorder { Show = false },
                Tooltip = new AxisTooltip { Enabled = false},
                Max = 72, 
                Labels = new YAxisLabels { Style = new AxisLabelStyle { Colors = "Red", FontSize = "20" }}
            }
        };`

**Comment by joadan** [comment]
Thank you for reporting.

This is a bug, I'll try to fix this asap.

**Comment by joadan** [comment]
https://apexcharts.github.io/Blazor-ApexCharts/features/axis#axis%20style 

Please note, not yet released..

**Comment by joadan** [comment]
Fixed in v0.9.10-beta
