### ISSUE TITLE
[HELP] Can you help me figure this whole thing out?

### ISSUE THREAD

**Issue by BrianJavier99** [apexcharts/Blazor-ApexCharts#95]
Hello, I am new to this and am trying to reproduce some of your samples, specifically the Basic one in here:
https://apexcharts.github.io/Blazor-ApexCharts/bar-charts

I have installed the package from nuget and added these to index.html
```
<script src="_content/Blazor-ApexCharts/js/apex-charts.min.js"></script>
<script src="_content/Blazor-ApexCharts/js/blazor-apex-charts.js"></script>
```

I have also added `@using ApexCharts;` to my _Imports.razor

I tried copy and pasting the source codes from demo,
```
<DemoContainer>
<ApexChart TItem="TItem"
           Title="Order Net Value">

    <ApexPointSeries TItem="Order"
                Items="Orders"
                Name="Gross Value"
                XValue="@(e => e.Country)"
                YAggregate="@(e => e.Sum(e => e.GrossValue))"
                OrderByDescending="e=>e.Y"
                SeriesType="SeriesType.Bar"/>

    <ApexPointSeries TItem="Order"
                Items="Orders"
                Name="Net Value"
                XValue="@(e => e.Country)"
                YAggregate="@(e => e.Sum(e => e.NetValue))"
                OrderByDescending="e=>e.Y"
                SeriesType="SeriesType.Bar"/>
</ApexChart>
</DemoContainer>

@code {
    private List<Order> Orders { get; set; } = SampleData.GetOrders();
}

```

 and I get the following errors:

> The name 'SampleData' does not exist in the current context
> The type or namespace name 'Order' could not be found (are you missing a using directive o an assembly reference?)

Where can I find the declaration for the name 'Order', and what datatype should 'SampleData' be? Thank you very much and I hope I can be enlightened with how this work.

**Comment by joadan** [comment]
Hello,

Order is just a sample class, you should use your class that holds your data.
Please see the self contained sample below..

```
<ApexChart TItem="Team"
           Title="Teams Score"
           Width=400>

    <ApexPointSeries TItem="Team"
                     Items="teams"
                     Name="points"
                     SeriesType="SeriesType.Pie"
                     XValue="@(e => e.Name)"
                     YValue="@(e => e.Points)" />
</ApexChart>

@code {
    private List<Team> teams = new();
    protected override void OnInitialized()
    {
        teams.Add(new Team { Name = "Barcelona", Points = 23 });
        teams.Add(new Team { Name = "Real Madrid", Points = 12 });
        teams.Add(new Team { Name = "Alavés", Points = 35 });
        teams.Add(new Team { Name = "Celta Vigo", Points = 16 });
    }

    public class Team
    {
        public string Name { get; set; }
        public int Points { get; set; }
    }
}

```

**Comment by BrianJavier99** [comment]
Ah I see, the `TItem` would be the custom class that you will create while the `Items` would be literally a list of the objects using custom class that you have made.

Thank you, I am now able to make this work on my project. You have been a great help!
