### ISSUE TITLE
Chart wont draw on Duplicate X-Axis value

### ISSUE THREAD

**Issue by ckieler86** [apexcharts/Blazor-ApexCharts#96]
Hello again! 

Thank you for your contributions so far. I have noticed a potential bug in the software.

When providing the same x-axis value (string), the chart does not draw. 

I am using a Line chart with 2 data sets (2 line series). I can confirm that the data sets both contain a value for the both instances of the x axis value. I have also tested with and area chart with only 1 data set, and I receive the same results.

I can see that there is data, because the tooltips show, but the lines aren't drawn and the x axis that should have been shown twice is only shown once.

![image](https://user-images.githubusercontent.com/62707326/170307437-c2472e73-41b5-477f-80bb-d28df1888465.png)

I've testing duplicate x axis values against the ApexJs library and it works there. When testing using plain Apex charts JS the duplicate value gets shown twice

![image](https://user-images.githubusercontent.com/62707326/170307673-c00fc667-c966-4471-923d-ab8c209178cc.png)

My current solution is to append a unique value to the end of the X-axis value, when I do this the charts draw and work as expected. Is this a bug within this library or could there be a conflicting setting that I am using?

**Comment by ckieler86** [comment]
Changing the value I passed in from a string to a DateTime and adding XAxisType="XAxisType.Datetime" fixed this issue for me. 

This may still be a bug within XAxisType.Category but if you are unable to replicate then it may have just been an issue with my dataset. 

Thanks

**Comment by joadan** [comment]
Thank you, I'll close this one.
